dependencies {
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "2.0.0"
	compileOnly group: "org.osgi", name: "org.osgi.compendium", version: "5.0.0"
	compile group: 'javax.mail', name: 'mail', version: '1.4'
	compileOnly project(":modules:Email-api")
	compile group: 'org.freemarker', name: 'freemarker', version: '2.3.15'
}