/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rpower.unpaid.unclaimed.dividend.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.rpower.unpaid.unclaimed.dividend.model.RpowerUnpaidUnclaimedDevidend;
import com.rpower.unpaid.unclaimed.dividend.service.RpowerUnpaidUnclaimedDevidendLocalServiceUtil;

/**
 * The extended model base implementation for the RpowerUnpaidUnclaimedDevidend service. Represents a row in the &quot;RPOWER_UNPAIDUNCLAIMEDDIVIDEND&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RpowerUnpaidUnclaimedDevidendImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RpowerUnpaidUnclaimedDevidendImpl
 * @see RpowerUnpaidUnclaimedDevidend
 * @generated
 */
@ProviderType
public abstract class RpowerUnpaidUnclaimedDevidendBaseImpl
	extends RpowerUnpaidUnclaimedDevidendModelImpl
	implements RpowerUnpaidUnclaimedDevidend {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rpower unpaid unclaimed devidend model instance should use the {@link RpowerUnpaidUnclaimedDevidend} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			RpowerUnpaidUnclaimedDevidendLocalServiceUtil.addRpowerUnpaidUnclaimedDevidend(this);
		}
		else {
			RpowerUnpaidUnclaimedDevidendLocalServiceUtil.updateRpowerUnpaidUnclaimedDevidend(this);
		}
	}
}