/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rinfra.news.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.rinfra.news.model.PressNews;
import com.rinfra.news.model.PressNewsModel;
import com.rinfra.news.model.PressNewsSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the PressNews service. Represents a row in the &quot;Rinfra_news&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link PressNewsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PressNewsImpl}.
 * </p>
 *
 * @author Vipin Singh
 * @see PressNewsImpl
 * @see PressNews
 * @see PressNewsModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class PressNewsModelImpl extends BaseModelImpl<PressNews>
	implements PressNewsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a press news model instance should use the {@link PressNews} interface instead.
	 */
	public static final String TABLE_NAME = "Rinfra_news";
	public static final Object[][] TABLE_COLUMNS = {
			{ "newsId", Types.BIGINT },
			{ "headLine", Types.VARCHAR },
			{ "publication", Types.VARCHAR },
			{ "downloadUrl", Types.VARCHAR },
			{ "fileName", Types.VARCHAR },
			{ "date_", Types.TIMESTAMP },
			{ "year", Types.INTEGER },
			{ "month", Types.INTEGER },
			{ "show_", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("newsId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("headLine", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("publication", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("downloadUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("date_", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("year", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("month", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("show_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table Rinfra_news (newsId LONG not null primary key,headLine VARCHAR(75) null,publication VARCHAR(75) null,downloadUrl VARCHAR(75) null,fileName VARCHAR(75) null,date_ DATE null,year INTEGER,month INTEGER,show_ VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table Rinfra_news";
	public static final String ORDER_BY_JPQL = " ORDER BY pressNews.date DESC";
	public static final String ORDER_BY_SQL = " ORDER BY Rinfra_news.date_ DESC";
	public static final String DATA_SOURCE = "extDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.rinfra.news.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rinfra.news.model.PressNews"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.rinfra.news.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rinfra.news.model.PressNews"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.rinfra.news.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rinfra.news.model.PressNews"),
			true);
	public static final long MONTH_COLUMN_BITMASK = 1L;
	public static final long YEAR_COLUMN_BITMASK = 2L;
	public static final long DATE_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static PressNews toModel(PressNewsSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PressNews model = new PressNewsImpl();

		model.setNewsId(soapModel.getNewsId());
		model.setHeadLine(soapModel.getHeadLine());
		model.setPublication(soapModel.getPublication());
		model.setDownloadUrl(soapModel.getDownloadUrl());
		model.setFileName(soapModel.getFileName());
		model.setDate(soapModel.getDate());
		model.setYear(soapModel.getYear());
		model.setMonth(soapModel.getMonth());
		model.setShow(soapModel.getShow());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<PressNews> toModels(PressNewsSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<PressNews> models = new ArrayList<PressNews>(soapModels.length);

		for (PressNewsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.rinfra.news.service.util.ServiceProps.get(
				"lock.expiration.time.com.rinfra.news.model.PressNews"));

	public PressNewsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _newsId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setNewsId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _newsId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PressNews.class;
	}

	@Override
	public String getModelClassName() {
		return PressNews.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("newsId", getNewsId());
		attributes.put("headLine", getHeadLine());
		attributes.put("publication", getPublication());
		attributes.put("downloadUrl", getDownloadUrl());
		attributes.put("fileName", getFileName());
		attributes.put("date", getDate());
		attributes.put("year", getYear());
		attributes.put("month", getMonth());
		attributes.put("show", getShow());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long newsId = (Long)attributes.get("newsId");

		if (newsId != null) {
			setNewsId(newsId);
		}

		String headLine = (String)attributes.get("headLine");

		if (headLine != null) {
			setHeadLine(headLine);
		}

		String publication = (String)attributes.get("publication");

		if (publication != null) {
			setPublication(publication);
		}

		String downloadUrl = (String)attributes.get("downloadUrl");

		if (downloadUrl != null) {
			setDownloadUrl(downloadUrl);
		}

		String fileName = (String)attributes.get("fileName");

		if (fileName != null) {
			setFileName(fileName);
		}

		Date date = (Date)attributes.get("date");

		if (date != null) {
			setDate(date);
		}

		Integer year = (Integer)attributes.get("year");

		if (year != null) {
			setYear(year);
		}

		Integer month = (Integer)attributes.get("month");

		if (month != null) {
			setMonth(month);
		}

		String show = (String)attributes.get("show");

		if (show != null) {
			setShow(show);
		}
	}

	@JSON
	@Override
	public long getNewsId() {
		return _newsId;
	}

	@Override
	public void setNewsId(long newsId) {
		_newsId = newsId;
	}

	@JSON
	@Override
	public String getHeadLine() {
		if (_headLine == null) {
			return StringPool.BLANK;
		}
		else {
			return _headLine;
		}
	}

	@Override
	public void setHeadLine(String headLine) {
		_headLine = headLine;
	}

	@JSON
	@Override
	public String getPublication() {
		if (_publication == null) {
			return StringPool.BLANK;
		}
		else {
			return _publication;
		}
	}

	@Override
	public void setPublication(String publication) {
		_publication = publication;
	}

	@JSON
	@Override
	public String getDownloadUrl() {
		if (_downloadUrl == null) {
			return StringPool.BLANK;
		}
		else {
			return _downloadUrl;
		}
	}

	@Override
	public void setDownloadUrl(String downloadUrl) {
		_downloadUrl = downloadUrl;
	}

	@JSON
	@Override
	public String getFileName() {
		if (_fileName == null) {
			return StringPool.BLANK;
		}
		else {
			return _fileName;
		}
	}

	@Override
	public void setFileName(String fileName) {
		_fileName = fileName;
	}

	@JSON
	@Override
	public Date getDate() {
		return _date;
	}

	@Override
	public void setDate(Date date) {
		_columnBitmask = -1L;

		_date = date;
	}

	@JSON
	@Override
	public int getYear() {
		return _year;
	}

	@Override
	public void setYear(int year) {
		_columnBitmask |= YEAR_COLUMN_BITMASK;

		if (!_setOriginalYear) {
			_setOriginalYear = true;

			_originalYear = _year;
		}

		_year = year;
	}

	public int getOriginalYear() {
		return _originalYear;
	}

	@JSON
	@Override
	public int getMonth() {
		return _month;
	}

	@Override
	public void setMonth(int month) {
		_columnBitmask |= MONTH_COLUMN_BITMASK;

		if (!_setOriginalMonth) {
			_setOriginalMonth = true;

			_originalMonth = _month;
		}

		_month = month;
	}

	public int getOriginalMonth() {
		return _originalMonth;
	}

	@JSON
	@Override
	public String getShow() {
		if (_show == null) {
			return StringPool.BLANK;
		}
		else {
			return _show;
		}
	}

	@Override
	public void setShow(String show) {
		_show = show;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			PressNews.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PressNews toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PressNews)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PressNewsImpl pressNewsImpl = new PressNewsImpl();

		pressNewsImpl.setNewsId(getNewsId());
		pressNewsImpl.setHeadLine(getHeadLine());
		pressNewsImpl.setPublication(getPublication());
		pressNewsImpl.setDownloadUrl(getDownloadUrl());
		pressNewsImpl.setFileName(getFileName());
		pressNewsImpl.setDate(getDate());
		pressNewsImpl.setYear(getYear());
		pressNewsImpl.setMonth(getMonth());
		pressNewsImpl.setShow(getShow());

		pressNewsImpl.resetOriginalValues();

		return pressNewsImpl;
	}

	@Override
	public int compareTo(PressNews pressNews) {
		int value = 0;

		value = DateUtil.compareTo(getDate(), pressNews.getDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PressNews)) {
			return false;
		}

		PressNews pressNews = (PressNews)obj;

		long primaryKey = pressNews.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		PressNewsModelImpl pressNewsModelImpl = this;

		pressNewsModelImpl._originalYear = pressNewsModelImpl._year;

		pressNewsModelImpl._setOriginalYear = false;

		pressNewsModelImpl._originalMonth = pressNewsModelImpl._month;

		pressNewsModelImpl._setOriginalMonth = false;

		pressNewsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PressNews> toCacheModel() {
		PressNewsCacheModel pressNewsCacheModel = new PressNewsCacheModel();

		pressNewsCacheModel.newsId = getNewsId();

		pressNewsCacheModel.headLine = getHeadLine();

		String headLine = pressNewsCacheModel.headLine;

		if ((headLine != null) && (headLine.length() == 0)) {
			pressNewsCacheModel.headLine = null;
		}

		pressNewsCacheModel.publication = getPublication();

		String publication = pressNewsCacheModel.publication;

		if ((publication != null) && (publication.length() == 0)) {
			pressNewsCacheModel.publication = null;
		}

		pressNewsCacheModel.downloadUrl = getDownloadUrl();

		String downloadUrl = pressNewsCacheModel.downloadUrl;

		if ((downloadUrl != null) && (downloadUrl.length() == 0)) {
			pressNewsCacheModel.downloadUrl = null;
		}

		pressNewsCacheModel.fileName = getFileName();

		String fileName = pressNewsCacheModel.fileName;

		if ((fileName != null) && (fileName.length() == 0)) {
			pressNewsCacheModel.fileName = null;
		}

		Date date = getDate();

		if (date != null) {
			pressNewsCacheModel.date = date.getTime();
		}
		else {
			pressNewsCacheModel.date = Long.MIN_VALUE;
		}

		pressNewsCacheModel.year = getYear();

		pressNewsCacheModel.month = getMonth();

		pressNewsCacheModel.show = getShow();

		String show = pressNewsCacheModel.show;

		if ((show != null) && (show.length() == 0)) {
			pressNewsCacheModel.show = null;
		}

		return pressNewsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{newsId=");
		sb.append(getNewsId());
		sb.append(", headLine=");
		sb.append(getHeadLine());
		sb.append(", publication=");
		sb.append(getPublication());
		sb.append(", downloadUrl=");
		sb.append(getDownloadUrl());
		sb.append(", fileName=");
		sb.append(getFileName());
		sb.append(", date=");
		sb.append(getDate());
		sb.append(", year=");
		sb.append(getYear());
		sb.append(", month=");
		sb.append(getMonth());
		sb.append(", show=");
		sb.append(getShow());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.rinfra.news.model.PressNews");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>newsId</column-name><column-value><![CDATA[");
		sb.append(getNewsId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>headLine</column-name><column-value><![CDATA[");
		sb.append(getHeadLine());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>publication</column-name><column-value><![CDATA[");
		sb.append(getPublication());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>downloadUrl</column-name><column-value><![CDATA[");
		sb.append(getDownloadUrl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileName</column-name><column-value><![CDATA[");
		sb.append(getFileName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>date</column-name><column-value><![CDATA[");
		sb.append(getDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>year</column-name><column-value><![CDATA[");
		sb.append(getYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>month</column-name><column-value><![CDATA[");
		sb.append(getMonth());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>show</column-name><column-value><![CDATA[");
		sb.append(getShow());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = PressNews.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			PressNews.class
		};
	private long _newsId;
	private String _headLine;
	private String _publication;
	private String _downloadUrl;
	private String _fileName;
	private Date _date;
	private int _year;
	private int _originalYear;
	private boolean _setOriginalYear;
	private int _month;
	private int _originalMonth;
	private boolean _setOriginalMonth;
	private String _show;
	private long _columnBitmask;
	private PressNews _escapedModel;
}