/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package rinfra.share.holders.doc.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import rinfra.share.holders.doc.model.ShareHoldersDoc;
import rinfra.share.holders.doc.service.ShareHoldersDocService;
import rinfra.share.holders.doc.service.persistence.ShareHoldersDocFinder;
import rinfra.share.holders.doc.service.persistence.ShareHoldersDocPersistence;
import rinfra.share.holders.doc.service.persistence.ShareHoldersFinder;
import rinfra.share.holders.doc.service.persistence.ShareHoldersPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the share holders doc remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link rinfra.share.holders.doc.service.impl.ShareHoldersDocServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see rinfra.share.holders.doc.service.impl.ShareHoldersDocServiceImpl
 * @see rinfra.share.holders.doc.service.ShareHoldersDocServiceUtil
 * @generated
 */
public abstract class ShareHoldersDocServiceBaseImpl extends BaseServiceImpl
	implements ShareHoldersDocService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link rinfra.share.holders.doc.service.ShareHoldersDocServiceUtil} to access the share holders doc remote service.
	 */

	/**
	 * Returns the share holders local service.
	 *
	 * @return the share holders local service
	 */
	public rinfra.share.holders.doc.service.ShareHoldersLocalService getShareHoldersLocalService() {
		return shareHoldersLocalService;
	}

	/**
	 * Sets the share holders local service.
	 *
	 * @param shareHoldersLocalService the share holders local service
	 */
	public void setShareHoldersLocalService(
		rinfra.share.holders.doc.service.ShareHoldersLocalService shareHoldersLocalService) {
		this.shareHoldersLocalService = shareHoldersLocalService;
	}

	/**
	 * Returns the share holders remote service.
	 *
	 * @return the share holders remote service
	 */
	public rinfra.share.holders.doc.service.ShareHoldersService getShareHoldersService() {
		return shareHoldersService;
	}

	/**
	 * Sets the share holders remote service.
	 *
	 * @param shareHoldersService the share holders remote service
	 */
	public void setShareHoldersService(
		rinfra.share.holders.doc.service.ShareHoldersService shareHoldersService) {
		this.shareHoldersService = shareHoldersService;
	}

	/**
	 * Returns the share holders persistence.
	 *
	 * @return the share holders persistence
	 */
	public ShareHoldersPersistence getShareHoldersPersistence() {
		return shareHoldersPersistence;
	}

	/**
	 * Sets the share holders persistence.
	 *
	 * @param shareHoldersPersistence the share holders persistence
	 */
	public void setShareHoldersPersistence(
		ShareHoldersPersistence shareHoldersPersistence) {
		this.shareHoldersPersistence = shareHoldersPersistence;
	}

	/**
	 * Returns the share holders finder.
	 *
	 * @return the share holders finder
	 */
	public ShareHoldersFinder getShareHoldersFinder() {
		return shareHoldersFinder;
	}

	/**
	 * Sets the share holders finder.
	 *
	 * @param shareHoldersFinder the share holders finder
	 */
	public void setShareHoldersFinder(ShareHoldersFinder shareHoldersFinder) {
		this.shareHoldersFinder = shareHoldersFinder;
	}

	/**
	 * Returns the share holders doc local service.
	 *
	 * @return the share holders doc local service
	 */
	public rinfra.share.holders.doc.service.ShareHoldersDocLocalService getShareHoldersDocLocalService() {
		return shareHoldersDocLocalService;
	}

	/**
	 * Sets the share holders doc local service.
	 *
	 * @param shareHoldersDocLocalService the share holders doc local service
	 */
	public void setShareHoldersDocLocalService(
		rinfra.share.holders.doc.service.ShareHoldersDocLocalService shareHoldersDocLocalService) {
		this.shareHoldersDocLocalService = shareHoldersDocLocalService;
	}

	/**
	 * Returns the share holders doc remote service.
	 *
	 * @return the share holders doc remote service
	 */
	public ShareHoldersDocService getShareHoldersDocService() {
		return shareHoldersDocService;
	}

	/**
	 * Sets the share holders doc remote service.
	 *
	 * @param shareHoldersDocService the share holders doc remote service
	 */
	public void setShareHoldersDocService(
		ShareHoldersDocService shareHoldersDocService) {
		this.shareHoldersDocService = shareHoldersDocService;
	}

	/**
	 * Returns the share holders doc persistence.
	 *
	 * @return the share holders doc persistence
	 */
	public ShareHoldersDocPersistence getShareHoldersDocPersistence() {
		return shareHoldersDocPersistence;
	}

	/**
	 * Sets the share holders doc persistence.
	 *
	 * @param shareHoldersDocPersistence the share holders doc persistence
	 */
	public void setShareHoldersDocPersistence(
		ShareHoldersDocPersistence shareHoldersDocPersistence) {
		this.shareHoldersDocPersistence = shareHoldersDocPersistence;
	}

	/**
	 * Returns the share holders doc finder.
	 *
	 * @return the share holders doc finder
	 */
	public ShareHoldersDocFinder getShareHoldersDocFinder() {
		return shareHoldersDocFinder;
	}

	/**
	 * Sets the share holders doc finder.
	 *
	 * @param shareHoldersDocFinder the share holders doc finder
	 */
	public void setShareHoldersDocFinder(
		ShareHoldersDocFinder shareHoldersDocFinder) {
		this.shareHoldersDocFinder = shareHoldersDocFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ShareHoldersDocService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ShareHoldersDoc.class;
	}

	protected String getModelClassName() {
		return ShareHoldersDoc.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = shareHoldersDocPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = rinfra.share.holders.doc.service.ShareHoldersLocalService.class)
	protected rinfra.share.holders.doc.service.ShareHoldersLocalService shareHoldersLocalService;
	@BeanReference(type = rinfra.share.holders.doc.service.ShareHoldersService.class)
	protected rinfra.share.holders.doc.service.ShareHoldersService shareHoldersService;
	@BeanReference(type = ShareHoldersPersistence.class)
	protected ShareHoldersPersistence shareHoldersPersistence;
	@BeanReference(type = ShareHoldersFinder.class)
	protected ShareHoldersFinder shareHoldersFinder;
	@BeanReference(type = rinfra.share.holders.doc.service.ShareHoldersDocLocalService.class)
	protected rinfra.share.holders.doc.service.ShareHoldersDocLocalService shareHoldersDocLocalService;
	@BeanReference(type = ShareHoldersDocService.class)
	protected ShareHoldersDocService shareHoldersDocService;
	@BeanReference(type = ShareHoldersDocPersistence.class)
	protected ShareHoldersDocPersistence shareHoldersDocPersistence;
	@BeanReference(type = ShareHoldersDocFinder.class)
	protected ShareHoldersDocFinder shareHoldersDocFinder;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}