/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package rinfra.share.holders.doc.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import rinfra.share.holders.doc.model.ShareHoldersDoc;
import rinfra.share.holders.doc.service.ShareHoldersDocLocalService;
import rinfra.share.holders.doc.service.persistence.ShareHoldersDocFinder;
import rinfra.share.holders.doc.service.persistence.ShareHoldersDocPersistence;
import rinfra.share.holders.doc.service.persistence.ShareHoldersFinder;
import rinfra.share.holders.doc.service.persistence.ShareHoldersPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the share holders doc local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link rinfra.share.holders.doc.service.impl.ShareHoldersDocLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see rinfra.share.holders.doc.service.impl.ShareHoldersDocLocalServiceImpl
 * @see rinfra.share.holders.doc.service.ShareHoldersDocLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class ShareHoldersDocLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements ShareHoldersDocLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link rinfra.share.holders.doc.service.ShareHoldersDocLocalServiceUtil} to access the share holders doc local service.
	 */

	/**
	 * Adds the share holders doc to the database. Also notifies the appropriate model listeners.
	 *
	 * @param shareHoldersDoc the share holders doc
	 * @return the share holders doc that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ShareHoldersDoc addShareHoldersDoc(ShareHoldersDoc shareHoldersDoc) {
		shareHoldersDoc.setNew(true);

		return shareHoldersDocPersistence.update(shareHoldersDoc);
	}

	/**
	 * Creates a new share holders doc with the primary key. Does not add the share holders doc to the database.
	 *
	 * @param pressId the primary key for the new share holders doc
	 * @return the new share holders doc
	 */
	@Override
	public ShareHoldersDoc createShareHoldersDoc(long pressId) {
		return shareHoldersDocPersistence.create(pressId);
	}

	/**
	 * Deletes the share holders doc with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param pressId the primary key of the share holders doc
	 * @return the share holders doc that was removed
	 * @throws PortalException if a share holders doc with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ShareHoldersDoc deleteShareHoldersDoc(long pressId)
		throws PortalException {
		return shareHoldersDocPersistence.remove(pressId);
	}

	/**
	 * Deletes the share holders doc from the database. Also notifies the appropriate model listeners.
	 *
	 * @param shareHoldersDoc the share holders doc
	 * @return the share holders doc that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ShareHoldersDoc deleteShareHoldersDoc(
		ShareHoldersDoc shareHoldersDoc) {
		return shareHoldersDocPersistence.remove(shareHoldersDoc);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(ShareHoldersDoc.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return shareHoldersDocPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link rinfra.share.holders.doc.model.impl.ShareHoldersDocModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return shareHoldersDocPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link rinfra.share.holders.doc.model.impl.ShareHoldersDocModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return shareHoldersDocPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return shareHoldersDocPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return shareHoldersDocPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public ShareHoldersDoc fetchShareHoldersDoc(long pressId) {
		return shareHoldersDocPersistence.fetchByPrimaryKey(pressId);
	}

	/**
	 * Returns the share holders doc with the primary key.
	 *
	 * @param pressId the primary key of the share holders doc
	 * @return the share holders doc
	 * @throws PortalException if a share holders doc with the primary key could not be found
	 */
	@Override
	public ShareHoldersDoc getShareHoldersDoc(long pressId)
		throws PortalException {
		return shareHoldersDocPersistence.findByPrimaryKey(pressId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(shareHoldersDocLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ShareHoldersDoc.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("pressId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(shareHoldersDocLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ShareHoldersDoc.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("pressId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(shareHoldersDocLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ShareHoldersDoc.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("pressId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return shareHoldersDocLocalService.deleteShareHoldersDoc((ShareHoldersDoc)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return shareHoldersDocPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the share holders docs.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link rinfra.share.holders.doc.model.impl.ShareHoldersDocModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of share holders docs
	 * @param end the upper bound of the range of share holders docs (not inclusive)
	 * @return the range of share holders docs
	 */
	@Override
	public List<ShareHoldersDoc> getShareHoldersDocs(int start, int end) {
		return shareHoldersDocPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of share holders docs.
	 *
	 * @return the number of share holders docs
	 */
	@Override
	public int getShareHoldersDocsCount() {
		return shareHoldersDocPersistence.countAll();
	}

	/**
	 * Updates the share holders doc in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param shareHoldersDoc the share holders doc
	 * @return the share holders doc that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ShareHoldersDoc updateShareHoldersDoc(
		ShareHoldersDoc shareHoldersDoc) {
		return shareHoldersDocPersistence.update(shareHoldersDoc);
	}

	/**
	 * Returns the share holders local service.
	 *
	 * @return the share holders local service
	 */
	public rinfra.share.holders.doc.service.ShareHoldersLocalService getShareHoldersLocalService() {
		return shareHoldersLocalService;
	}

	/**
	 * Sets the share holders local service.
	 *
	 * @param shareHoldersLocalService the share holders local service
	 */
	public void setShareHoldersLocalService(
		rinfra.share.holders.doc.service.ShareHoldersLocalService shareHoldersLocalService) {
		this.shareHoldersLocalService = shareHoldersLocalService;
	}

	/**
	 * Returns the share holders persistence.
	 *
	 * @return the share holders persistence
	 */
	public ShareHoldersPersistence getShareHoldersPersistence() {
		return shareHoldersPersistence;
	}

	/**
	 * Sets the share holders persistence.
	 *
	 * @param shareHoldersPersistence the share holders persistence
	 */
	public void setShareHoldersPersistence(
		ShareHoldersPersistence shareHoldersPersistence) {
		this.shareHoldersPersistence = shareHoldersPersistence;
	}

	/**
	 * Returns the share holders finder.
	 *
	 * @return the share holders finder
	 */
	public ShareHoldersFinder getShareHoldersFinder() {
		return shareHoldersFinder;
	}

	/**
	 * Sets the share holders finder.
	 *
	 * @param shareHoldersFinder the share holders finder
	 */
	public void setShareHoldersFinder(ShareHoldersFinder shareHoldersFinder) {
		this.shareHoldersFinder = shareHoldersFinder;
	}

	/**
	 * Returns the share holders doc local service.
	 *
	 * @return the share holders doc local service
	 */
	public ShareHoldersDocLocalService getShareHoldersDocLocalService() {
		return shareHoldersDocLocalService;
	}

	/**
	 * Sets the share holders doc local service.
	 *
	 * @param shareHoldersDocLocalService the share holders doc local service
	 */
	public void setShareHoldersDocLocalService(
		ShareHoldersDocLocalService shareHoldersDocLocalService) {
		this.shareHoldersDocLocalService = shareHoldersDocLocalService;
	}

	/**
	 * Returns the share holders doc persistence.
	 *
	 * @return the share holders doc persistence
	 */
	public ShareHoldersDocPersistence getShareHoldersDocPersistence() {
		return shareHoldersDocPersistence;
	}

	/**
	 * Sets the share holders doc persistence.
	 *
	 * @param shareHoldersDocPersistence the share holders doc persistence
	 */
	public void setShareHoldersDocPersistence(
		ShareHoldersDocPersistence shareHoldersDocPersistence) {
		this.shareHoldersDocPersistence = shareHoldersDocPersistence;
	}

	/**
	 * Returns the share holders doc finder.
	 *
	 * @return the share holders doc finder
	 */
	public ShareHoldersDocFinder getShareHoldersDocFinder() {
		return shareHoldersDocFinder;
	}

	/**
	 * Sets the share holders doc finder.
	 *
	 * @param shareHoldersDocFinder the share holders doc finder
	 */
	public void setShareHoldersDocFinder(
		ShareHoldersDocFinder shareHoldersDocFinder) {
		this.shareHoldersDocFinder = shareHoldersDocFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("rinfra.share.holders.doc.model.ShareHoldersDoc",
			shareHoldersDocLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"rinfra.share.holders.doc.model.ShareHoldersDoc");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ShareHoldersDocLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ShareHoldersDoc.class;
	}

	protected String getModelClassName() {
		return ShareHoldersDoc.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = shareHoldersDocPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = rinfra.share.holders.doc.service.ShareHoldersLocalService.class)
	protected rinfra.share.holders.doc.service.ShareHoldersLocalService shareHoldersLocalService;
	@BeanReference(type = ShareHoldersPersistence.class)
	protected ShareHoldersPersistence shareHoldersPersistence;
	@BeanReference(type = ShareHoldersFinder.class)
	protected ShareHoldersFinder shareHoldersFinder;
	@BeanReference(type = ShareHoldersDocLocalService.class)
	protected ShareHoldersDocLocalService shareHoldersDocLocalService;
	@BeanReference(type = ShareHoldersDocPersistence.class)
	protected ShareHoldersDocPersistence shareHoldersDocPersistence;
	@BeanReference(type = ShareHoldersDocFinder.class)
	protected ShareHoldersDocFinder shareHoldersDocFinder;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}