/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rinfra.unpaidunclaimedshares.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.rinfra.unpaidunclaimedshares.model.unpaidUnclaimedDevidend;
import com.rinfra.unpaidunclaimedshares.model.unpaidUnclaimedDevidendModel;
import com.rinfra.unpaidunclaimedshares.model.unpaidUnclaimedDevidendSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the unpaidUnclaimedDevidend service. Represents a row in the &quot;UNPAID_DIVIDEND_SHARE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link unpaidUnclaimedDevidendModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link unpaidUnclaimedDevidendImpl}.
 * </p>
 *
 * @author Mukesh Patidar
 * @see unpaidUnclaimedDevidendImpl
 * @see unpaidUnclaimedDevidend
 * @see unpaidUnclaimedDevidendModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class unpaidUnclaimedDevidendModelImpl extends BaseModelImpl<unpaidUnclaimedDevidend>
	implements unpaidUnclaimedDevidendModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a unpaid unclaimed devidend model instance should use the {@link unpaidUnclaimedDevidend} interface instead.
	 */
	public static final String TABLE_NAME = "UNPAID_DIVIDEND_SHARE";
	public static final Object[][] TABLE_COLUMNS = {
			{ "SRNO", Types.BIGINT },
			{ "FOLIO_NO", Types.VARCHAR },
			{ "NAME", Types.VARCHAR },
			{ "ADD1", Types.VARCHAR },
			{ "ADD2", Types.VARCHAR },
			{ "ADD3", Types.VARCHAR },
			{ "ADD4", Types.VARCHAR },
			{ "ADD5", Types.VARCHAR },
			{ "ADD6", Types.VARCHAR },
			{ "JT1", Types.VARCHAR },
			{ "JT2", Types.VARCHAR },
			{ "JT3", Types.VARCHAR },
			{ "SHARES", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("SRNO", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FOLIO_NO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ADD1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ADD2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ADD3", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ADD4", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ADD5", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ADD6", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("JT1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("JT2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("JT3", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("SHARES", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table UNPAID_DIVIDEND_SHARE (SRNO LONG not null primary key,FOLIO_NO VARCHAR(75) null,NAME VARCHAR(75) null,ADD1 VARCHAR(75) null,ADD2 VARCHAR(75) null,ADD3 VARCHAR(75) null,ADD4 VARCHAR(75) null,ADD5 VARCHAR(75) null,ADD6 VARCHAR(75) null,JT1 VARCHAR(75) null,JT2 VARCHAR(75) null,JT3 VARCHAR(75) null,SHARES VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table UNPAID_DIVIDEND_SHARE";
	public static final String ORDER_BY_JPQL = " ORDER BY unpaidUnclaimedDevidend.SRNO ASC";
	public static final String ORDER_BY_SQL = " ORDER BY UNPAID_DIVIDEND_SHARE.SRNO ASC";
	public static final String DATA_SOURCE = "extDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.rinfra.unpaidunclaimedshares.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rinfra.unpaidunclaimedshares.model.unpaidUnclaimedDevidend"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.rinfra.unpaidunclaimedshares.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rinfra.unpaidunclaimedshares.model.unpaidUnclaimedDevidend"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.rinfra.unpaidunclaimedshares.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rinfra.unpaidunclaimedshares.model.unpaidUnclaimedDevidend"),
			true);
	public static final long FOLIO_NO_COLUMN_BITMASK = 1L;
	public static final long SRNO_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static unpaidUnclaimedDevidend toModel(
		unpaidUnclaimedDevidendSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		unpaidUnclaimedDevidend model = new unpaidUnclaimedDevidendImpl();

		model.setSRNO(soapModel.getSRNO());
		model.setFOLIO_NO(soapModel.getFOLIO_NO());
		model.setNAME(soapModel.getNAME());
		model.setADD1(soapModel.getADD1());
		model.setADD2(soapModel.getADD2());
		model.setADD3(soapModel.getADD3());
		model.setADD4(soapModel.getADD4());
		model.setADD5(soapModel.getADD5());
		model.setADD6(soapModel.getADD6());
		model.setJT1(soapModel.getJT1());
		model.setJT2(soapModel.getJT2());
		model.setJT3(soapModel.getJT3());
		model.setSHARES(soapModel.getSHARES());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<unpaidUnclaimedDevidend> toModels(
		unpaidUnclaimedDevidendSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<unpaidUnclaimedDevidend> models = new ArrayList<unpaidUnclaimedDevidend>(soapModels.length);

		for (unpaidUnclaimedDevidendSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.rinfra.unpaidunclaimedshares.service.util.ServiceProps.get(
				"lock.expiration.time.com.rinfra.unpaidunclaimedshares.model.unpaidUnclaimedDevidend"));

	public unpaidUnclaimedDevidendModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _SRNO;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSRNO(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _SRNO;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return unpaidUnclaimedDevidend.class;
	}

	@Override
	public String getModelClassName() {
		return unpaidUnclaimedDevidend.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("SRNO", getSRNO());
		attributes.put("FOLIO_NO", getFOLIO_NO());
		attributes.put("NAME", getNAME());
		attributes.put("ADD1", getADD1());
		attributes.put("ADD2", getADD2());
		attributes.put("ADD3", getADD3());
		attributes.put("ADD4", getADD4());
		attributes.put("ADD5", getADD5());
		attributes.put("ADD6", getADD6());
		attributes.put("JT1", getJT1());
		attributes.put("JT2", getJT2());
		attributes.put("JT3", getJT3());
		attributes.put("SHARES", getSHARES());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long SRNO = (Long)attributes.get("SRNO");

		if (SRNO != null) {
			setSRNO(SRNO);
		}

		String FOLIO_NO = (String)attributes.get("FOLIO_NO");

		if (FOLIO_NO != null) {
			setFOLIO_NO(FOLIO_NO);
		}

		String NAME = (String)attributes.get("NAME");

		if (NAME != null) {
			setNAME(NAME);
		}

		String ADD1 = (String)attributes.get("ADD1");

		if (ADD1 != null) {
			setADD1(ADD1);
		}

		String ADD2 = (String)attributes.get("ADD2");

		if (ADD2 != null) {
			setADD2(ADD2);
		}

		String ADD3 = (String)attributes.get("ADD3");

		if (ADD3 != null) {
			setADD3(ADD3);
		}

		String ADD4 = (String)attributes.get("ADD4");

		if (ADD4 != null) {
			setADD4(ADD4);
		}

		String ADD5 = (String)attributes.get("ADD5");

		if (ADD5 != null) {
			setADD5(ADD5);
		}

		String ADD6 = (String)attributes.get("ADD6");

		if (ADD6 != null) {
			setADD6(ADD6);
		}

		String JT1 = (String)attributes.get("JT1");

		if (JT1 != null) {
			setJT1(JT1);
		}

		String JT2 = (String)attributes.get("JT2");

		if (JT2 != null) {
			setJT2(JT2);
		}

		String JT3 = (String)attributes.get("JT3");

		if (JT3 != null) {
			setJT3(JT3);
		}

		String SHARES = (String)attributes.get("SHARES");

		if (SHARES != null) {
			setSHARES(SHARES);
		}
	}

	@JSON
	@Override
	public long getSRNO() {
		return _SRNO;
	}

	@Override
	public void setSRNO(long SRNO) {
		_SRNO = SRNO;
	}

	@JSON
	@Override
	public String getFOLIO_NO() {
		if (_FOLIO_NO == null) {
			return StringPool.BLANK;
		}
		else {
			return _FOLIO_NO;
		}
	}

	@Override
	public void setFOLIO_NO(String FOLIO_NO) {
		_columnBitmask |= FOLIO_NO_COLUMN_BITMASK;

		if (_originalFOLIO_NO == null) {
			_originalFOLIO_NO = _FOLIO_NO;
		}

		_FOLIO_NO = FOLIO_NO;
	}

	public String getOriginalFOLIO_NO() {
		return GetterUtil.getString(_originalFOLIO_NO);
	}

	@JSON
	@Override
	public String getNAME() {
		if (_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _NAME;
		}
	}

	@Override
	public void setNAME(String NAME) {
		_NAME = NAME;
	}

	@JSON
	@Override
	public String getADD1() {
		if (_ADD1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _ADD1;
		}
	}

	@Override
	public void setADD1(String ADD1) {
		_ADD1 = ADD1;
	}

	@JSON
	@Override
	public String getADD2() {
		if (_ADD2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _ADD2;
		}
	}

	@Override
	public void setADD2(String ADD2) {
		_ADD2 = ADD2;
	}

	@JSON
	@Override
	public String getADD3() {
		if (_ADD3 == null) {
			return StringPool.BLANK;
		}
		else {
			return _ADD3;
		}
	}

	@Override
	public void setADD3(String ADD3) {
		_ADD3 = ADD3;
	}

	@JSON
	@Override
	public String getADD4() {
		if (_ADD4 == null) {
			return StringPool.BLANK;
		}
		else {
			return _ADD4;
		}
	}

	@Override
	public void setADD4(String ADD4) {
		_ADD4 = ADD4;
	}

	@JSON
	@Override
	public String getADD5() {
		if (_ADD5 == null) {
			return StringPool.BLANK;
		}
		else {
			return _ADD5;
		}
	}

	@Override
	public void setADD5(String ADD5) {
		_ADD5 = ADD5;
	}

	@JSON
	@Override
	public String getADD6() {
		if (_ADD6 == null) {
			return StringPool.BLANK;
		}
		else {
			return _ADD6;
		}
	}

	@Override
	public void setADD6(String ADD6) {
		_ADD6 = ADD6;
	}

	@JSON
	@Override
	public String getJT1() {
		if (_JT1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _JT1;
		}
	}

	@Override
	public void setJT1(String JT1) {
		_JT1 = JT1;
	}

	@JSON
	@Override
	public String getJT2() {
		if (_JT2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _JT2;
		}
	}

	@Override
	public void setJT2(String JT2) {
		_JT2 = JT2;
	}

	@JSON
	@Override
	public String getJT3() {
		if (_JT3 == null) {
			return StringPool.BLANK;
		}
		else {
			return _JT3;
		}
	}

	@Override
	public void setJT3(String JT3) {
		_JT3 = JT3;
	}

	@JSON
	@Override
	public String getSHARES() {
		if (_SHARES == null) {
			return StringPool.BLANK;
		}
		else {
			return _SHARES;
		}
	}

	@Override
	public void setSHARES(String SHARES) {
		_SHARES = SHARES;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			unpaidUnclaimedDevidend.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public unpaidUnclaimedDevidend toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (unpaidUnclaimedDevidend)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		unpaidUnclaimedDevidendImpl unpaidUnclaimedDevidendImpl = new unpaidUnclaimedDevidendImpl();

		unpaidUnclaimedDevidendImpl.setSRNO(getSRNO());
		unpaidUnclaimedDevidendImpl.setFOLIO_NO(getFOLIO_NO());
		unpaidUnclaimedDevidendImpl.setNAME(getNAME());
		unpaidUnclaimedDevidendImpl.setADD1(getADD1());
		unpaidUnclaimedDevidendImpl.setADD2(getADD2());
		unpaidUnclaimedDevidendImpl.setADD3(getADD3());
		unpaidUnclaimedDevidendImpl.setADD4(getADD4());
		unpaidUnclaimedDevidendImpl.setADD5(getADD5());
		unpaidUnclaimedDevidendImpl.setADD6(getADD6());
		unpaidUnclaimedDevidendImpl.setJT1(getJT1());
		unpaidUnclaimedDevidendImpl.setJT2(getJT2());
		unpaidUnclaimedDevidendImpl.setJT3(getJT3());
		unpaidUnclaimedDevidendImpl.setSHARES(getSHARES());

		unpaidUnclaimedDevidendImpl.resetOriginalValues();

		return unpaidUnclaimedDevidendImpl;
	}

	@Override
	public int compareTo(unpaidUnclaimedDevidend unpaidUnclaimedDevidend) {
		long primaryKey = unpaidUnclaimedDevidend.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof unpaidUnclaimedDevidend)) {
			return false;
		}

		unpaidUnclaimedDevidend unpaidUnclaimedDevidend = (unpaidUnclaimedDevidend)obj;

		long primaryKey = unpaidUnclaimedDevidend.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		unpaidUnclaimedDevidendModelImpl unpaidUnclaimedDevidendModelImpl = this;

		unpaidUnclaimedDevidendModelImpl._originalFOLIO_NO = unpaidUnclaimedDevidendModelImpl._FOLIO_NO;

		unpaidUnclaimedDevidendModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<unpaidUnclaimedDevidend> toCacheModel() {
		unpaidUnclaimedDevidendCacheModel unpaidUnclaimedDevidendCacheModel = new unpaidUnclaimedDevidendCacheModel();

		unpaidUnclaimedDevidendCacheModel.SRNO = getSRNO();

		unpaidUnclaimedDevidendCacheModel.FOLIO_NO = getFOLIO_NO();

		String FOLIO_NO = unpaidUnclaimedDevidendCacheModel.FOLIO_NO;

		if ((FOLIO_NO != null) && (FOLIO_NO.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.FOLIO_NO = null;
		}

		unpaidUnclaimedDevidendCacheModel.NAME = getNAME();

		String NAME = unpaidUnclaimedDevidendCacheModel.NAME;

		if ((NAME != null) && (NAME.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.NAME = null;
		}

		unpaidUnclaimedDevidendCacheModel.ADD1 = getADD1();

		String ADD1 = unpaidUnclaimedDevidendCacheModel.ADD1;

		if ((ADD1 != null) && (ADD1.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.ADD1 = null;
		}

		unpaidUnclaimedDevidendCacheModel.ADD2 = getADD2();

		String ADD2 = unpaidUnclaimedDevidendCacheModel.ADD2;

		if ((ADD2 != null) && (ADD2.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.ADD2 = null;
		}

		unpaidUnclaimedDevidendCacheModel.ADD3 = getADD3();

		String ADD3 = unpaidUnclaimedDevidendCacheModel.ADD3;

		if ((ADD3 != null) && (ADD3.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.ADD3 = null;
		}

		unpaidUnclaimedDevidendCacheModel.ADD4 = getADD4();

		String ADD4 = unpaidUnclaimedDevidendCacheModel.ADD4;

		if ((ADD4 != null) && (ADD4.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.ADD4 = null;
		}

		unpaidUnclaimedDevidendCacheModel.ADD5 = getADD5();

		String ADD5 = unpaidUnclaimedDevidendCacheModel.ADD5;

		if ((ADD5 != null) && (ADD5.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.ADD5 = null;
		}

		unpaidUnclaimedDevidendCacheModel.ADD6 = getADD6();

		String ADD6 = unpaidUnclaimedDevidendCacheModel.ADD6;

		if ((ADD6 != null) && (ADD6.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.ADD6 = null;
		}

		unpaidUnclaimedDevidendCacheModel.JT1 = getJT1();

		String JT1 = unpaidUnclaimedDevidendCacheModel.JT1;

		if ((JT1 != null) && (JT1.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.JT1 = null;
		}

		unpaidUnclaimedDevidendCacheModel.JT2 = getJT2();

		String JT2 = unpaidUnclaimedDevidendCacheModel.JT2;

		if ((JT2 != null) && (JT2.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.JT2 = null;
		}

		unpaidUnclaimedDevidendCacheModel.JT3 = getJT3();

		String JT3 = unpaidUnclaimedDevidendCacheModel.JT3;

		if ((JT3 != null) && (JT3.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.JT3 = null;
		}

		unpaidUnclaimedDevidendCacheModel.SHARES = getSHARES();

		String SHARES = unpaidUnclaimedDevidendCacheModel.SHARES;

		if ((SHARES != null) && (SHARES.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.SHARES = null;
		}

		return unpaidUnclaimedDevidendCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{SRNO=");
		sb.append(getSRNO());
		sb.append(", FOLIO_NO=");
		sb.append(getFOLIO_NO());
		sb.append(", NAME=");
		sb.append(getNAME());
		sb.append(", ADD1=");
		sb.append(getADD1());
		sb.append(", ADD2=");
		sb.append(getADD2());
		sb.append(", ADD3=");
		sb.append(getADD3());
		sb.append(", ADD4=");
		sb.append(getADD4());
		sb.append(", ADD5=");
		sb.append(getADD5());
		sb.append(", ADD6=");
		sb.append(getADD6());
		sb.append(", JT1=");
		sb.append(getJT1());
		sb.append(", JT2=");
		sb.append(getJT2());
		sb.append(", JT3=");
		sb.append(getJT3());
		sb.append(", SHARES=");
		sb.append(getSHARES());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append(
			"com.rinfra.unpaidunclaimedshares.model.unpaidUnclaimedDevidend");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>SRNO</column-name><column-value><![CDATA[");
		sb.append(getSRNO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FOLIO_NO</column-name><column-value><![CDATA[");
		sb.append(getFOLIO_NO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NAME</column-name><column-value><![CDATA[");
		sb.append(getNAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ADD1</column-name><column-value><![CDATA[");
		sb.append(getADD1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ADD2</column-name><column-value><![CDATA[");
		sb.append(getADD2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ADD3</column-name><column-value><![CDATA[");
		sb.append(getADD3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ADD4</column-name><column-value><![CDATA[");
		sb.append(getADD4());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ADD5</column-name><column-value><![CDATA[");
		sb.append(getADD5());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ADD6</column-name><column-value><![CDATA[");
		sb.append(getADD6());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>JT1</column-name><column-value><![CDATA[");
		sb.append(getJT1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>JT2</column-name><column-value><![CDATA[");
		sb.append(getJT2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>JT3</column-name><column-value><![CDATA[");
		sb.append(getJT3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SHARES</column-name><column-value><![CDATA[");
		sb.append(getSHARES());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = unpaidUnclaimedDevidend.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			unpaidUnclaimedDevidend.class
		};
	private long _SRNO;
	private String _FOLIO_NO;
	private String _originalFOLIO_NO;
	private String _NAME;
	private String _ADD1;
	private String _ADD2;
	private String _ADD3;
	private String _ADD4;
	private String _ADD5;
	private String _ADD6;
	private String _JT1;
	private String _JT2;
	private String _JT3;
	private String _SHARES;
	private long _columnBitmask;
	private unpaidUnclaimedDevidend _escapedModel;
}