/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rinfra.annual.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.rinfra.annual.model.AnnualReport;
import com.rinfra.annual.model.AnnualReportModel;
import com.rinfra.annual.model.AnnualReportSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the AnnualReport service. Represents a row in the &quot;FINANCIAL_REPORT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AnnualReportModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AnnualReportImpl}.
 * </p>
 *
 * @author MukeshPatidar
 * @see AnnualReportImpl
 * @see AnnualReport
 * @see AnnualReportModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class AnnualReportModelImpl extends BaseModelImpl<AnnualReport>
	implements AnnualReportModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a annual report model instance should use the {@link AnnualReport} interface instead.
	 */
	public static final String TABLE_NAME = "FINANCIAL_REPORT";
	public static final Object[][] TABLE_COLUMNS = {
			{ "SRNO", Types.BIGINT },
			{ "FINANCIAL_YEARS", Types.VARCHAR },
			{ "FINANCIALDATA", Types.VARCHAR },
			{ "FINANCIAL_DATALINK", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("SRNO", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FINANCIAL_YEARS", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FINANCIALDATA", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FINANCIAL_DATALINK", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table FINANCIAL_REPORT (SRNO LONG not null primary key,FINANCIAL_YEARS VARCHAR(75) null,FINANCIALDATA VARCHAR(75) null,FINANCIAL_DATALINK VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table FINANCIAL_REPORT";
	public static final String ORDER_BY_JPQL = " ORDER BY annualReport.SRNO ASC";
	public static final String ORDER_BY_SQL = " ORDER BY FINANCIAL_REPORT.SRNO ASC";
	public static final String DATA_SOURCE = "extDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.rinfra.annual.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rinfra.annual.model.AnnualReport"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.rinfra.annual.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rinfra.annual.model.AnnualReport"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.rinfra.annual.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rinfra.annual.model.AnnualReport"),
			true);
	public static final long FINANCIAL_YEARS_COLUMN_BITMASK = 1L;
	public static final long SRNO_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AnnualReport toModel(AnnualReportSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AnnualReport model = new AnnualReportImpl();

		model.setSRNO(soapModel.getSRNO());
		model.setFINANCIAL_YEARS(soapModel.getFINANCIAL_YEARS());
		model.setFINANCIALDATA(soapModel.getFINANCIALDATA());
		model.setFINANCIAL_DATALINK(soapModel.getFINANCIAL_DATALINK());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AnnualReport> toModels(AnnualReportSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AnnualReport> models = new ArrayList<AnnualReport>(soapModels.length);

		for (AnnualReportSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.rinfra.annual.service.util.ServiceProps.get(
				"lock.expiration.time.com.rinfra.annual.model.AnnualReport"));

	public AnnualReportModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _SRNO;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSRNO(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _SRNO;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AnnualReport.class;
	}

	@Override
	public String getModelClassName() {
		return AnnualReport.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("SRNO", getSRNO());
		attributes.put("FINANCIAL_YEARS", getFINANCIAL_YEARS());
		attributes.put("FINANCIALDATA", getFINANCIALDATA());
		attributes.put("FINANCIAL_DATALINK", getFINANCIAL_DATALINK());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long SRNO = (Long)attributes.get("SRNO");

		if (SRNO != null) {
			setSRNO(SRNO);
		}

		String FINANCIAL_YEARS = (String)attributes.get("FINANCIAL_YEARS");

		if (FINANCIAL_YEARS != null) {
			setFINANCIAL_YEARS(FINANCIAL_YEARS);
		}

		String FINANCIALDATA = (String)attributes.get("FINANCIALDATA");

		if (FINANCIALDATA != null) {
			setFINANCIALDATA(FINANCIALDATA);
		}

		String FINANCIAL_DATALINK = (String)attributes.get("FINANCIAL_DATALINK");

		if (FINANCIAL_DATALINK != null) {
			setFINANCIAL_DATALINK(FINANCIAL_DATALINK);
		}
	}

	@JSON
	@Override
	public long getSRNO() {
		return _SRNO;
	}

	@Override
	public void setSRNO(long SRNO) {
		_SRNO = SRNO;
	}

	@JSON
	@Override
	public String getFINANCIAL_YEARS() {
		if (_FINANCIAL_YEARS == null) {
			return StringPool.BLANK;
		}
		else {
			return _FINANCIAL_YEARS;
		}
	}

	@Override
	public void setFINANCIAL_YEARS(String FINANCIAL_YEARS) {
		_columnBitmask |= FINANCIAL_YEARS_COLUMN_BITMASK;

		if (_originalFINANCIAL_YEARS == null) {
			_originalFINANCIAL_YEARS = _FINANCIAL_YEARS;
		}

		_FINANCIAL_YEARS = FINANCIAL_YEARS;
	}

	public String getOriginalFINANCIAL_YEARS() {
		return GetterUtil.getString(_originalFINANCIAL_YEARS);
	}

	@JSON
	@Override
	public String getFINANCIALDATA() {
		if (_FINANCIALDATA == null) {
			return StringPool.BLANK;
		}
		else {
			return _FINANCIALDATA;
		}
	}

	@Override
	public void setFINANCIALDATA(String FINANCIALDATA) {
		_FINANCIALDATA = FINANCIALDATA;
	}

	@JSON
	@Override
	public String getFINANCIAL_DATALINK() {
		if (_FINANCIAL_DATALINK == null) {
			return StringPool.BLANK;
		}
		else {
			return _FINANCIAL_DATALINK;
		}
	}

	@Override
	public void setFINANCIAL_DATALINK(String FINANCIAL_DATALINK) {
		_FINANCIAL_DATALINK = FINANCIAL_DATALINK;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			AnnualReport.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AnnualReport toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AnnualReport)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AnnualReportImpl annualReportImpl = new AnnualReportImpl();

		annualReportImpl.setSRNO(getSRNO());
		annualReportImpl.setFINANCIAL_YEARS(getFINANCIAL_YEARS());
		annualReportImpl.setFINANCIALDATA(getFINANCIALDATA());
		annualReportImpl.setFINANCIAL_DATALINK(getFINANCIAL_DATALINK());

		annualReportImpl.resetOriginalValues();

		return annualReportImpl;
	}

	@Override
	public int compareTo(AnnualReport annualReport) {
		long primaryKey = annualReport.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AnnualReport)) {
			return false;
		}

		AnnualReport annualReport = (AnnualReport)obj;

		long primaryKey = annualReport.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		AnnualReportModelImpl annualReportModelImpl = this;

		annualReportModelImpl._originalFINANCIAL_YEARS = annualReportModelImpl._FINANCIAL_YEARS;

		annualReportModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AnnualReport> toCacheModel() {
		AnnualReportCacheModel annualReportCacheModel = new AnnualReportCacheModel();

		annualReportCacheModel.SRNO = getSRNO();

		annualReportCacheModel.FINANCIAL_YEARS = getFINANCIAL_YEARS();

		String FINANCIAL_YEARS = annualReportCacheModel.FINANCIAL_YEARS;

		if ((FINANCIAL_YEARS != null) && (FINANCIAL_YEARS.length() == 0)) {
			annualReportCacheModel.FINANCIAL_YEARS = null;
		}

		annualReportCacheModel.FINANCIALDATA = getFINANCIALDATA();

		String FINANCIALDATA = annualReportCacheModel.FINANCIALDATA;

		if ((FINANCIALDATA != null) && (FINANCIALDATA.length() == 0)) {
			annualReportCacheModel.FINANCIALDATA = null;
		}

		annualReportCacheModel.FINANCIAL_DATALINK = getFINANCIAL_DATALINK();

		String FINANCIAL_DATALINK = annualReportCacheModel.FINANCIAL_DATALINK;

		if ((FINANCIAL_DATALINK != null) && (FINANCIAL_DATALINK.length() == 0)) {
			annualReportCacheModel.FINANCIAL_DATALINK = null;
		}

		return annualReportCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{SRNO=");
		sb.append(getSRNO());
		sb.append(", FINANCIAL_YEARS=");
		sb.append(getFINANCIAL_YEARS());
		sb.append(", FINANCIALDATA=");
		sb.append(getFINANCIALDATA());
		sb.append(", FINANCIAL_DATALINK=");
		sb.append(getFINANCIAL_DATALINK());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.rinfra.annual.model.AnnualReport");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>SRNO</column-name><column-value><![CDATA[");
		sb.append(getSRNO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FINANCIAL_YEARS</column-name><column-value><![CDATA[");
		sb.append(getFINANCIAL_YEARS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FINANCIALDATA</column-name><column-value><![CDATA[");
		sb.append(getFINANCIALDATA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FINANCIAL_DATALINK</column-name><column-value><![CDATA[");
		sb.append(getFINANCIAL_DATALINK());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AnnualReport.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AnnualReport.class
		};
	private long _SRNO;
	private String _FINANCIAL_YEARS;
	private String _originalFINANCIAL_YEARS;
	private String _FINANCIALDATA;
	private String _FINANCIAL_DATALINK;
	private long _columnBitmask;
	private AnnualReport _escapedModel;
}