/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package attendence.rinfra.services.model.impl;

import aQute.bnd.annotation.ProviderType;

import attendence.rinfra.services.model.EmpMaster;
import attendence.rinfra.services.model.EmpMasterModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the EmpMaster service. Represents a row in the &quot;MASTER_TABLE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link EmpMasterModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmpMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmpMasterImpl
 * @see EmpMaster
 * @see EmpMasterModel
 * @generated
 */
@ProviderType
public class EmpMasterModelImpl extends BaseModelImpl<EmpMaster>
	implements EmpMasterModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a emp master model instance should use the {@link EmpMaster} interface instead.
	 */
	public static final String TABLE_NAME = "MASTER_TABLE";
	public static final Object[][] TABLE_COLUMNS = {
			{ "EMPLOYEE_CODE", Types.VARCHAR },
			{ "EMPLOYEE_NAME", Types.VARCHAR },
			{ "MOBILE_NUMBER", Types.VARCHAR },
			{ "USER_DEFINED_1", Types.VARCHAR },
			{ "USER_DEFINED_2", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("EMPLOYEE_CODE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("EMPLOYEE_NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MOBILE_NUMBER", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("USER_DEFINED_1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("USER_DEFINED_2", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table MASTER_TABLE (EMPLOYEE_CODE VARCHAR(75) not null primary key,EMPLOYEE_NAME VARCHAR(75) null,MOBILE_NUMBER VARCHAR(75) null,USER_DEFINED_1 VARCHAR(75) null,USER_DEFINED_2 VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table MASTER_TABLE";
	public static final String ORDER_BY_JPQL = " ORDER BY empMaster.employeeCode ASC";
	public static final String ORDER_BY_SQL = " ORDER BY MASTER_TABLE.EMPLOYEE_CODE ASC";
	public static final String DATA_SOURCE = "rinfrauser";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(attendence.rinfra.services.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.attendence.rinfra.services.model.EmpMaster"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(attendence.rinfra.services.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.attendence.rinfra.services.model.EmpMaster"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(attendence.rinfra.services.service.util.ServiceProps.get(
				"lock.expiration.time.attendence.rinfra.services.model.EmpMaster"));

	public EmpMasterModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _employeeCode;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setEmployeeCode(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _employeeCode;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return EmpMaster.class;
	}

	@Override
	public String getModelClassName() {
		return EmpMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("employeeCode", getEmployeeCode());
		attributes.put("employeeName", getEmployeeName());
		attributes.put("mobile", getMobile());
		attributes.put("userDefined1", getUserDefined1());
		attributes.put("userDefined2", getUserDefined2());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String employeeCode = (String)attributes.get("employeeCode");

		if (employeeCode != null) {
			setEmployeeCode(employeeCode);
		}

		String employeeName = (String)attributes.get("employeeName");

		if (employeeName != null) {
			setEmployeeName(employeeName);
		}

		String mobile = (String)attributes.get("mobile");

		if (mobile != null) {
			setMobile(mobile);
		}

		String userDefined1 = (String)attributes.get("userDefined1");

		if (userDefined1 != null) {
			setUserDefined1(userDefined1);
		}

		String userDefined2 = (String)attributes.get("userDefined2");

		if (userDefined2 != null) {
			setUserDefined2(userDefined2);
		}
	}

	@Override
	public String getEmployeeCode() {
		if (_employeeCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _employeeCode;
		}
	}

	@Override
	public void setEmployeeCode(String employeeCode) {
		_employeeCode = employeeCode;
	}

	@Override
	public String getEmployeeName() {
		if (_employeeName == null) {
			return StringPool.BLANK;
		}
		else {
			return _employeeName;
		}
	}

	@Override
	public void setEmployeeName(String employeeName) {
		_employeeName = employeeName;
	}

	@Override
	public String getMobile() {
		if (_mobile == null) {
			return StringPool.BLANK;
		}
		else {
			return _mobile;
		}
	}

	@Override
	public void setMobile(String mobile) {
		_mobile = mobile;
	}

	@Override
	public String getUserDefined1() {
		if (_userDefined1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _userDefined1;
		}
	}

	@Override
	public void setUserDefined1(String userDefined1) {
		_userDefined1 = userDefined1;
	}

	@Override
	public String getUserDefined2() {
		if (_userDefined2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _userDefined2;
		}
	}

	@Override
	public void setUserDefined2(String userDefined2) {
		_userDefined2 = userDefined2;
	}

	@Override
	public EmpMaster toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EmpMaster)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmpMasterImpl empMasterImpl = new EmpMasterImpl();

		empMasterImpl.setEmployeeCode(getEmployeeCode());
		empMasterImpl.setEmployeeName(getEmployeeName());
		empMasterImpl.setMobile(getMobile());
		empMasterImpl.setUserDefined1(getUserDefined1());
		empMasterImpl.setUserDefined2(getUserDefined2());

		empMasterImpl.resetOriginalValues();

		return empMasterImpl;
	}

	@Override
	public int compareTo(EmpMaster empMaster) {
		String primaryKey = empMaster.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EmpMaster)) {
			return false;
		}

		EmpMaster empMaster = (EmpMaster)obj;

		String primaryKey = empMaster.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<EmpMaster> toCacheModel() {
		EmpMasterCacheModel empMasterCacheModel = new EmpMasterCacheModel();

		empMasterCacheModel.employeeCode = getEmployeeCode();

		String employeeCode = empMasterCacheModel.employeeCode;

		if ((employeeCode != null) && (employeeCode.length() == 0)) {
			empMasterCacheModel.employeeCode = null;
		}

		empMasterCacheModel.employeeName = getEmployeeName();

		String employeeName = empMasterCacheModel.employeeName;

		if ((employeeName != null) && (employeeName.length() == 0)) {
			empMasterCacheModel.employeeName = null;
		}

		empMasterCacheModel.mobile = getMobile();

		String mobile = empMasterCacheModel.mobile;

		if ((mobile != null) && (mobile.length() == 0)) {
			empMasterCacheModel.mobile = null;
		}

		empMasterCacheModel.userDefined1 = getUserDefined1();

		String userDefined1 = empMasterCacheModel.userDefined1;

		if ((userDefined1 != null) && (userDefined1.length() == 0)) {
			empMasterCacheModel.userDefined1 = null;
		}

		empMasterCacheModel.userDefined2 = getUserDefined2();

		String userDefined2 = empMasterCacheModel.userDefined2;

		if ((userDefined2 != null) && (userDefined2.length() == 0)) {
			empMasterCacheModel.userDefined2 = null;
		}

		return empMasterCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{employeeCode=");
		sb.append(getEmployeeCode());
		sb.append(", employeeName=");
		sb.append(getEmployeeName());
		sb.append(", mobile=");
		sb.append(getMobile());
		sb.append(", userDefined1=");
		sb.append(getUserDefined1());
		sb.append(", userDefined2=");
		sb.append(getUserDefined2());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("attendence.rinfra.services.model.EmpMaster");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>employeeCode</column-name><column-value><![CDATA[");
		sb.append(getEmployeeCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>employeeName</column-name><column-value><![CDATA[");
		sb.append(getEmployeeName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mobile</column-name><column-value><![CDATA[");
		sb.append(getMobile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userDefined1</column-name><column-value><![CDATA[");
		sb.append(getUserDefined1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userDefined2</column-name><column-value><![CDATA[");
		sb.append(getUserDefined2());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = EmpMaster.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			EmpMaster.class
		};
	private String _employeeCode;
	private String _employeeName;
	private String _mobile;
	private String _userDefined1;
	private String _userDefined2;
	private EmpMaster _escapedModel;
}