/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package attendence.rinfra.services.model.impl;

import aQute.bnd.annotation.ProviderType;

import attendence.rinfra.services.model.EmpOtpMaster;
import attendence.rinfra.services.model.EmpOtpMasterModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the EmpOtpMaster service. Represents a row in the &quot;EMP_OTP_MASTER&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link EmpOtpMasterModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmpOtpMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmpOtpMasterImpl
 * @see EmpOtpMaster
 * @see EmpOtpMasterModel
 * @generated
 */
@ProviderType
public class EmpOtpMasterModelImpl extends BaseModelImpl<EmpOtpMaster>
	implements EmpOtpMasterModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a emp otp master model instance should use the {@link EmpOtpMaster} interface instead.
	 */
	public static final String TABLE_NAME = "EMP_OTP_MASTER";
	public static final Object[][] TABLE_COLUMNS = {
			{ "EMP_MOBILE", Types.VARCHAR },
			{ "OTP", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("EMP_MOBILE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("OTP", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table EMP_OTP_MASTER (EMP_MOBILE VARCHAR(75) not null primary key,OTP VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table EMP_OTP_MASTER";
	public static final String ORDER_BY_JPQL = " ORDER BY empOtpMaster.empMobile ASC";
	public static final String ORDER_BY_SQL = " ORDER BY EMP_OTP_MASTER.EMP_MOBILE ASC";
	public static final String DATA_SOURCE = "rinfrauser";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(attendence.rinfra.services.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.attendence.rinfra.services.model.EmpOtpMaster"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(attendence.rinfra.services.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.attendence.rinfra.services.model.EmpOtpMaster"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(attendence.rinfra.services.service.util.ServiceProps.get(
				"lock.expiration.time.attendence.rinfra.services.model.EmpOtpMaster"));

	public EmpOtpMasterModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _empMobile;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setEmpMobile(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _empMobile;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return EmpOtpMaster.class;
	}

	@Override
	public String getModelClassName() {
		return EmpOtpMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("empMobile", getEmpMobile());
		attributes.put("otp", getOtp());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String empMobile = (String)attributes.get("empMobile");

		if (empMobile != null) {
			setEmpMobile(empMobile);
		}

		String otp = (String)attributes.get("otp");

		if (otp != null) {
			setOtp(otp);
		}
	}

	@Override
	public String getEmpMobile() {
		if (_empMobile == null) {
			return StringPool.BLANK;
		}
		else {
			return _empMobile;
		}
	}

	@Override
	public void setEmpMobile(String empMobile) {
		_empMobile = empMobile;
	}

	@Override
	public String getOtp() {
		if (_otp == null) {
			return StringPool.BLANK;
		}
		else {
			return _otp;
		}
	}

	@Override
	public void setOtp(String otp) {
		_otp = otp;
	}

	@Override
	public EmpOtpMaster toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EmpOtpMaster)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmpOtpMasterImpl empOtpMasterImpl = new EmpOtpMasterImpl();

		empOtpMasterImpl.setEmpMobile(getEmpMobile());
		empOtpMasterImpl.setOtp(getOtp());

		empOtpMasterImpl.resetOriginalValues();

		return empOtpMasterImpl;
	}

	@Override
	public int compareTo(EmpOtpMaster empOtpMaster) {
		String primaryKey = empOtpMaster.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EmpOtpMaster)) {
			return false;
		}

		EmpOtpMaster empOtpMaster = (EmpOtpMaster)obj;

		String primaryKey = empOtpMaster.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<EmpOtpMaster> toCacheModel() {
		EmpOtpMasterCacheModel empOtpMasterCacheModel = new EmpOtpMasterCacheModel();

		empOtpMasterCacheModel.empMobile = getEmpMobile();

		String empMobile = empOtpMasterCacheModel.empMobile;

		if ((empMobile != null) && (empMobile.length() == 0)) {
			empOtpMasterCacheModel.empMobile = null;
		}

		empOtpMasterCacheModel.otp = getOtp();

		String otp = empOtpMasterCacheModel.otp;

		if ((otp != null) && (otp.length() == 0)) {
			empOtpMasterCacheModel.otp = null;
		}

		return empOtpMasterCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{empMobile=");
		sb.append(getEmpMobile());
		sb.append(", otp=");
		sb.append(getOtp());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("attendence.rinfra.services.model.EmpOtpMaster");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>empMobile</column-name><column-value><![CDATA[");
		sb.append(getEmpMobile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>otp</column-name><column-value><![CDATA[");
		sb.append(getOtp());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = EmpOtpMaster.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			EmpOtpMaster.class
		};
	private String _empMobile;
	private String _otp;
	private EmpOtpMaster _escapedModel;
}