/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.metro.mediarelease.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MetroMediaRelease service. Represents a row in the &quot;mumbai_metro_media_release&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.metro.mediarelease.model.impl.MetroMediaReleaseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.metro.mediarelease.model.impl.MetroMediaReleaseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MetroMediaRelease
 * @see com.metro.mediarelease.model.impl.MetroMediaReleaseImpl
 * @see com.metro.mediarelease.model.impl.MetroMediaReleaseModelImpl
 * @generated
 */
@ProviderType
public interface MetroMediaReleaseModel extends BaseModel<MetroMediaRelease> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a metro media release model instance should use the {@link MetroMediaRelease} interface instead.
	 */

	/**
	 * Returns the primary key of this metro media release.
	 *
	 * @return the primary key of this metro media release
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this metro media release.
	 *
	 * @param primaryKey the primary key of this metro media release
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the srno of this metro media release.
	 *
	 * @return the srno of this metro media release
	 */
	public long getSRNO();

	/**
	 * Sets the srno of this metro media release.
	 *
	 * @param SRNO the srno of this metro media release
	 */
	public void setSRNO(long SRNO);

	/**
	 * Returns the hdate of this metro media release.
	 *
	 * @return the hdate of this metro media release
	 */
	public Date getHDATE();

	/**
	 * Sets the hdate of this metro media release.
	 *
	 * @param HDATE the hdate of this metro media release
	 */
	public void setHDATE(Date HDATE);

	/**
	 * Returns the headline of this metro media release.
	 *
	 * @return the headline of this metro media release
	 */
	@AutoEscape
	public String getHEADLINE();

	/**
	 * Sets the headline of this metro media release.
	 *
	 * @param HEADLINE the headline of this metro media release
	 */
	public void setHEADLINE(String HEADLINE);

	/**
	 * Returns the document_name of this metro media release.
	 *
	 * @return the document_name of this metro media release
	 */
	@AutoEscape
	public String getDOCUMENT_NAME();

	/**
	 * Sets the document_name of this metro media release.
	 *
	 * @param DOCUMENT_NAME the document_name of this metro media release
	 */
	public void setDOCUMENT_NAME(String DOCUMENT_NAME);

	/**
	 * Returns the createdate of this metro media release.
	 *
	 * @return the createdate of this metro media release
	 */
	public Date getCREATEDATE();

	/**
	 * Sets the createdate of this metro media release.
	 *
	 * @param CREATEDATE the createdate of this metro media release
	 */
	public void setCREATEDATE(Date CREATEDATE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MetroMediaRelease metroMediaRelease);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MetroMediaRelease> toCacheModel();

	@Override
	public MetroMediaRelease toEscapedModel();

	@Override
	public MetroMediaRelease toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}