/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.reliance.reality.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import com.reliance.reality.model.RealityPropertyMaster;
import com.reliance.reality.service.RealityPropertyMasterService;
import com.reliance.reality.service.persistence.RealityPropertyMasterFinder;
import com.reliance.reality.service.persistence.RealityPropertyMasterPersistence;
import com.reliance.reality.service.persistence.RelianceRealityFinder;
import com.reliance.reality.service.persistence.RelianceRealityPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the reality property master remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.reliance.reality.service.impl.RealityPropertyMasterServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.reliance.reality.service.impl.RealityPropertyMasterServiceImpl
 * @see com.reliance.reality.service.RealityPropertyMasterServiceUtil
 * @generated
 */
public abstract class RealityPropertyMasterServiceBaseImpl
	extends BaseServiceImpl implements RealityPropertyMasterService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.reliance.reality.service.RealityPropertyMasterServiceUtil} to access the reality property master remote service.
	 */

	/**
	 * Returns the reality property master local service.
	 *
	 * @return the reality property master local service
	 */
	public com.reliance.reality.service.RealityPropertyMasterLocalService getRealityPropertyMasterLocalService() {
		return realityPropertyMasterLocalService;
	}

	/**
	 * Sets the reality property master local service.
	 *
	 * @param realityPropertyMasterLocalService the reality property master local service
	 */
	public void setRealityPropertyMasterLocalService(
		com.reliance.reality.service.RealityPropertyMasterLocalService realityPropertyMasterLocalService) {
		this.realityPropertyMasterLocalService = realityPropertyMasterLocalService;
	}

	/**
	 * Returns the reality property master remote service.
	 *
	 * @return the reality property master remote service
	 */
	public RealityPropertyMasterService getRealityPropertyMasterService() {
		return realityPropertyMasterService;
	}

	/**
	 * Sets the reality property master remote service.
	 *
	 * @param realityPropertyMasterService the reality property master remote service
	 */
	public void setRealityPropertyMasterService(
		RealityPropertyMasterService realityPropertyMasterService) {
		this.realityPropertyMasterService = realityPropertyMasterService;
	}

	/**
	 * Returns the reality property master persistence.
	 *
	 * @return the reality property master persistence
	 */
	public RealityPropertyMasterPersistence getRealityPropertyMasterPersistence() {
		return realityPropertyMasterPersistence;
	}

	/**
	 * Sets the reality property master persistence.
	 *
	 * @param realityPropertyMasterPersistence the reality property master persistence
	 */
	public void setRealityPropertyMasterPersistence(
		RealityPropertyMasterPersistence realityPropertyMasterPersistence) {
		this.realityPropertyMasterPersistence = realityPropertyMasterPersistence;
	}

	/**
	 * Returns the reality property master finder.
	 *
	 * @return the reality property master finder
	 */
	public RealityPropertyMasterFinder getRealityPropertyMasterFinder() {
		return realityPropertyMasterFinder;
	}

	/**
	 * Sets the reality property master finder.
	 *
	 * @param realityPropertyMasterFinder the reality property master finder
	 */
	public void setRealityPropertyMasterFinder(
		RealityPropertyMasterFinder realityPropertyMasterFinder) {
		this.realityPropertyMasterFinder = realityPropertyMasterFinder;
	}

	/**
	 * Returns the reliance reality local service.
	 *
	 * @return the reliance reality local service
	 */
	public com.reliance.reality.service.RelianceRealityLocalService getRelianceRealityLocalService() {
		return relianceRealityLocalService;
	}

	/**
	 * Sets the reliance reality local service.
	 *
	 * @param relianceRealityLocalService the reliance reality local service
	 */
	public void setRelianceRealityLocalService(
		com.reliance.reality.service.RelianceRealityLocalService relianceRealityLocalService) {
		this.relianceRealityLocalService = relianceRealityLocalService;
	}

	/**
	 * Returns the reliance reality remote service.
	 *
	 * @return the reliance reality remote service
	 */
	public com.reliance.reality.service.RelianceRealityService getRelianceRealityService() {
		return relianceRealityService;
	}

	/**
	 * Sets the reliance reality remote service.
	 *
	 * @param relianceRealityService the reliance reality remote service
	 */
	public void setRelianceRealityService(
		com.reliance.reality.service.RelianceRealityService relianceRealityService) {
		this.relianceRealityService = relianceRealityService;
	}

	/**
	 * Returns the reliance reality persistence.
	 *
	 * @return the reliance reality persistence
	 */
	public RelianceRealityPersistence getRelianceRealityPersistence() {
		return relianceRealityPersistence;
	}

	/**
	 * Sets the reliance reality persistence.
	 *
	 * @param relianceRealityPersistence the reliance reality persistence
	 */
	public void setRelianceRealityPersistence(
		RelianceRealityPersistence relianceRealityPersistence) {
		this.relianceRealityPersistence = relianceRealityPersistence;
	}

	/**
	 * Returns the reliance reality finder.
	 *
	 * @return the reliance reality finder
	 */
	public RelianceRealityFinder getRelianceRealityFinder() {
		return relianceRealityFinder;
	}

	/**
	 * Sets the reliance reality finder.
	 *
	 * @param relianceRealityFinder the reliance reality finder
	 */
	public void setRelianceRealityFinder(
		RelianceRealityFinder relianceRealityFinder) {
		this.relianceRealityFinder = relianceRealityFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return RealityPropertyMasterService.class.getName();
	}

	protected Class<?> getModelClass() {
		return RealityPropertyMaster.class;
	}

	protected String getModelClassName() {
		return RealityPropertyMaster.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = realityPropertyMasterPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.reliance.reality.service.RealityPropertyMasterLocalService.class)
	protected com.reliance.reality.service.RealityPropertyMasterLocalService realityPropertyMasterLocalService;
	@BeanReference(type = RealityPropertyMasterService.class)
	protected RealityPropertyMasterService realityPropertyMasterService;
	@BeanReference(type = RealityPropertyMasterPersistence.class)
	protected RealityPropertyMasterPersistence realityPropertyMasterPersistence;
	@BeanReference(type = RealityPropertyMasterFinder.class)
	protected RealityPropertyMasterFinder realityPropertyMasterFinder;
	@BeanReference(type = com.reliance.reality.service.RelianceRealityLocalService.class)
	protected com.reliance.reality.service.RelianceRealityLocalService relianceRealityLocalService;
	@BeanReference(type = com.reliance.reality.service.RelianceRealityService.class)
	protected com.reliance.reality.service.RelianceRealityService relianceRealityService;
	@BeanReference(type = RelianceRealityPersistence.class)
	protected RelianceRealityPersistence relianceRealityPersistence;
	@BeanReference(type = RelianceRealityFinder.class)
	protected RelianceRealityFinder relianceRealityFinder;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}