/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.reliance.reality.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import com.reliance.reality.model.RealityPropertyMaster;
import com.reliance.reality.service.RealityPropertyMasterLocalService;
import com.reliance.reality.service.persistence.RealityPropertyMasterFinder;
import com.reliance.reality.service.persistence.RealityPropertyMasterPersistence;
import com.reliance.reality.service.persistence.RelianceRealityFinder;
import com.reliance.reality.service.persistence.RelianceRealityPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the reality property master local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.reliance.reality.service.impl.RealityPropertyMasterLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.reliance.reality.service.impl.RealityPropertyMasterLocalServiceImpl
 * @see com.reliance.reality.service.RealityPropertyMasterLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class RealityPropertyMasterLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements RealityPropertyMasterLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.reliance.reality.service.RealityPropertyMasterLocalServiceUtil} to access the reality property master local service.
	 */

	/**
	 * Adds the reality property master to the database. Also notifies the appropriate model listeners.
	 *
	 * @param realityPropertyMaster the reality property master
	 * @return the reality property master that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RealityPropertyMaster addRealityPropertyMaster(
		RealityPropertyMaster realityPropertyMaster) {
		realityPropertyMaster.setNew(true);

		return realityPropertyMasterPersistence.update(realityPropertyMaster);
	}

	/**
	 * Creates a new reality property master with the primary key. Does not add the reality property master to the database.
	 *
	 * @param property_ID the primary key for the new reality property master
	 * @return the new reality property master
	 */
	@Override
	public RealityPropertyMaster createRealityPropertyMaster(long property_ID) {
		return realityPropertyMasterPersistence.create(property_ID);
	}

	/**
	 * Deletes the reality property master with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param property_ID the primary key of the reality property master
	 * @return the reality property master that was removed
	 * @throws PortalException if a reality property master with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RealityPropertyMaster deleteRealityPropertyMaster(long property_ID)
		throws PortalException {
		return realityPropertyMasterPersistence.remove(property_ID);
	}

	/**
	 * Deletes the reality property master from the database. Also notifies the appropriate model listeners.
	 *
	 * @param realityPropertyMaster the reality property master
	 * @return the reality property master that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RealityPropertyMaster deleteRealityPropertyMaster(
		RealityPropertyMaster realityPropertyMaster) {
		return realityPropertyMasterPersistence.remove(realityPropertyMaster);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(RealityPropertyMaster.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return realityPropertyMasterPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.reliance.reality.model.impl.RealityPropertyMasterModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return realityPropertyMasterPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.reliance.reality.model.impl.RealityPropertyMasterModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return realityPropertyMasterPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return realityPropertyMasterPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return realityPropertyMasterPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public RealityPropertyMaster fetchRealityPropertyMaster(long property_ID) {
		return realityPropertyMasterPersistence.fetchByPrimaryKey(property_ID);
	}

	/**
	 * Returns the reality property master with the primary key.
	 *
	 * @param property_ID the primary key of the reality property master
	 * @return the reality property master
	 * @throws PortalException if a reality property master with the primary key could not be found
	 */
	@Override
	public RealityPropertyMaster getRealityPropertyMaster(long property_ID)
		throws PortalException {
		return realityPropertyMasterPersistence.findByPrimaryKey(property_ID);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(realityPropertyMasterLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RealityPropertyMaster.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("property_ID");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(realityPropertyMasterLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(RealityPropertyMaster.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("property_ID");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(realityPropertyMasterLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RealityPropertyMaster.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("property_ID");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return realityPropertyMasterLocalService.deleteRealityPropertyMaster((RealityPropertyMaster)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return realityPropertyMasterPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the reality property masters.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.reliance.reality.model.impl.RealityPropertyMasterModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of reality property masters
	 * @param end the upper bound of the range of reality property masters (not inclusive)
	 * @return the range of reality property masters
	 */
	@Override
	public List<RealityPropertyMaster> getRealityPropertyMasters(int start,
		int end) {
		return realityPropertyMasterPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of reality property masters.
	 *
	 * @return the number of reality property masters
	 */
	@Override
	public int getRealityPropertyMastersCount() {
		return realityPropertyMasterPersistence.countAll();
	}

	/**
	 * Updates the reality property master in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param realityPropertyMaster the reality property master
	 * @return the reality property master that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RealityPropertyMaster updateRealityPropertyMaster(
		RealityPropertyMaster realityPropertyMaster) {
		return realityPropertyMasterPersistence.update(realityPropertyMaster);
	}

	/**
	 * Returns the reality property master local service.
	 *
	 * @return the reality property master local service
	 */
	public RealityPropertyMasterLocalService getRealityPropertyMasterLocalService() {
		return realityPropertyMasterLocalService;
	}

	/**
	 * Sets the reality property master local service.
	 *
	 * @param realityPropertyMasterLocalService the reality property master local service
	 */
	public void setRealityPropertyMasterLocalService(
		RealityPropertyMasterLocalService realityPropertyMasterLocalService) {
		this.realityPropertyMasterLocalService = realityPropertyMasterLocalService;
	}

	/**
	 * Returns the reality property master persistence.
	 *
	 * @return the reality property master persistence
	 */
	public RealityPropertyMasterPersistence getRealityPropertyMasterPersistence() {
		return realityPropertyMasterPersistence;
	}

	/**
	 * Sets the reality property master persistence.
	 *
	 * @param realityPropertyMasterPersistence the reality property master persistence
	 */
	public void setRealityPropertyMasterPersistence(
		RealityPropertyMasterPersistence realityPropertyMasterPersistence) {
		this.realityPropertyMasterPersistence = realityPropertyMasterPersistence;
	}

	/**
	 * Returns the reality property master finder.
	 *
	 * @return the reality property master finder
	 */
	public RealityPropertyMasterFinder getRealityPropertyMasterFinder() {
		return realityPropertyMasterFinder;
	}

	/**
	 * Sets the reality property master finder.
	 *
	 * @param realityPropertyMasterFinder the reality property master finder
	 */
	public void setRealityPropertyMasterFinder(
		RealityPropertyMasterFinder realityPropertyMasterFinder) {
		this.realityPropertyMasterFinder = realityPropertyMasterFinder;
	}

	/**
	 * Returns the reliance reality local service.
	 *
	 * @return the reliance reality local service
	 */
	public com.reliance.reality.service.RelianceRealityLocalService getRelianceRealityLocalService() {
		return relianceRealityLocalService;
	}

	/**
	 * Sets the reliance reality local service.
	 *
	 * @param relianceRealityLocalService the reliance reality local service
	 */
	public void setRelianceRealityLocalService(
		com.reliance.reality.service.RelianceRealityLocalService relianceRealityLocalService) {
		this.relianceRealityLocalService = relianceRealityLocalService;
	}

	/**
	 * Returns the reliance reality persistence.
	 *
	 * @return the reliance reality persistence
	 */
	public RelianceRealityPersistence getRelianceRealityPersistence() {
		return relianceRealityPersistence;
	}

	/**
	 * Sets the reliance reality persistence.
	 *
	 * @param relianceRealityPersistence the reliance reality persistence
	 */
	public void setRelianceRealityPersistence(
		RelianceRealityPersistence relianceRealityPersistence) {
		this.relianceRealityPersistence = relianceRealityPersistence;
	}

	/**
	 * Returns the reliance reality finder.
	 *
	 * @return the reliance reality finder
	 */
	public RelianceRealityFinder getRelianceRealityFinder() {
		return relianceRealityFinder;
	}

	/**
	 * Sets the reliance reality finder.
	 *
	 * @param relianceRealityFinder the reliance reality finder
	 */
	public void setRelianceRealityFinder(
		RelianceRealityFinder relianceRealityFinder) {
		this.relianceRealityFinder = relianceRealityFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.reliance.reality.model.RealityPropertyMaster",
			realityPropertyMasterLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.reliance.reality.model.RealityPropertyMaster");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return RealityPropertyMasterLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return RealityPropertyMaster.class;
	}

	protected String getModelClassName() {
		return RealityPropertyMaster.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = realityPropertyMasterPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = RealityPropertyMasterLocalService.class)
	protected RealityPropertyMasterLocalService realityPropertyMasterLocalService;
	@BeanReference(type = RealityPropertyMasterPersistence.class)
	protected RealityPropertyMasterPersistence realityPropertyMasterPersistence;
	@BeanReference(type = RealityPropertyMasterFinder.class)
	protected RealityPropertyMasterFinder realityPropertyMasterFinder;
	@BeanReference(type = com.reliance.reality.service.RelianceRealityLocalService.class)
	protected com.reliance.reality.service.RelianceRealityLocalService relianceRealityLocalService;
	@BeanReference(type = RelianceRealityPersistence.class)
	protected RelianceRealityPersistence relianceRealityPersistence;
	@BeanReference(type = RelianceRealityFinder.class)
	protected RelianceRealityFinder relianceRealityFinder;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}