/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.reliance.reality.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RealityPropertyMaster service. Represents a row in the &quot;REALITY_PROPERTY_MSTR&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.reliance.reality.model.impl.RealityPropertyMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.reliance.reality.model.impl.RealityPropertyMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RealityPropertyMaster
 * @see com.reliance.reality.model.impl.RealityPropertyMasterImpl
 * @see com.reliance.reality.model.impl.RealityPropertyMasterModelImpl
 * @generated
 */
@ProviderType
public interface RealityPropertyMasterModel extends BaseModel<RealityPropertyMaster> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a reality property master model instance should use the {@link RealityPropertyMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this reality property master.
	 *
	 * @return the primary key of this reality property master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this reality property master.
	 *
	 * @param primaryKey the primary key of this reality property master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the property_id of this reality property master.
	 *
	 * @return the property_id of this reality property master
	 */
	public long getProperty_ID();

	/**
	 * Sets the property_id of this reality property master.
	 *
	 * @param property_ID the property_id of this reality property master
	 */
	public void setProperty_ID(long property_ID);

	/**
	 * Returns the city of this reality property master.
	 *
	 * @return the city of this reality property master
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this reality property master.
	 *
	 * @param city the city of this reality property master
	 */
	public void setCity(String city);

	/**
	 * Returns the location of this reality property master.
	 *
	 * @return the location of this reality property master
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this reality property master.
	 *
	 * @param location the location of this reality property master
	 */
	public void setLocation(String location);

	/**
	 * Returns the address of this reality property master.
	 *
	 * @return the address of this reality property master
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this reality property master.
	 *
	 * @param address the address of this reality property master
	 */
	public void setAddress(String address);

	/**
	 * Returns the area of this reality property master.
	 *
	 * @return the area of this reality property master
	 */
	@AutoEscape
	public String getArea();

	/**
	 * Sets the area of this reality property master.
	 *
	 * @param area the area of this reality property master
	 */
	public void setArea(String area);

	/**
	 * Returns the type of this reality property master.
	 *
	 * @return the type of this reality property master
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this reality property master.
	 *
	 * @param type the type of this reality property master
	 */
	public void setType(String type);

	/**
	 * Returns the guidance price of this reality property master.
	 *
	 * @return the guidance price of this reality property master
	 */
	@AutoEscape
	public String getGuidancePrice();

	/**
	 * Sets the guidance price of this reality property master.
	 *
	 * @param guidancePrice the guidance price of this reality property master
	 */
	public void setGuidancePrice(String guidancePrice);

	/**
	 * Returns the property bid of this reality property master.
	 *
	 * @return the property bid of this reality property master
	 */
	public long getPropertyBid();

	/**
	 * Sets the property bid of this reality property master.
	 *
	 * @param propertyBid the property bid of this reality property master
	 */
	public void setPropertyBid(long propertyBid);

	/**
	 * Returns the offer price of this reality property master.
	 *
	 * @return the offer price of this reality property master
	 */
	@AutoEscape
	public String getOfferPrice();

	/**
	 * Sets the offer price of this reality property master.
	 *
	 * @param offerPrice the offer price of this reality property master
	 */
	public void setOfferPrice(String offerPrice);

	/**
	 * Returns the age of property of this reality property master.
	 *
	 * @return the age of property of this reality property master
	 */
	@AutoEscape
	public String getAgeOfProperty();

	/**
	 * Sets the age of property of this reality property master.
	 *
	 * @param ageOfProperty the age of property of this reality property master
	 */
	public void setAgeOfProperty(String ageOfProperty);

	/**
	 * Returns the create date of this reality property master.
	 *
	 * @return the create date of this reality property master
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this reality property master.
	 *
	 * @param createDate the create date of this reality property master
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(RealityPropertyMaster realityPropertyMaster);

	@Override
	public int hashCode();

	@Override
	public CacheModel<RealityPropertyMaster> toCacheModel();

	@Override
	public RealityPropertyMaster toEscapedModel();

	@Override
	public RealityPropertyMaster toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}