/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.reliance.reality.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RelianceReality service. Represents a row in the &quot;RELIANCE_REALITY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.reliance.reality.model.impl.RelianceRealityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.reliance.reality.model.impl.RelianceRealityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RelianceReality
 * @see com.reliance.reality.model.impl.RelianceRealityImpl
 * @see com.reliance.reality.model.impl.RelianceRealityModelImpl
 * @generated
 */
@ProviderType
public interface RelianceRealityModel extends BaseModel<RelianceReality> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a reliance reality model instance should use the {@link RelianceReality} interface instead.
	 */

	/**
	 * Returns the primary key of this reliance reality.
	 *
	 * @return the primary key of this reliance reality
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this reliance reality.
	 *
	 * @param primaryKey the primary key of this reliance reality
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the r_ ID of this reliance reality.
	 *
	 * @return the r_ ID of this reliance reality
	 */
	public long getR_Id();

	/**
	 * Sets the r_ ID of this reliance reality.
	 *
	 * @param r_Id the r_ ID of this reliance reality
	 */
	public void setR_Id(long r_Id);

	/**
	 * Returns the city of this reliance reality.
	 *
	 * @return the city of this reliance reality
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this reliance reality.
	 *
	 * @param city the city of this reliance reality
	 */
	public void setCity(String city);

	/**
	 * Returns the location of this reliance reality.
	 *
	 * @return the location of this reliance reality
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this reliance reality.
	 *
	 * @param location the location of this reliance reality
	 */
	public void setLocation(String location);

	/**
	 * Returns the address of this reliance reality.
	 *
	 * @return the address of this reliance reality
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this reliance reality.
	 *
	 * @param address the address of this reliance reality
	 */
	public void setAddress(String address);

	/**
	 * Returns the area of this reliance reality.
	 *
	 * @return the area of this reliance reality
	 */
	@AutoEscape
	public String getArea();

	/**
	 * Sets the area of this reliance reality.
	 *
	 * @param area the area of this reliance reality
	 */
	public void setArea(String area);

	/**
	 * Returns the type of this reliance reality.
	 *
	 * @return the type of this reliance reality
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this reliance reality.
	 *
	 * @param type the type of this reliance reality
	 */
	public void setType(String type);

	/**
	 * Returns the guidance price of this reliance reality.
	 *
	 * @return the guidance price of this reliance reality
	 */
	public long getGuidancePrice();

	/**
	 * Sets the guidance price of this reliance reality.
	 *
	 * @param guidancePrice the guidance price of this reliance reality
	 */
	public void setGuidancePrice(long guidancePrice);

	/**
	 * Returns the property ID of this reliance reality.
	 *
	 * @return the property ID of this reliance reality
	 */
	@AutoEscape
	public String getPropertyId();

	/**
	 * Sets the property ID of this reliance reality.
	 *
	 * @param propertyId the property ID of this reliance reality
	 */
	public void setPropertyId(String propertyId);

	/**
	 * Returns the offer price of this reliance reality.
	 *
	 * @return the offer price of this reliance reality
	 */
	@AutoEscape
	public String getOfferPrice();

	/**
	 * Sets the offer price of this reliance reality.
	 *
	 * @param offerPrice the offer price of this reliance reality
	 */
	public void setOfferPrice(String offerPrice);

	/**
	 * Returns the funding of this reliance reality.
	 *
	 * @return the funding of this reliance reality
	 */
	@AutoEscape
	public String getFunding();

	/**
	 * Sets the funding of this reliance reality.
	 *
	 * @param funding the funding of this reliance reality
	 */
	public void setFunding(String funding);

	/**
	 * Returns the days of this reliance reality.
	 *
	 * @return the days of this reliance reality
	 */
	public long getDays();

	/**
	 * Sets the days of this reliance reality.
	 *
	 * @param days the days of this reliance reality
	 */
	public void setDays(long days);

	/**
	 * Returns the empcode of this reliance reality.
	 *
	 * @return the empcode of this reliance reality
	 */
	@AutoEscape
	public String getEmpcode();

	/**
	 * Sets the empcode of this reliance reality.
	 *
	 * @param empcode the empcode of this reliance reality
	 */
	public void setEmpcode(String empcode);

	/**
	 * Returns the name of this reliance reality.
	 *
	 * @return the name of this reliance reality
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this reliance reality.
	 *
	 * @param name the name of this reliance reality
	 */
	public void setName(String name);

	/**
	 * Returns the email_id of this reliance reality.
	 *
	 * @return the email_id of this reliance reality
	 */
	@AutoEscape
	public String getEmail_id();

	/**
	 * Sets the email_id of this reliance reality.
	 *
	 * @param email_id the email_id of this reliance reality
	 */
	public void setEmail_id(String email_id);

	/**
	 * Returns the mobile of this reliance reality.
	 *
	 * @return the mobile of this reliance reality
	 */
	@AutoEscape
	public String getMobile();

	/**
	 * Sets the mobile of this reliance reality.
	 *
	 * @param mobile the mobile of this reliance reality
	 */
	public void setMobile(String mobile);

	/**
	 * Returns the age of property of this reliance reality.
	 *
	 * @return the age of property of this reliance reality
	 */
	@AutoEscape
	public String getAgeOfProperty();

	/**
	 * Sets the age of property of this reliance reality.
	 *
	 * @param ageOfProperty the age of property of this reliance reality
	 */
	public void setAgeOfProperty(String ageOfProperty);

	/**
	 * Returns the group company name of this reliance reality.
	 *
	 * @return the group company name of this reliance reality
	 */
	@AutoEscape
	public String getGroupCompanyName();

	/**
	 * Sets the group company name of this reliance reality.
	 *
	 * @param groupCompanyName the group company name of this reliance reality
	 */
	public void setGroupCompanyName(String groupCompanyName);

	/**
	 * Returns the create date of this reliance reality.
	 *
	 * @return the create date of this reliance reality
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this reliance reality.
	 *
	 * @param createDate the create date of this reliance reality
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(RelianceReality relianceReality);

	@Override
	public int hashCode();

	@Override
	public CacheModel<RelianceReality> toCacheModel();

	@Override
	public RelianceReality toEscapedModel();

	@Override
	public RelianceReality toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}