/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.news.media.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.news.media.model.NewsAndMedia;
import com.news.media.model.NewsAndMediaModel;
import com.news.media.model.NewsAndMediaSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the NewsAndMedia service. Represents a row in the &quot;mumbai_metro_news_media&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link NewsAndMediaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NewsAndMediaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NewsAndMediaImpl
 * @see NewsAndMedia
 * @see NewsAndMediaModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class NewsAndMediaModelImpl extends BaseModelImpl<NewsAndMedia>
	implements NewsAndMediaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a news and media model instance should use the {@link NewsAndMedia} interface instead.
	 */
	public static final String TABLE_NAME = "mumbai_metro_news_media";
	public static final Object[][] TABLE_COLUMNS = {
			{ "SRNO", Types.BIGINT },
			{ "HDATE", Types.TIMESTAMP },
			{ "HEADLINE", Types.VARCHAR },
			{ "PUBLICATION", Types.VARCHAR },
			{ "DOCUMENT_NAME", Types.VARCHAR },
			{ "CREATEDATE", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("SRNO", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("HDATE", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("HEADLINE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("PUBLICATION", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DOCUMENT_NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CREATEDATE", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table mumbai_metro_news_media (SRNO LONG not null primary key,HDATE DATE null,HEADLINE VARCHAR(75) null,PUBLICATION VARCHAR(75) null,DOCUMENT_NAME VARCHAR(75) null,CREATEDATE DATE null)";
	public static final String TABLE_SQL_DROP = "drop table mumbai_metro_news_media";
	public static final String ORDER_BY_JPQL = " ORDER BY newsAndMedia.SRNO ASC";
	public static final String ORDER_BY_SQL = " ORDER BY mumbai_metro_news_media.SRNO ASC";
	public static final String DATA_SOURCE = "extDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.news.media.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.news.media.model.NewsAndMedia"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.news.media.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.news.media.model.NewsAndMedia"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static NewsAndMedia toModel(NewsAndMediaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		NewsAndMedia model = new NewsAndMediaImpl();

		model.setSRNO(soapModel.getSRNO());
		model.setHDATE(soapModel.getHDATE());
		model.setHEADLINE(soapModel.getHEADLINE());
		model.setPUBLICATION(soapModel.getPUBLICATION());
		model.setDOCUMENT_NAME(soapModel.getDOCUMENT_NAME());
		model.setCREATEDATE(soapModel.getCREATEDATE());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<NewsAndMedia> toModels(NewsAndMediaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<NewsAndMedia> models = new ArrayList<NewsAndMedia>(soapModels.length);

		for (NewsAndMediaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.news.media.service.util.ServiceProps.get(
				"lock.expiration.time.com.news.media.model.NewsAndMedia"));

	public NewsAndMediaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _SRNO;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSRNO(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _SRNO;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NewsAndMedia.class;
	}

	@Override
	public String getModelClassName() {
		return NewsAndMedia.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("SRNO", getSRNO());
		attributes.put("HDATE", getHDATE());
		attributes.put("HEADLINE", getHEADLINE());
		attributes.put("PUBLICATION", getPUBLICATION());
		attributes.put("DOCUMENT_NAME", getDOCUMENT_NAME());
		attributes.put("CREATEDATE", getCREATEDATE());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long SRNO = (Long)attributes.get("SRNO");

		if (SRNO != null) {
			setSRNO(SRNO);
		}

		Date HDATE = (Date)attributes.get("HDATE");

		if (HDATE != null) {
			setHDATE(HDATE);
		}

		String HEADLINE = (String)attributes.get("HEADLINE");

		if (HEADLINE != null) {
			setHEADLINE(HEADLINE);
		}

		String PUBLICATION = (String)attributes.get("PUBLICATION");

		if (PUBLICATION != null) {
			setPUBLICATION(PUBLICATION);
		}

		String DOCUMENT_NAME = (String)attributes.get("DOCUMENT_NAME");

		if (DOCUMENT_NAME != null) {
			setDOCUMENT_NAME(DOCUMENT_NAME);
		}

		Date CREATEDATE = (Date)attributes.get("CREATEDATE");

		if (CREATEDATE != null) {
			setCREATEDATE(CREATEDATE);
		}
	}

	@JSON
	@Override
	public long getSRNO() {
		return _SRNO;
	}

	@Override
	public void setSRNO(long SRNO) {
		_SRNO = SRNO;
	}

	@JSON
	@Override
	public Date getHDATE() {
		return _HDATE;
	}

	@Override
	public void setHDATE(Date HDATE) {
		_HDATE = HDATE;
	}

	@JSON
	@Override
	public String getHEADLINE() {
		if (_HEADLINE == null) {
			return StringPool.BLANK;
		}
		else {
			return _HEADLINE;
		}
	}

	@Override
	public void setHEADLINE(String HEADLINE) {
		_HEADLINE = HEADLINE;
	}

	@JSON
	@Override
	public String getPUBLICATION() {
		if (_PUBLICATION == null) {
			return StringPool.BLANK;
		}
		else {
			return _PUBLICATION;
		}
	}

	@Override
	public void setPUBLICATION(String PUBLICATION) {
		_PUBLICATION = PUBLICATION;
	}

	@JSON
	@Override
	public String getDOCUMENT_NAME() {
		if (_DOCUMENT_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _DOCUMENT_NAME;
		}
	}

	@Override
	public void setDOCUMENT_NAME(String DOCUMENT_NAME) {
		_DOCUMENT_NAME = DOCUMENT_NAME;
	}

	@JSON
	@Override
	public Date getCREATEDATE() {
		return _CREATEDATE;
	}

	@Override
	public void setCREATEDATE(Date CREATEDATE) {
		_CREATEDATE = CREATEDATE;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			NewsAndMedia.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public NewsAndMedia toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (NewsAndMedia)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NewsAndMediaImpl newsAndMediaImpl = new NewsAndMediaImpl();

		newsAndMediaImpl.setSRNO(getSRNO());
		newsAndMediaImpl.setHDATE(getHDATE());
		newsAndMediaImpl.setHEADLINE(getHEADLINE());
		newsAndMediaImpl.setPUBLICATION(getPUBLICATION());
		newsAndMediaImpl.setDOCUMENT_NAME(getDOCUMENT_NAME());
		newsAndMediaImpl.setCREATEDATE(getCREATEDATE());

		newsAndMediaImpl.resetOriginalValues();

		return newsAndMediaImpl;
	}

	@Override
	public int compareTo(NewsAndMedia newsAndMedia) {
		long primaryKey = newsAndMedia.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof NewsAndMedia)) {
			return false;
		}

		NewsAndMedia newsAndMedia = (NewsAndMedia)obj;

		long primaryKey = newsAndMedia.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<NewsAndMedia> toCacheModel() {
		NewsAndMediaCacheModel newsAndMediaCacheModel = new NewsAndMediaCacheModel();

		newsAndMediaCacheModel.SRNO = getSRNO();

		Date HDATE = getHDATE();

		if (HDATE != null) {
			newsAndMediaCacheModel.HDATE = HDATE.getTime();
		}
		else {
			newsAndMediaCacheModel.HDATE = Long.MIN_VALUE;
		}

		newsAndMediaCacheModel.HEADLINE = getHEADLINE();

		String HEADLINE = newsAndMediaCacheModel.HEADLINE;

		if ((HEADLINE != null) && (HEADLINE.length() == 0)) {
			newsAndMediaCacheModel.HEADLINE = null;
		}

		newsAndMediaCacheModel.PUBLICATION = getPUBLICATION();

		String PUBLICATION = newsAndMediaCacheModel.PUBLICATION;

		if ((PUBLICATION != null) && (PUBLICATION.length() == 0)) {
			newsAndMediaCacheModel.PUBLICATION = null;
		}

		newsAndMediaCacheModel.DOCUMENT_NAME = getDOCUMENT_NAME();

		String DOCUMENT_NAME = newsAndMediaCacheModel.DOCUMENT_NAME;

		if ((DOCUMENT_NAME != null) && (DOCUMENT_NAME.length() == 0)) {
			newsAndMediaCacheModel.DOCUMENT_NAME = null;
		}

		Date CREATEDATE = getCREATEDATE();

		if (CREATEDATE != null) {
			newsAndMediaCacheModel.CREATEDATE = CREATEDATE.getTime();
		}
		else {
			newsAndMediaCacheModel.CREATEDATE = Long.MIN_VALUE;
		}

		return newsAndMediaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{SRNO=");
		sb.append(getSRNO());
		sb.append(", HDATE=");
		sb.append(getHDATE());
		sb.append(", HEADLINE=");
		sb.append(getHEADLINE());
		sb.append(", PUBLICATION=");
		sb.append(getPUBLICATION());
		sb.append(", DOCUMENT_NAME=");
		sb.append(getDOCUMENT_NAME());
		sb.append(", CREATEDATE=");
		sb.append(getCREATEDATE());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.news.media.model.NewsAndMedia");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>SRNO</column-name><column-value><![CDATA[");
		sb.append(getSRNO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>HDATE</column-name><column-value><![CDATA[");
		sb.append(getHDATE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>HEADLINE</column-name><column-value><![CDATA[");
		sb.append(getHEADLINE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PUBLICATION</column-name><column-value><![CDATA[");
		sb.append(getPUBLICATION());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DOCUMENT_NAME</column-name><column-value><![CDATA[");
		sb.append(getDOCUMENT_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CREATEDATE</column-name><column-value><![CDATA[");
		sb.append(getCREATEDATE());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = NewsAndMedia.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			NewsAndMedia.class
		};
	private long _SRNO;
	private Date _HDATE;
	private String _HEADLINE;
	private String _PUBLICATION;
	private String _DOCUMENT_NAME;
	private Date _CREATEDATE;
	private NewsAndMedia _escapedModel;
}