/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.unpaid.unclaimed.dividend.holders.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import com.unpaid.unclaimed.dividend.holders.model.UnpaidUnclaimedDevidendHolders;
import com.unpaid.unclaimed.dividend.holders.service.UnpaidUnclaimedDevidendHoldersLocalService;
import com.unpaid.unclaimed.dividend.holders.service.persistence.UnpaidUnclaimedDevidendHoldersFinder;
import com.unpaid.unclaimed.dividend.holders.service.persistence.UnpaidUnclaimedDevidendHoldersPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the unpaid unclaimed devidend holders local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.unpaid.unclaimed.dividend.holders.service.impl.UnpaidUnclaimedDevidendHoldersLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.unpaid.unclaimed.dividend.holders.service.impl.UnpaidUnclaimedDevidendHoldersLocalServiceImpl
 * @see com.unpaid.unclaimed.dividend.holders.service.UnpaidUnclaimedDevidendHoldersLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class UnpaidUnclaimedDevidendHoldersLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements UnpaidUnclaimedDevidendHoldersLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.unpaid.unclaimed.dividend.holders.service.UnpaidUnclaimedDevidendHoldersLocalServiceUtil} to access the unpaid unclaimed devidend holders local service.
	 */

	/**
	 * Adds the unpaid unclaimed devidend holders to the database. Also notifies the appropriate model listeners.
	 *
	 * @param unpaidUnclaimedDevidendHolders the unpaid unclaimed devidend holders
	 * @return the unpaid unclaimed devidend holders that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public UnpaidUnclaimedDevidendHolders addUnpaidUnclaimedDevidendHolders(
		UnpaidUnclaimedDevidendHolders unpaidUnclaimedDevidendHolders) {
		unpaidUnclaimedDevidendHolders.setNew(true);

		return unpaidUnclaimedDevidendHoldersPersistence.update(unpaidUnclaimedDevidendHolders);
	}

	/**
	 * Creates a new unpaid unclaimed devidend holders with the primary key. Does not add the unpaid unclaimed devidend holders to the database.
	 *
	 * @param SRNO the primary key for the new unpaid unclaimed devidend holders
	 * @return the new unpaid unclaimed devidend holders
	 */
	@Override
	public UnpaidUnclaimedDevidendHolders createUnpaidUnclaimedDevidendHolders(
		long SRNO) {
		return unpaidUnclaimedDevidendHoldersPersistence.create(SRNO);
	}

	/**
	 * Deletes the unpaid unclaimed devidend holders with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param SRNO the primary key of the unpaid unclaimed devidend holders
	 * @return the unpaid unclaimed devidend holders that was removed
	 * @throws PortalException if a unpaid unclaimed devidend holders with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public UnpaidUnclaimedDevidendHolders deleteUnpaidUnclaimedDevidendHolders(
		long SRNO) throws PortalException {
		return unpaidUnclaimedDevidendHoldersPersistence.remove(SRNO);
	}

	/**
	 * Deletes the unpaid unclaimed devidend holders from the database. Also notifies the appropriate model listeners.
	 *
	 * @param unpaidUnclaimedDevidendHolders the unpaid unclaimed devidend holders
	 * @return the unpaid unclaimed devidend holders that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public UnpaidUnclaimedDevidendHolders deleteUnpaidUnclaimedDevidendHolders(
		UnpaidUnclaimedDevidendHolders unpaidUnclaimedDevidendHolders) {
		return unpaidUnclaimedDevidendHoldersPersistence.remove(unpaidUnclaimedDevidendHolders);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(UnpaidUnclaimedDevidendHolders.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return unpaidUnclaimedDevidendHoldersPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.unpaid.unclaimed.dividend.holders.model.impl.UnpaidUnclaimedDevidendHoldersModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return unpaidUnclaimedDevidendHoldersPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.unpaid.unclaimed.dividend.holders.model.impl.UnpaidUnclaimedDevidendHoldersModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return unpaidUnclaimedDevidendHoldersPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return unpaidUnclaimedDevidendHoldersPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return unpaidUnclaimedDevidendHoldersPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public UnpaidUnclaimedDevidendHolders fetchUnpaidUnclaimedDevidendHolders(
		long SRNO) {
		return unpaidUnclaimedDevidendHoldersPersistence.fetchByPrimaryKey(SRNO);
	}

	/**
	 * Returns the unpaid unclaimed devidend holders with the primary key.
	 *
	 * @param SRNO the primary key of the unpaid unclaimed devidend holders
	 * @return the unpaid unclaimed devidend holders
	 * @throws PortalException if a unpaid unclaimed devidend holders with the primary key could not be found
	 */
	@Override
	public UnpaidUnclaimedDevidendHolders getUnpaidUnclaimedDevidendHolders(
		long SRNO) throws PortalException {
		return unpaidUnclaimedDevidendHoldersPersistence.findByPrimaryKey(SRNO);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(unpaidUnclaimedDevidendHoldersLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(UnpaidUnclaimedDevidendHolders.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("SRNO");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(unpaidUnclaimedDevidendHoldersLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(UnpaidUnclaimedDevidendHolders.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("SRNO");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(unpaidUnclaimedDevidendHoldersLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(UnpaidUnclaimedDevidendHolders.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("SRNO");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return unpaidUnclaimedDevidendHoldersLocalService.deleteUnpaidUnclaimedDevidendHolders((UnpaidUnclaimedDevidendHolders)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return unpaidUnclaimedDevidendHoldersPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the unpaid unclaimed devidend holderses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.unpaid.unclaimed.dividend.holders.model.impl.UnpaidUnclaimedDevidendHoldersModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of unpaid unclaimed devidend holderses
	 * @param end the upper bound of the range of unpaid unclaimed devidend holderses (not inclusive)
	 * @return the range of unpaid unclaimed devidend holderses
	 */
	@Override
	public List<UnpaidUnclaimedDevidendHolders> getUnpaidUnclaimedDevidendHolderses(
		int start, int end) {
		return unpaidUnclaimedDevidendHoldersPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of unpaid unclaimed devidend holderses.
	 *
	 * @return the number of unpaid unclaimed devidend holderses
	 */
	@Override
	public int getUnpaidUnclaimedDevidendHoldersesCount() {
		return unpaidUnclaimedDevidendHoldersPersistence.countAll();
	}

	/**
	 * Updates the unpaid unclaimed devidend holders in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param unpaidUnclaimedDevidendHolders the unpaid unclaimed devidend holders
	 * @return the unpaid unclaimed devidend holders that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public UnpaidUnclaimedDevidendHolders updateUnpaidUnclaimedDevidendHolders(
		UnpaidUnclaimedDevidendHolders unpaidUnclaimedDevidendHolders) {
		return unpaidUnclaimedDevidendHoldersPersistence.update(unpaidUnclaimedDevidendHolders);
	}

	/**
	 * Returns the unpaid unclaimed devidend holders local service.
	 *
	 * @return the unpaid unclaimed devidend holders local service
	 */
	public UnpaidUnclaimedDevidendHoldersLocalService getUnpaidUnclaimedDevidendHoldersLocalService() {
		return unpaidUnclaimedDevidendHoldersLocalService;
	}

	/**
	 * Sets the unpaid unclaimed devidend holders local service.
	 *
	 * @param unpaidUnclaimedDevidendHoldersLocalService the unpaid unclaimed devidend holders local service
	 */
	public void setUnpaidUnclaimedDevidendHoldersLocalService(
		UnpaidUnclaimedDevidendHoldersLocalService unpaidUnclaimedDevidendHoldersLocalService) {
		this.unpaidUnclaimedDevidendHoldersLocalService = unpaidUnclaimedDevidendHoldersLocalService;
	}

	/**
	 * Returns the unpaid unclaimed devidend holders persistence.
	 *
	 * @return the unpaid unclaimed devidend holders persistence
	 */
	public UnpaidUnclaimedDevidendHoldersPersistence getUnpaidUnclaimedDevidendHoldersPersistence() {
		return unpaidUnclaimedDevidendHoldersPersistence;
	}

	/**
	 * Sets the unpaid unclaimed devidend holders persistence.
	 *
	 * @param unpaidUnclaimedDevidendHoldersPersistence the unpaid unclaimed devidend holders persistence
	 */
	public void setUnpaidUnclaimedDevidendHoldersPersistence(
		UnpaidUnclaimedDevidendHoldersPersistence unpaidUnclaimedDevidendHoldersPersistence) {
		this.unpaidUnclaimedDevidendHoldersPersistence = unpaidUnclaimedDevidendHoldersPersistence;
	}

	/**
	 * Returns the unpaid unclaimed devidend holders finder.
	 *
	 * @return the unpaid unclaimed devidend holders finder
	 */
	public UnpaidUnclaimedDevidendHoldersFinder getUnpaidUnclaimedDevidendHoldersFinder() {
		return unpaidUnclaimedDevidendHoldersFinder;
	}

	/**
	 * Sets the unpaid unclaimed devidend holders finder.
	 *
	 * @param unpaidUnclaimedDevidendHoldersFinder the unpaid unclaimed devidend holders finder
	 */
	public void setUnpaidUnclaimedDevidendHoldersFinder(
		UnpaidUnclaimedDevidendHoldersFinder unpaidUnclaimedDevidendHoldersFinder) {
		this.unpaidUnclaimedDevidendHoldersFinder = unpaidUnclaimedDevidendHoldersFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.unpaid.unclaimed.dividend.holders.model.UnpaidUnclaimedDevidendHolders",
			unpaidUnclaimedDevidendHoldersLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.unpaid.unclaimed.dividend.holders.model.UnpaidUnclaimedDevidendHolders");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return UnpaidUnclaimedDevidendHoldersLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return UnpaidUnclaimedDevidendHolders.class;
	}

	protected String getModelClassName() {
		return UnpaidUnclaimedDevidendHolders.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = unpaidUnclaimedDevidendHoldersPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = UnpaidUnclaimedDevidendHoldersLocalService.class)
	protected UnpaidUnclaimedDevidendHoldersLocalService unpaidUnclaimedDevidendHoldersLocalService;
	@BeanReference(type = UnpaidUnclaimedDevidendHoldersPersistence.class)
	protected UnpaidUnclaimedDevidendHoldersPersistence unpaidUnclaimedDevidendHoldersPersistence;
	@BeanReference(type = UnpaidUnclaimedDevidendHoldersFinder.class)
	protected UnpaidUnclaimedDevidendHoldersFinder unpaidUnclaimedDevidendHoldersFinder;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}