/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.news.media.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import com.news.media.model.NewsAndMedia;
import com.news.media.service.NewsAndMediaLocalService;
import com.news.media.service.persistence.NewsAndMediaFinder;
import com.news.media.service.persistence.NewsAndMediaPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the news and media local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.news.media.service.impl.NewsAndMediaLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.news.media.service.impl.NewsAndMediaLocalServiceImpl
 * @see com.news.media.service.NewsAndMediaLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class NewsAndMediaLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements NewsAndMediaLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.news.media.service.NewsAndMediaLocalServiceUtil} to access the news and media local service.
	 */

	/**
	 * Adds the news and media to the database. Also notifies the appropriate model listeners.
	 *
	 * @param newsAndMedia the news and media
	 * @return the news and media that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public NewsAndMedia addNewsAndMedia(NewsAndMedia newsAndMedia) {
		newsAndMedia.setNew(true);

		return newsAndMediaPersistence.update(newsAndMedia);
	}

	/**
	 * Creates a new news and media with the primary key. Does not add the news and media to the database.
	 *
	 * @param SRNO the primary key for the new news and media
	 * @return the new news and media
	 */
	@Override
	public NewsAndMedia createNewsAndMedia(long SRNO) {
		return newsAndMediaPersistence.create(SRNO);
	}

	/**
	 * Deletes the news and media with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param SRNO the primary key of the news and media
	 * @return the news and media that was removed
	 * @throws PortalException if a news and media with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public NewsAndMedia deleteNewsAndMedia(long SRNO) throws PortalException {
		return newsAndMediaPersistence.remove(SRNO);
	}

	/**
	 * Deletes the news and media from the database. Also notifies the appropriate model listeners.
	 *
	 * @param newsAndMedia the news and media
	 * @return the news and media that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public NewsAndMedia deleteNewsAndMedia(NewsAndMedia newsAndMedia) {
		return newsAndMediaPersistence.remove(newsAndMedia);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(NewsAndMedia.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return newsAndMediaPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.news.media.model.impl.NewsAndMediaModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return newsAndMediaPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.news.media.model.impl.NewsAndMediaModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return newsAndMediaPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return newsAndMediaPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return newsAndMediaPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public NewsAndMedia fetchNewsAndMedia(long SRNO) {
		return newsAndMediaPersistence.fetchByPrimaryKey(SRNO);
	}

	/**
	 * Returns the news and media with the primary key.
	 *
	 * @param SRNO the primary key of the news and media
	 * @return the news and media
	 * @throws PortalException if a news and media with the primary key could not be found
	 */
	@Override
	public NewsAndMedia getNewsAndMedia(long SRNO) throws PortalException {
		return newsAndMediaPersistence.findByPrimaryKey(SRNO);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(newsAndMediaLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(NewsAndMedia.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("SRNO");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(newsAndMediaLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(NewsAndMedia.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("SRNO");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(newsAndMediaLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(NewsAndMedia.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("SRNO");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return newsAndMediaLocalService.deleteNewsAndMedia((NewsAndMedia)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return newsAndMediaPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the news and medias.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.news.media.model.impl.NewsAndMediaModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of news and medias
	 * @param end the upper bound of the range of news and medias (not inclusive)
	 * @return the range of news and medias
	 */
	@Override
	public List<NewsAndMedia> getNewsAndMedias(int start, int end) {
		return newsAndMediaPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of news and medias.
	 *
	 * @return the number of news and medias
	 */
	@Override
	public int getNewsAndMediasCount() {
		return newsAndMediaPersistence.countAll();
	}

	/**
	 * Updates the news and media in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param newsAndMedia the news and media
	 * @return the news and media that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public NewsAndMedia updateNewsAndMedia(NewsAndMedia newsAndMedia) {
		return newsAndMediaPersistence.update(newsAndMedia);
	}

	/**
	 * Returns the news and media local service.
	 *
	 * @return the news and media local service
	 */
	public NewsAndMediaLocalService getNewsAndMediaLocalService() {
		return newsAndMediaLocalService;
	}

	/**
	 * Sets the news and media local service.
	 *
	 * @param newsAndMediaLocalService the news and media local service
	 */
	public void setNewsAndMediaLocalService(
		NewsAndMediaLocalService newsAndMediaLocalService) {
		this.newsAndMediaLocalService = newsAndMediaLocalService;
	}

	/**
	 * Returns the news and media persistence.
	 *
	 * @return the news and media persistence
	 */
	public NewsAndMediaPersistence getNewsAndMediaPersistence() {
		return newsAndMediaPersistence;
	}

	/**
	 * Sets the news and media persistence.
	 *
	 * @param newsAndMediaPersistence the news and media persistence
	 */
	public void setNewsAndMediaPersistence(
		NewsAndMediaPersistence newsAndMediaPersistence) {
		this.newsAndMediaPersistence = newsAndMediaPersistence;
	}

	/**
	 * Returns the news and media finder.
	 *
	 * @return the news and media finder
	 */
	public NewsAndMediaFinder getNewsAndMediaFinder() {
		return newsAndMediaFinder;
	}

	/**
	 * Sets the news and media finder.
	 *
	 * @param newsAndMediaFinder the news and media finder
	 */
	public void setNewsAndMediaFinder(NewsAndMediaFinder newsAndMediaFinder) {
		this.newsAndMediaFinder = newsAndMediaFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.news.media.model.NewsAndMedia",
			newsAndMediaLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.news.media.model.NewsAndMedia");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return NewsAndMediaLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return NewsAndMedia.class;
	}

	protected String getModelClassName() {
		return NewsAndMedia.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = newsAndMediaPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = NewsAndMediaLocalService.class)
	protected NewsAndMediaLocalService newsAndMediaLocalService;
	@BeanReference(type = NewsAndMediaPersistence.class)
	protected NewsAndMediaPersistence newsAndMediaPersistence;
	@BeanReference(type = NewsAndMediaFinder.class)
	protected NewsAndMediaFinder newsAndMediaFinder;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}