/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package rpower.shareholders.doc.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import rpower.shareholders.doc.model.RpowerShareHoldersDoc;
import rpower.shareholders.doc.service.RpowerShareHoldersDocLocalService;
import rpower.shareholders.doc.service.persistence.RpowerShareHoldersDocFinder;
import rpower.shareholders.doc.service.persistence.RpowerShareHoldersDocPersistence;
import rpower.shareholders.doc.service.persistence.RpowerShareHoldersFinder;
import rpower.shareholders.doc.service.persistence.RpowerShareHoldersPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the rpower share holders doc local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link rpower.shareholders.doc.service.impl.RpowerShareHoldersDocLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see rpower.shareholders.doc.service.impl.RpowerShareHoldersDocLocalServiceImpl
 * @see rpower.shareholders.doc.service.RpowerShareHoldersDocLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class RpowerShareHoldersDocLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements RpowerShareHoldersDocLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link rpower.shareholders.doc.service.RpowerShareHoldersDocLocalServiceUtil} to access the rpower share holders doc local service.
	 */

	/**
	 * Adds the rpower share holders doc to the database. Also notifies the appropriate model listeners.
	 *
	 * @param rpowerShareHoldersDoc the rpower share holders doc
	 * @return the rpower share holders doc that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RpowerShareHoldersDoc addRpowerShareHoldersDoc(
		RpowerShareHoldersDoc rpowerShareHoldersDoc) {
		rpowerShareHoldersDoc.setNew(true);

		return rpowerShareHoldersDocPersistence.update(rpowerShareHoldersDoc);
	}

	/**
	 * Creates a new rpower share holders doc with the primary key. Does not add the rpower share holders doc to the database.
	 *
	 * @param pressId the primary key for the new rpower share holders doc
	 * @return the new rpower share holders doc
	 */
	@Override
	public RpowerShareHoldersDoc createRpowerShareHoldersDoc(long pressId) {
		return rpowerShareHoldersDocPersistence.create(pressId);
	}

	/**
	 * Deletes the rpower share holders doc with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param pressId the primary key of the rpower share holders doc
	 * @return the rpower share holders doc that was removed
	 * @throws PortalException if a rpower share holders doc with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RpowerShareHoldersDoc deleteRpowerShareHoldersDoc(long pressId)
		throws PortalException {
		return rpowerShareHoldersDocPersistence.remove(pressId);
	}

	/**
	 * Deletes the rpower share holders doc from the database. Also notifies the appropriate model listeners.
	 *
	 * @param rpowerShareHoldersDoc the rpower share holders doc
	 * @return the rpower share holders doc that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RpowerShareHoldersDoc deleteRpowerShareHoldersDoc(
		RpowerShareHoldersDoc rpowerShareHoldersDoc) {
		return rpowerShareHoldersDocPersistence.remove(rpowerShareHoldersDoc);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(RpowerShareHoldersDoc.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return rpowerShareHoldersDocPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link rpower.shareholders.doc.model.impl.RpowerShareHoldersDocModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return rpowerShareHoldersDocPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link rpower.shareholders.doc.model.impl.RpowerShareHoldersDocModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return rpowerShareHoldersDocPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return rpowerShareHoldersDocPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return rpowerShareHoldersDocPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public RpowerShareHoldersDoc fetchRpowerShareHoldersDoc(long pressId) {
		return rpowerShareHoldersDocPersistence.fetchByPrimaryKey(pressId);
	}

	/**
	 * Returns the rpower share holders doc with the primary key.
	 *
	 * @param pressId the primary key of the rpower share holders doc
	 * @return the rpower share holders doc
	 * @throws PortalException if a rpower share holders doc with the primary key could not be found
	 */
	@Override
	public RpowerShareHoldersDoc getRpowerShareHoldersDoc(long pressId)
		throws PortalException {
		return rpowerShareHoldersDocPersistence.findByPrimaryKey(pressId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(rpowerShareHoldersDocLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RpowerShareHoldersDoc.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("pressId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(rpowerShareHoldersDocLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(RpowerShareHoldersDoc.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("pressId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(rpowerShareHoldersDocLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RpowerShareHoldersDoc.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("pressId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return rpowerShareHoldersDocLocalService.deleteRpowerShareHoldersDoc((RpowerShareHoldersDoc)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return rpowerShareHoldersDocPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the rpower share holders docs.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link rpower.shareholders.doc.model.impl.RpowerShareHoldersDocModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of rpower share holders docs
	 * @param end the upper bound of the range of rpower share holders docs (not inclusive)
	 * @return the range of rpower share holders docs
	 */
	@Override
	public List<RpowerShareHoldersDoc> getRpowerShareHoldersDocs(int start,
		int end) {
		return rpowerShareHoldersDocPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of rpower share holders docs.
	 *
	 * @return the number of rpower share holders docs
	 */
	@Override
	public int getRpowerShareHoldersDocsCount() {
		return rpowerShareHoldersDocPersistence.countAll();
	}

	/**
	 * Updates the rpower share holders doc in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param rpowerShareHoldersDoc the rpower share holders doc
	 * @return the rpower share holders doc that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RpowerShareHoldersDoc updateRpowerShareHoldersDoc(
		RpowerShareHoldersDoc rpowerShareHoldersDoc) {
		return rpowerShareHoldersDocPersistence.update(rpowerShareHoldersDoc);
	}

	/**
	 * Returns the rpower share holders local service.
	 *
	 * @return the rpower share holders local service
	 */
	public rpower.shareholders.doc.service.RpowerShareHoldersLocalService getRpowerShareHoldersLocalService() {
		return rpowerShareHoldersLocalService;
	}

	/**
	 * Sets the rpower share holders local service.
	 *
	 * @param rpowerShareHoldersLocalService the rpower share holders local service
	 */
	public void setRpowerShareHoldersLocalService(
		rpower.shareholders.doc.service.RpowerShareHoldersLocalService rpowerShareHoldersLocalService) {
		this.rpowerShareHoldersLocalService = rpowerShareHoldersLocalService;
	}

	/**
	 * Returns the rpower share holders persistence.
	 *
	 * @return the rpower share holders persistence
	 */
	public RpowerShareHoldersPersistence getRpowerShareHoldersPersistence() {
		return rpowerShareHoldersPersistence;
	}

	/**
	 * Sets the rpower share holders persistence.
	 *
	 * @param rpowerShareHoldersPersistence the rpower share holders persistence
	 */
	public void setRpowerShareHoldersPersistence(
		RpowerShareHoldersPersistence rpowerShareHoldersPersistence) {
		this.rpowerShareHoldersPersistence = rpowerShareHoldersPersistence;
	}

	/**
	 * Returns the rpower share holders finder.
	 *
	 * @return the rpower share holders finder
	 */
	public RpowerShareHoldersFinder getRpowerShareHoldersFinder() {
		return rpowerShareHoldersFinder;
	}

	/**
	 * Sets the rpower share holders finder.
	 *
	 * @param rpowerShareHoldersFinder the rpower share holders finder
	 */
	public void setRpowerShareHoldersFinder(
		RpowerShareHoldersFinder rpowerShareHoldersFinder) {
		this.rpowerShareHoldersFinder = rpowerShareHoldersFinder;
	}

	/**
	 * Returns the rpower share holders doc local service.
	 *
	 * @return the rpower share holders doc local service
	 */
	public RpowerShareHoldersDocLocalService getRpowerShareHoldersDocLocalService() {
		return rpowerShareHoldersDocLocalService;
	}

	/**
	 * Sets the rpower share holders doc local service.
	 *
	 * @param rpowerShareHoldersDocLocalService the rpower share holders doc local service
	 */
	public void setRpowerShareHoldersDocLocalService(
		RpowerShareHoldersDocLocalService rpowerShareHoldersDocLocalService) {
		this.rpowerShareHoldersDocLocalService = rpowerShareHoldersDocLocalService;
	}

	/**
	 * Returns the rpower share holders doc persistence.
	 *
	 * @return the rpower share holders doc persistence
	 */
	public RpowerShareHoldersDocPersistence getRpowerShareHoldersDocPersistence() {
		return rpowerShareHoldersDocPersistence;
	}

	/**
	 * Sets the rpower share holders doc persistence.
	 *
	 * @param rpowerShareHoldersDocPersistence the rpower share holders doc persistence
	 */
	public void setRpowerShareHoldersDocPersistence(
		RpowerShareHoldersDocPersistence rpowerShareHoldersDocPersistence) {
		this.rpowerShareHoldersDocPersistence = rpowerShareHoldersDocPersistence;
	}

	/**
	 * Returns the rpower share holders doc finder.
	 *
	 * @return the rpower share holders doc finder
	 */
	public RpowerShareHoldersDocFinder getRpowerShareHoldersDocFinder() {
		return rpowerShareHoldersDocFinder;
	}

	/**
	 * Sets the rpower share holders doc finder.
	 *
	 * @param rpowerShareHoldersDocFinder the rpower share holders doc finder
	 */
	public void setRpowerShareHoldersDocFinder(
		RpowerShareHoldersDocFinder rpowerShareHoldersDocFinder) {
		this.rpowerShareHoldersDocFinder = rpowerShareHoldersDocFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("rpower.shareholders.doc.model.RpowerShareHoldersDoc",
			rpowerShareHoldersDocLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"rpower.shareholders.doc.model.RpowerShareHoldersDoc");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return RpowerShareHoldersDocLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return RpowerShareHoldersDoc.class;
	}

	protected String getModelClassName() {
		return RpowerShareHoldersDoc.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = rpowerShareHoldersDocPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = rpower.shareholders.doc.service.RpowerShareHoldersLocalService.class)
	protected rpower.shareholders.doc.service.RpowerShareHoldersLocalService rpowerShareHoldersLocalService;
	@BeanReference(type = RpowerShareHoldersPersistence.class)
	protected RpowerShareHoldersPersistence rpowerShareHoldersPersistence;
	@BeanReference(type = RpowerShareHoldersFinder.class)
	protected RpowerShareHoldersFinder rpowerShareHoldersFinder;
	@BeanReference(type = RpowerShareHoldersDocLocalService.class)
	protected RpowerShareHoldersDocLocalService rpowerShareHoldersDocLocalService;
	@BeanReference(type = RpowerShareHoldersDocPersistence.class)
	protected RpowerShareHoldersDocPersistence rpowerShareHoldersDocPersistence;
	@BeanReference(type = RpowerShareHoldersDocFinder.class)
	protected RpowerShareHoldersDocFinder rpowerShareHoldersDocFinder;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}