/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package rpower.shareholders.doc.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import rpower.shareholders.doc.model.RpowerShareHolders;
import rpower.shareholders.doc.service.RpowerShareHoldersService;
import rpower.shareholders.doc.service.persistence.RpowerShareHoldersDocFinder;
import rpower.shareholders.doc.service.persistence.RpowerShareHoldersDocPersistence;
import rpower.shareholders.doc.service.persistence.RpowerShareHoldersFinder;
import rpower.shareholders.doc.service.persistence.RpowerShareHoldersPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the rpower share holders remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link rpower.shareholders.doc.service.impl.RpowerShareHoldersServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see rpower.shareholders.doc.service.impl.RpowerShareHoldersServiceImpl
 * @see rpower.shareholders.doc.service.RpowerShareHoldersServiceUtil
 * @generated
 */
public abstract class RpowerShareHoldersServiceBaseImpl extends BaseServiceImpl
	implements RpowerShareHoldersService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link rpower.shareholders.doc.service.RpowerShareHoldersServiceUtil} to access the rpower share holders remote service.
	 */

	/**
	 * Returns the rpower share holders local service.
	 *
	 * @return the rpower share holders local service
	 */
	public rpower.shareholders.doc.service.RpowerShareHoldersLocalService getRpowerShareHoldersLocalService() {
		return rpowerShareHoldersLocalService;
	}

	/**
	 * Sets the rpower share holders local service.
	 *
	 * @param rpowerShareHoldersLocalService the rpower share holders local service
	 */
	public void setRpowerShareHoldersLocalService(
		rpower.shareholders.doc.service.RpowerShareHoldersLocalService rpowerShareHoldersLocalService) {
		this.rpowerShareHoldersLocalService = rpowerShareHoldersLocalService;
	}

	/**
	 * Returns the rpower share holders remote service.
	 *
	 * @return the rpower share holders remote service
	 */
	public RpowerShareHoldersService getRpowerShareHoldersService() {
		return rpowerShareHoldersService;
	}

	/**
	 * Sets the rpower share holders remote service.
	 *
	 * @param rpowerShareHoldersService the rpower share holders remote service
	 */
	public void setRpowerShareHoldersService(
		RpowerShareHoldersService rpowerShareHoldersService) {
		this.rpowerShareHoldersService = rpowerShareHoldersService;
	}

	/**
	 * Returns the rpower share holders persistence.
	 *
	 * @return the rpower share holders persistence
	 */
	public RpowerShareHoldersPersistence getRpowerShareHoldersPersistence() {
		return rpowerShareHoldersPersistence;
	}

	/**
	 * Sets the rpower share holders persistence.
	 *
	 * @param rpowerShareHoldersPersistence the rpower share holders persistence
	 */
	public void setRpowerShareHoldersPersistence(
		RpowerShareHoldersPersistence rpowerShareHoldersPersistence) {
		this.rpowerShareHoldersPersistence = rpowerShareHoldersPersistence;
	}

	/**
	 * Returns the rpower share holders finder.
	 *
	 * @return the rpower share holders finder
	 */
	public RpowerShareHoldersFinder getRpowerShareHoldersFinder() {
		return rpowerShareHoldersFinder;
	}

	/**
	 * Sets the rpower share holders finder.
	 *
	 * @param rpowerShareHoldersFinder the rpower share holders finder
	 */
	public void setRpowerShareHoldersFinder(
		RpowerShareHoldersFinder rpowerShareHoldersFinder) {
		this.rpowerShareHoldersFinder = rpowerShareHoldersFinder;
	}

	/**
	 * Returns the rpower share holders doc local service.
	 *
	 * @return the rpower share holders doc local service
	 */
	public rpower.shareholders.doc.service.RpowerShareHoldersDocLocalService getRpowerShareHoldersDocLocalService() {
		return rpowerShareHoldersDocLocalService;
	}

	/**
	 * Sets the rpower share holders doc local service.
	 *
	 * @param rpowerShareHoldersDocLocalService the rpower share holders doc local service
	 */
	public void setRpowerShareHoldersDocLocalService(
		rpower.shareholders.doc.service.RpowerShareHoldersDocLocalService rpowerShareHoldersDocLocalService) {
		this.rpowerShareHoldersDocLocalService = rpowerShareHoldersDocLocalService;
	}

	/**
	 * Returns the rpower share holders doc remote service.
	 *
	 * @return the rpower share holders doc remote service
	 */
	public rpower.shareholders.doc.service.RpowerShareHoldersDocService getRpowerShareHoldersDocService() {
		return rpowerShareHoldersDocService;
	}

	/**
	 * Sets the rpower share holders doc remote service.
	 *
	 * @param rpowerShareHoldersDocService the rpower share holders doc remote service
	 */
	public void setRpowerShareHoldersDocService(
		rpower.shareholders.doc.service.RpowerShareHoldersDocService rpowerShareHoldersDocService) {
		this.rpowerShareHoldersDocService = rpowerShareHoldersDocService;
	}

	/**
	 * Returns the rpower share holders doc persistence.
	 *
	 * @return the rpower share holders doc persistence
	 */
	public RpowerShareHoldersDocPersistence getRpowerShareHoldersDocPersistence() {
		return rpowerShareHoldersDocPersistence;
	}

	/**
	 * Sets the rpower share holders doc persistence.
	 *
	 * @param rpowerShareHoldersDocPersistence the rpower share holders doc persistence
	 */
	public void setRpowerShareHoldersDocPersistence(
		RpowerShareHoldersDocPersistence rpowerShareHoldersDocPersistence) {
		this.rpowerShareHoldersDocPersistence = rpowerShareHoldersDocPersistence;
	}

	/**
	 * Returns the rpower share holders doc finder.
	 *
	 * @return the rpower share holders doc finder
	 */
	public RpowerShareHoldersDocFinder getRpowerShareHoldersDocFinder() {
		return rpowerShareHoldersDocFinder;
	}

	/**
	 * Sets the rpower share holders doc finder.
	 *
	 * @param rpowerShareHoldersDocFinder the rpower share holders doc finder
	 */
	public void setRpowerShareHoldersDocFinder(
		RpowerShareHoldersDocFinder rpowerShareHoldersDocFinder) {
		this.rpowerShareHoldersDocFinder = rpowerShareHoldersDocFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return RpowerShareHoldersService.class.getName();
	}

	protected Class<?> getModelClass() {
		return RpowerShareHolders.class;
	}

	protected String getModelClassName() {
		return RpowerShareHolders.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = rpowerShareHoldersPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = rpower.shareholders.doc.service.RpowerShareHoldersLocalService.class)
	protected rpower.shareholders.doc.service.RpowerShareHoldersLocalService rpowerShareHoldersLocalService;
	@BeanReference(type = RpowerShareHoldersService.class)
	protected RpowerShareHoldersService rpowerShareHoldersService;
	@BeanReference(type = RpowerShareHoldersPersistence.class)
	protected RpowerShareHoldersPersistence rpowerShareHoldersPersistence;
	@BeanReference(type = RpowerShareHoldersFinder.class)
	protected RpowerShareHoldersFinder rpowerShareHoldersFinder;
	@BeanReference(type = rpower.shareholders.doc.service.RpowerShareHoldersDocLocalService.class)
	protected rpower.shareholders.doc.service.RpowerShareHoldersDocLocalService rpowerShareHoldersDocLocalService;
	@BeanReference(type = rpower.shareholders.doc.service.RpowerShareHoldersDocService.class)
	protected rpower.shareholders.doc.service.RpowerShareHoldersDocService rpowerShareHoldersDocService;
	@BeanReference(type = RpowerShareHoldersDocPersistence.class)
	protected RpowerShareHoldersDocPersistence rpowerShareHoldersDocPersistence;
	@BeanReference(type = RpowerShareHoldersDocFinder.class)
	protected RpowerShareHoldersDocFinder rpowerShareHoldersDocFinder;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}