/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rinfra.unpaid.unclaimed.devidend.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import com.rinfra.unpaid.unclaimed.devidend.model.RpowerUnpaidUnclaimedDevidend;
import com.rinfra.unpaid.unclaimed.devidend.service.RpowerUnpaidUnclaimedDevidendLocalService;
import com.rinfra.unpaid.unclaimed.devidend.service.persistence.RpowerUnpaidUnclaimedDevidendFinder;
import com.rinfra.unpaid.unclaimed.devidend.service.persistence.RpowerUnpaidUnclaimedDevidendPersistence;
import com.rinfra.unpaid.unclaimed.devidend.service.persistence.UnpaidUnclaimedDevidendFinder;
import com.rinfra.unpaid.unclaimed.devidend.service.persistence.UnpaidUnclaimedDevidendPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the rpower unpaid unclaimed devidend local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.rinfra.unpaid.unclaimed.devidend.service.impl.RpowerUnpaidUnclaimedDevidendLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.rinfra.unpaid.unclaimed.devidend.service.impl.RpowerUnpaidUnclaimedDevidendLocalServiceImpl
 * @see com.rinfra.unpaid.unclaimed.devidend.service.RpowerUnpaidUnclaimedDevidendLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class RpowerUnpaidUnclaimedDevidendLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements RpowerUnpaidUnclaimedDevidendLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.rinfra.unpaid.unclaimed.devidend.service.RpowerUnpaidUnclaimedDevidendLocalServiceUtil} to access the rpower unpaid unclaimed devidend local service.
	 */

	/**
	 * Adds the rpower unpaid unclaimed devidend to the database. Also notifies the appropriate model listeners.
	 *
	 * @param rpowerUnpaidUnclaimedDevidend the rpower unpaid unclaimed devidend
	 * @return the rpower unpaid unclaimed devidend that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RpowerUnpaidUnclaimedDevidend addRpowerUnpaidUnclaimedDevidend(
		RpowerUnpaidUnclaimedDevidend rpowerUnpaidUnclaimedDevidend) {
		rpowerUnpaidUnclaimedDevidend.setNew(true);

		return rpowerUnpaidUnclaimedDevidendPersistence.update(rpowerUnpaidUnclaimedDevidend);
	}

	/**
	 * Creates a new rpower unpaid unclaimed devidend with the primary key. Does not add the rpower unpaid unclaimed devidend to the database.
	 *
	 * @param SRNO the primary key for the new rpower unpaid unclaimed devidend
	 * @return the new rpower unpaid unclaimed devidend
	 */
	@Override
	public RpowerUnpaidUnclaimedDevidend createRpowerUnpaidUnclaimedDevidend(
		long SRNO) {
		return rpowerUnpaidUnclaimedDevidendPersistence.create(SRNO);
	}

	/**
	 * Deletes the rpower unpaid unclaimed devidend with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param SRNO the primary key of the rpower unpaid unclaimed devidend
	 * @return the rpower unpaid unclaimed devidend that was removed
	 * @throws PortalException if a rpower unpaid unclaimed devidend with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RpowerUnpaidUnclaimedDevidend deleteRpowerUnpaidUnclaimedDevidend(
		long SRNO) throws PortalException {
		return rpowerUnpaidUnclaimedDevidendPersistence.remove(SRNO);
	}

	/**
	 * Deletes the rpower unpaid unclaimed devidend from the database. Also notifies the appropriate model listeners.
	 *
	 * @param rpowerUnpaidUnclaimedDevidend the rpower unpaid unclaimed devidend
	 * @return the rpower unpaid unclaimed devidend that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RpowerUnpaidUnclaimedDevidend deleteRpowerUnpaidUnclaimedDevidend(
		RpowerUnpaidUnclaimedDevidend rpowerUnpaidUnclaimedDevidend) {
		return rpowerUnpaidUnclaimedDevidendPersistence.remove(rpowerUnpaidUnclaimedDevidend);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(RpowerUnpaidUnclaimedDevidend.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return rpowerUnpaidUnclaimedDevidendPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rinfra.unpaid.unclaimed.devidend.model.impl.RpowerUnpaidUnclaimedDevidendModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return rpowerUnpaidUnclaimedDevidendPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rinfra.unpaid.unclaimed.devidend.model.impl.RpowerUnpaidUnclaimedDevidendModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return rpowerUnpaidUnclaimedDevidendPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return rpowerUnpaidUnclaimedDevidendPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return rpowerUnpaidUnclaimedDevidendPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public RpowerUnpaidUnclaimedDevidend fetchRpowerUnpaidUnclaimedDevidend(
		long SRNO) {
		return rpowerUnpaidUnclaimedDevidendPersistence.fetchByPrimaryKey(SRNO);
	}

	/**
	 * Returns the rpower unpaid unclaimed devidend with the primary key.
	 *
	 * @param SRNO the primary key of the rpower unpaid unclaimed devidend
	 * @return the rpower unpaid unclaimed devidend
	 * @throws PortalException if a rpower unpaid unclaimed devidend with the primary key could not be found
	 */
	@Override
	public RpowerUnpaidUnclaimedDevidend getRpowerUnpaidUnclaimedDevidend(
		long SRNO) throws PortalException {
		return rpowerUnpaidUnclaimedDevidendPersistence.findByPrimaryKey(SRNO);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(rpowerUnpaidUnclaimedDevidendLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RpowerUnpaidUnclaimedDevidend.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("SRNO");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(rpowerUnpaidUnclaimedDevidendLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(RpowerUnpaidUnclaimedDevidend.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("SRNO");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(rpowerUnpaidUnclaimedDevidendLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RpowerUnpaidUnclaimedDevidend.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("SRNO");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return rpowerUnpaidUnclaimedDevidendLocalService.deleteRpowerUnpaidUnclaimedDevidend((RpowerUnpaidUnclaimedDevidend)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return rpowerUnpaidUnclaimedDevidendPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the rpower unpaid unclaimed devidends.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rinfra.unpaid.unclaimed.devidend.model.impl.RpowerUnpaidUnclaimedDevidendModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of rpower unpaid unclaimed devidends
	 * @param end the upper bound of the range of rpower unpaid unclaimed devidends (not inclusive)
	 * @return the range of rpower unpaid unclaimed devidends
	 */
	@Override
	public List<RpowerUnpaidUnclaimedDevidend> getRpowerUnpaidUnclaimedDevidends(
		int start, int end) {
		return rpowerUnpaidUnclaimedDevidendPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of rpower unpaid unclaimed devidends.
	 *
	 * @return the number of rpower unpaid unclaimed devidends
	 */
	@Override
	public int getRpowerUnpaidUnclaimedDevidendsCount() {
		return rpowerUnpaidUnclaimedDevidendPersistence.countAll();
	}

	/**
	 * Updates the rpower unpaid unclaimed devidend in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param rpowerUnpaidUnclaimedDevidend the rpower unpaid unclaimed devidend
	 * @return the rpower unpaid unclaimed devidend that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RpowerUnpaidUnclaimedDevidend updateRpowerUnpaidUnclaimedDevidend(
		RpowerUnpaidUnclaimedDevidend rpowerUnpaidUnclaimedDevidend) {
		return rpowerUnpaidUnclaimedDevidendPersistence.update(rpowerUnpaidUnclaimedDevidend);
	}

	/**
	 * Returns the rpower unpaid unclaimed devidend local service.
	 *
	 * @return the rpower unpaid unclaimed devidend local service
	 */
	public RpowerUnpaidUnclaimedDevidendLocalService getRpowerUnpaidUnclaimedDevidendLocalService() {
		return rpowerUnpaidUnclaimedDevidendLocalService;
	}

	/**
	 * Sets the rpower unpaid unclaimed devidend local service.
	 *
	 * @param rpowerUnpaidUnclaimedDevidendLocalService the rpower unpaid unclaimed devidend local service
	 */
	public void setRpowerUnpaidUnclaimedDevidendLocalService(
		RpowerUnpaidUnclaimedDevidendLocalService rpowerUnpaidUnclaimedDevidendLocalService) {
		this.rpowerUnpaidUnclaimedDevidendLocalService = rpowerUnpaidUnclaimedDevidendLocalService;
	}

	/**
	 * Returns the rpower unpaid unclaimed devidend persistence.
	 *
	 * @return the rpower unpaid unclaimed devidend persistence
	 */
	public RpowerUnpaidUnclaimedDevidendPersistence getRpowerUnpaidUnclaimedDevidendPersistence() {
		return rpowerUnpaidUnclaimedDevidendPersistence;
	}

	/**
	 * Sets the rpower unpaid unclaimed devidend persistence.
	 *
	 * @param rpowerUnpaidUnclaimedDevidendPersistence the rpower unpaid unclaimed devidend persistence
	 */
	public void setRpowerUnpaidUnclaimedDevidendPersistence(
		RpowerUnpaidUnclaimedDevidendPersistence rpowerUnpaidUnclaimedDevidendPersistence) {
		this.rpowerUnpaidUnclaimedDevidendPersistence = rpowerUnpaidUnclaimedDevidendPersistence;
	}

	/**
	 * Returns the rpower unpaid unclaimed devidend finder.
	 *
	 * @return the rpower unpaid unclaimed devidend finder
	 */
	public RpowerUnpaidUnclaimedDevidendFinder getRpowerUnpaidUnclaimedDevidendFinder() {
		return rpowerUnpaidUnclaimedDevidendFinder;
	}

	/**
	 * Sets the rpower unpaid unclaimed devidend finder.
	 *
	 * @param rpowerUnpaidUnclaimedDevidendFinder the rpower unpaid unclaimed devidend finder
	 */
	public void setRpowerUnpaidUnclaimedDevidendFinder(
		RpowerUnpaidUnclaimedDevidendFinder rpowerUnpaidUnclaimedDevidendFinder) {
		this.rpowerUnpaidUnclaimedDevidendFinder = rpowerUnpaidUnclaimedDevidendFinder;
	}

	/**
	 * Returns the unpaid unclaimed devidend local service.
	 *
	 * @return the unpaid unclaimed devidend local service
	 */
	public com.rinfra.unpaid.unclaimed.devidend.service.UnpaidUnclaimedDevidendLocalService getUnpaidUnclaimedDevidendLocalService() {
		return unpaidUnclaimedDevidendLocalService;
	}

	/**
	 * Sets the unpaid unclaimed devidend local service.
	 *
	 * @param unpaidUnclaimedDevidendLocalService the unpaid unclaimed devidend local service
	 */
	public void setUnpaidUnclaimedDevidendLocalService(
		com.rinfra.unpaid.unclaimed.devidend.service.UnpaidUnclaimedDevidendLocalService unpaidUnclaimedDevidendLocalService) {
		this.unpaidUnclaimedDevidendLocalService = unpaidUnclaimedDevidendLocalService;
	}

	/**
	 * Returns the unpaid unclaimed devidend persistence.
	 *
	 * @return the unpaid unclaimed devidend persistence
	 */
	public UnpaidUnclaimedDevidendPersistence getUnpaidUnclaimedDevidendPersistence() {
		return unpaidUnclaimedDevidendPersistence;
	}

	/**
	 * Sets the unpaid unclaimed devidend persistence.
	 *
	 * @param unpaidUnclaimedDevidendPersistence the unpaid unclaimed devidend persistence
	 */
	public void setUnpaidUnclaimedDevidendPersistence(
		UnpaidUnclaimedDevidendPersistence unpaidUnclaimedDevidendPersistence) {
		this.unpaidUnclaimedDevidendPersistence = unpaidUnclaimedDevidendPersistence;
	}

	/**
	 * Returns the unpaid unclaimed devidend finder.
	 *
	 * @return the unpaid unclaimed devidend finder
	 */
	public UnpaidUnclaimedDevidendFinder getUnpaidUnclaimedDevidendFinder() {
		return unpaidUnclaimedDevidendFinder;
	}

	/**
	 * Sets the unpaid unclaimed devidend finder.
	 *
	 * @param unpaidUnclaimedDevidendFinder the unpaid unclaimed devidend finder
	 */
	public void setUnpaidUnclaimedDevidendFinder(
		UnpaidUnclaimedDevidendFinder unpaidUnclaimedDevidendFinder) {
		this.unpaidUnclaimedDevidendFinder = unpaidUnclaimedDevidendFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.rinfra.unpaid.unclaimed.devidend.model.RpowerUnpaidUnclaimedDevidend",
			rpowerUnpaidUnclaimedDevidendLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.rinfra.unpaid.unclaimed.devidend.model.RpowerUnpaidUnclaimedDevidend");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return RpowerUnpaidUnclaimedDevidendLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return RpowerUnpaidUnclaimedDevidend.class;
	}

	protected String getModelClassName() {
		return RpowerUnpaidUnclaimedDevidend.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = rpowerUnpaidUnclaimedDevidendPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = RpowerUnpaidUnclaimedDevidendLocalService.class)
	protected RpowerUnpaidUnclaimedDevidendLocalService rpowerUnpaidUnclaimedDevidendLocalService;
	@BeanReference(type = RpowerUnpaidUnclaimedDevidendPersistence.class)
	protected RpowerUnpaidUnclaimedDevidendPersistence rpowerUnpaidUnclaimedDevidendPersistence;
	@BeanReference(type = RpowerUnpaidUnclaimedDevidendFinder.class)
	protected RpowerUnpaidUnclaimedDevidendFinder rpowerUnpaidUnclaimedDevidendFinder;
	@BeanReference(type = com.rinfra.unpaid.unclaimed.devidend.service.UnpaidUnclaimedDevidendLocalService.class)
	protected com.rinfra.unpaid.unclaimed.devidend.service.UnpaidUnclaimedDevidendLocalService unpaidUnclaimedDevidendLocalService;
	@BeanReference(type = UnpaidUnclaimedDevidendPersistence.class)
	protected UnpaidUnclaimedDevidendPersistence unpaidUnclaimedDevidendPersistence;
	@BeanReference(type = UnpaidUnclaimedDevidendFinder.class)
	protected UnpaidUnclaimedDevidendFinder unpaidUnclaimedDevidendFinder;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}