/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package OCCModuleNew.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the OccMessageNew service. Represents a row in the &quot;OCCMESSAGENEW&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link OCCModuleNew.model.impl.OccMessageNewModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OCCModuleNew.model.impl.OccMessageNewImpl}.
 * </p>
 *
 * @author Mukesh Patidar
 * @see OccMessageNew
 * @see OCCModuleNew.model.impl.OccMessageNewImpl
 * @see OCCModuleNew.model.impl.OccMessageNewModelImpl
 * @generated
 */
@ProviderType
public interface OccMessageNewModel extends BaseModel<OccMessageNew> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a occ message new model instance should use the {@link OccMessageNew} interface instead.
	 */

	/**
	 * Returns the primary key of this occ message new.
	 *
	 * @return the primary key of this occ message new
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this occ message new.
	 *
	 * @param primaryKey the primary key of this occ message new
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the msg_id of this occ message new.
	 *
	 * @return the msg_id of this occ message new
	 */
	public long getMSG_ID();

	/**
	 * Sets the msg_id of this occ message new.
	 *
	 * @param MSG_ID the msg_id of this occ message new
	 */
	public void setMSG_ID(long MSG_ID);

	/**
	 * Returns the list name of this occ message new.
	 *
	 * @return the list name of this occ message new
	 */
	@AutoEscape
	public String getListName();

	/**
	 * Sets the list name of this occ message new.
	 *
	 * @param ListName the list name of this occ message new
	 */
	public void setListName(String ListName);

	/**
	 * Returns the message of this occ message new.
	 *
	 * @return the message of this occ message new
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this occ message new.
	 *
	 * @param Message the message of this occ message new
	 */
	public void setMessage(String Message);

	/**
	 * Returns the m sg send date of this occ message new.
	 *
	 * @return the m sg send date of this occ message new
	 */
	@AutoEscape
	public String getMSgSendDate();

	/**
	 * Sets the m sg send date of this occ message new.
	 *
	 * @param MSgSendDate the m sg send date of this occ message new
	 */
	public void setMSgSendDate(String MSgSendDate);

	/**
	 * Returns the severity of this occ message new.
	 *
	 * @return the severity of this occ message new
	 */
	@AutoEscape
	public String getSeverity();

	/**
	 * Sets the severity of this occ message new.
	 *
	 * @param Severity the severity of this occ message new
	 */
	public void setSeverity(String Severity);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(OCCModuleNew.model.OccMessageNew occMessageNew);

	@Override
	public int hashCode();

	@Override
	public CacheModel<OCCModuleNew.model.OccMessageNew> toCacheModel();

	@Override
	public OCCModuleNew.model.OccMessageNew toEscapedModel();

	@Override
	public OCCModuleNew.model.OccMessageNew toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}