/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package OCCModuleNew.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the OccNew service. Represents a row in the &quot;OCCNEW&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link OCCModuleNew.model.impl.OccNewModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OCCModuleNew.model.impl.OccNewImpl}.
 * </p>
 *
 * @author Mukesh Patidar
 * @see OccNew
 * @see OCCModuleNew.model.impl.OccNewImpl
 * @see OCCModuleNew.model.impl.OccNewModelImpl
 * @generated
 */
@ProviderType
public interface OccNewModel extends BaseModel<OccNew> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a occ new model instance should use the {@link OccNew} interface instead.
	 */

	/**
	 * Returns the primary key of this occ new.
	 *
	 * @return the primary key of this occ new
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this occ new.
	 *
	 * @param primaryKey the primary key of this occ new
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the occid of this occ new.
	 *
	 * @return the occid of this occ new
	 */
	public long getOCCID();

	/**
	 * Sets the occid of this occ new.
	 *
	 * @param OCCID the occid of this occ new
	 */
	public void setOCCID(long OCCID);

	/**
	 * Returns the list ID of this occ new.
	 *
	 * @return the list ID of this occ new
	 */
	public long getListID();

	/**
	 * Sets the list ID of this occ new.
	 *
	 * @param ListID the list ID of this occ new
	 */
	public void setListID(long ListID);

	/**
	 * Returns the list name of this occ new.
	 *
	 * @return the list name of this occ new
	 */
	@AutoEscape
	public String getListName();

	/**
	 * Sets the list name of this occ new.
	 *
	 * @param ListName the list name of this occ new
	 */
	public void setListName(String ListName);

	/**
	 * Returns the roll no of this occ new.
	 *
	 * @return the roll no of this occ new
	 */
	@AutoEscape
	public String getRollNo();

	/**
	 * Sets the roll no of this occ new.
	 *
	 * @param RollNo the roll no of this occ new
	 */
	public void setRollNo(String RollNo);

	/**
	 * Returns the name of this occ new.
	 *
	 * @return the name of this occ new
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this occ new.
	 *
	 * @param Name the name of this occ new
	 */
	public void setName(String Name);

	/**
	 * Returns the mobile no of this occ new.
	 *
	 * @return the mobile no of this occ new
	 */
	public long getMobileNo();

	/**
	 * Sets the mobile no of this occ new.
	 *
	 * @param MobileNo the mobile no of this occ new
	 */
	public void setMobileNo(long MobileNo);

	/**
	 * Returns the email of this occ new.
	 *
	 * @return the email of this occ new
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this occ new.
	 *
	 * @param Email the email of this occ new
	 */
	public void setEmail(String Email);

	/**
	 * Returns the dept of this occ new.
	 *
	 * @return the dept of this occ new
	 */
	@AutoEscape
	public String getDept();

	/**
	 * Sets the dept of this occ new.
	 *
	 * @param Dept the dept of this occ new
	 */
	public void setDept(String Dept);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(OCCModuleNew.model.OccNew occNew);

	@Override
	public int hashCode();

	@Override
	public CacheModel<OCCModuleNew.model.OccNew> toCacheModel();

	@Override
	public OCCModuleNew.model.OccNew toEscapedModel();

	@Override
	public OCCModuleNew.model.OccNew toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}