/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rinfra.annual.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the AnnualReport service. Represents a row in the &quot;FINANCIAL_REPORT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rinfra.annual.model.impl.AnnualReportModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rinfra.annual.model.impl.AnnualReportImpl}.
 * </p>
 *
 * @author MukeshPatidar
 * @see AnnualReport
 * @see com.rinfra.annual.model.impl.AnnualReportImpl
 * @see com.rinfra.annual.model.impl.AnnualReportModelImpl
 * @generated
 */
@ProviderType
public interface AnnualReportModel extends BaseModel<AnnualReport> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a annual report model instance should use the {@link AnnualReport} interface instead.
	 */

	/**
	 * Returns the primary key of this annual report.
	 *
	 * @return the primary key of this annual report
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this annual report.
	 *
	 * @param primaryKey the primary key of this annual report
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the srno of this annual report.
	 *
	 * @return the srno of this annual report
	 */
	public long getSRNO();

	/**
	 * Sets the srno of this annual report.
	 *
	 * @param SRNO the srno of this annual report
	 */
	public void setSRNO(long SRNO);

	/**
	 * Returns the financial_years of this annual report.
	 *
	 * @return the financial_years of this annual report
	 */
	@AutoEscape
	public String getFINANCIAL_YEARS();

	/**
	 * Sets the financial_years of this annual report.
	 *
	 * @param FINANCIAL_YEARS the financial_years of this annual report
	 */
	public void setFINANCIAL_YEARS(String FINANCIAL_YEARS);

	/**
	 * Returns the financialdata of this annual report.
	 *
	 * @return the financialdata of this annual report
	 */
	@AutoEscape
	public String getFINANCIALDATA();

	/**
	 * Sets the financialdata of this annual report.
	 *
	 * @param FINANCIALDATA the financialdata of this annual report
	 */
	public void setFINANCIALDATA(String FINANCIALDATA);

	/**
	 * Returns the financial_datalink of this annual report.
	 *
	 * @return the financial_datalink of this annual report
	 */
	@AutoEscape
	public String getFINANCIAL_DATALINK();

	/**
	 * Sets the financial_datalink of this annual report.
	 *
	 * @param FINANCIAL_DATALINK the financial_datalink of this annual report
	 */
	public void setFINANCIAL_DATALINK(String FINANCIAL_DATALINK);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AnnualReport annualReport);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AnnualReport> toCacheModel();

	@Override
	public AnnualReport toEscapedModel();

	@Override
	public AnnualReport toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}