/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rpower.unpaid.unclaimed.dividend.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RpowerUnpaidUnclaimedDevidend service. Represents a row in the &quot;RPOWER_UNPAIDUNCLAIMEDDIVIDEND&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rpower.unpaid.unclaimed.dividend.model.impl.RpowerUnpaidUnclaimedDevidendModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rpower.unpaid.unclaimed.dividend.model.impl.RpowerUnpaidUnclaimedDevidendImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RpowerUnpaidUnclaimedDevidend
 * @see com.rpower.unpaid.unclaimed.dividend.model.impl.RpowerUnpaidUnclaimedDevidendImpl
 * @see com.rpower.unpaid.unclaimed.dividend.model.impl.RpowerUnpaidUnclaimedDevidendModelImpl
 * @generated
 */
@ProviderType
public interface RpowerUnpaidUnclaimedDevidendModel extends BaseModel<RpowerUnpaidUnclaimedDevidend> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rpower unpaid unclaimed devidend model instance should use the {@link RpowerUnpaidUnclaimedDevidend} interface instead.
	 */

	/**
	 * Returns the primary key of this rpower unpaid unclaimed devidend.
	 *
	 * @return the primary key of this rpower unpaid unclaimed devidend
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rpower unpaid unclaimed devidend.
	 *
	 * @param primaryKey the primary key of this rpower unpaid unclaimed devidend
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the srno of this rpower unpaid unclaimed devidend.
	 *
	 * @return the srno of this rpower unpaid unclaimed devidend
	 */
	public long getSRNO();

	/**
	 * Sets the srno of this rpower unpaid unclaimed devidend.
	 *
	 * @param SRNO the srno of this rpower unpaid unclaimed devidend
	 */
	public void setSRNO(long SRNO);

	/**
	 * Returns the first_name of this rpower unpaid unclaimed devidend.
	 *
	 * @return the first_name of this rpower unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getFIRST_NAME();

	/**
	 * Sets the first_name of this rpower unpaid unclaimed devidend.
	 *
	 * @param FIRST_NAME the first_name of this rpower unpaid unclaimed devidend
	 */
	public void setFIRST_NAME(String FIRST_NAME);

	/**
	 * Returns the middle_name of this rpower unpaid unclaimed devidend.
	 *
	 * @return the middle_name of this rpower unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getMIDDLE_NAME();

	/**
	 * Sets the middle_name of this rpower unpaid unclaimed devidend.
	 *
	 * @param MIDDLE_NAME the middle_name of this rpower unpaid unclaimed devidend
	 */
	public void setMIDDLE_NAME(String MIDDLE_NAME);

	/**
	 * Returns the last_name of this rpower unpaid unclaimed devidend.
	 *
	 * @return the last_name of this rpower unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getLAST_NAME();

	/**
	 * Sets the last_name of this rpower unpaid unclaimed devidend.
	 *
	 * @param LAST_NAME the last_name of this rpower unpaid unclaimed devidend
	 */
	public void setLAST_NAME(String LAST_NAME);

	/**
	 * Returns the father_husband_first_name of this rpower unpaid unclaimed devidend.
	 *
	 * @return the father_husband_first_name of this rpower unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getFATHER_HUSBAND_FIRST_NAME();

	/**
	 * Sets the father_husband_first_name of this rpower unpaid unclaimed devidend.
	 *
	 * @param FATHER_HUSBAND_FIRST_NAME the father_husband_first_name of this rpower unpaid unclaimed devidend
	 */
	public void setFATHER_HUSBAND_FIRST_NAME(String FATHER_HUSBAND_FIRST_NAME);

	/**
	 * Returns the father_husband_middle_name of this rpower unpaid unclaimed devidend.
	 *
	 * @return the father_husband_middle_name of this rpower unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getFATHER_HUSBAND_MIDDLE_NAME();

	/**
	 * Sets the father_husband_middle_name of this rpower unpaid unclaimed devidend.
	 *
	 * @param FATHER_HUSBAND_MIDDLE_NAME the father_husband_middle_name of this rpower unpaid unclaimed devidend
	 */
	public void setFATHER_HUSBAND_MIDDLE_NAME(String FATHER_HUSBAND_MIDDLE_NAME);

	/**
	 * Returns the father_husband_last_name of this rpower unpaid unclaimed devidend.
	 *
	 * @return the father_husband_last_name of this rpower unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getFATHER_HUSBAND_LAST_NAME();

	/**
	 * Sets the father_husband_last_name of this rpower unpaid unclaimed devidend.
	 *
	 * @param FATHER_HUSBAND_LAST_NAME the father_husband_last_name of this rpower unpaid unclaimed devidend
	 */
	public void setFATHER_HUSBAND_LAST_NAME(String FATHER_HUSBAND_LAST_NAME);

	/**
	 * Returns the address of this rpower unpaid unclaimed devidend.
	 *
	 * @return the address of this rpower unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getADDRESS();

	/**
	 * Sets the address of this rpower unpaid unclaimed devidend.
	 *
	 * @param ADDRESS the address of this rpower unpaid unclaimed devidend
	 */
	public void setADDRESS(String ADDRESS);

	/**
	 * Returns the country of this rpower unpaid unclaimed devidend.
	 *
	 * @return the country of this rpower unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getCOUNTRY();

	/**
	 * Sets the country of this rpower unpaid unclaimed devidend.
	 *
	 * @param COUNTRY the country of this rpower unpaid unclaimed devidend
	 */
	public void setCOUNTRY(String COUNTRY);

	/**
	 * Returns the state of this rpower unpaid unclaimed devidend.
	 *
	 * @return the state of this rpower unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getSTATE();

	/**
	 * Sets the state of this rpower unpaid unclaimed devidend.
	 *
	 * @param STATE the state of this rpower unpaid unclaimed devidend
	 */
	public void setSTATE(String STATE);

	/**
	 * Returns the district of this rpower unpaid unclaimed devidend.
	 *
	 * @return the district of this rpower unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getDISTRICT();

	/**
	 * Sets the district of this rpower unpaid unclaimed devidend.
	 *
	 * @param DISTRICT the district of this rpower unpaid unclaimed devidend
	 */
	public void setDISTRICT(String DISTRICT);

	/**
	 * Returns the pin_code of this rpower unpaid unclaimed devidend.
	 *
	 * @return the pin_code of this rpower unpaid unclaimed devidend
	 */
	public long getPIN_CODE();

	/**
	 * Sets the pin_code of this rpower unpaid unclaimed devidend.
	 *
	 * @param PIN_CODE the pin_code of this rpower unpaid unclaimed devidend
	 */
	public void setPIN_CODE(long PIN_CODE);

	/**
	 * Returns the folio_no_of_ities of this rpower unpaid unclaimed devidend.
	 *
	 * @return the folio_no_of_ities of this rpower unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getFOLIO_NO_OF_ITIES();

	/**
	 * Sets the folio_no_of_ities of this rpower unpaid unclaimed devidend.
	 *
	 * @param FOLIO_NO_OF_ITIES the folio_no_of_ities of this rpower unpaid unclaimed devidend
	 */
	public void setFOLIO_NO_OF_ITIES(String FOLIO_NO_OF_ITIES);

	/**
	 * Returns the investment_type of this rpower unpaid unclaimed devidend.
	 *
	 * @return the investment_type of this rpower unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getINVESTMENT_TYPE();

	/**
	 * Sets the investment_type of this rpower unpaid unclaimed devidend.
	 *
	 * @param INVESTMENT_TYPE the investment_type of this rpower unpaid unclaimed devidend
	 */
	public void setINVESTMENT_TYPE(String INVESTMENT_TYPE);

	/**
	 * Returns the amount_due_in_rs of this rpower unpaid unclaimed devidend.
	 *
	 * @return the amount_due_in_rs of this rpower unpaid unclaimed devidend
	 */
	public double getAMOUNT_DUE_IN_RS();

	/**
	 * Sets the amount_due_in_rs of this rpower unpaid unclaimed devidend.
	 *
	 * @param AMOUNT_DUE_IN_RS the amount_due_in_rs of this rpower unpaid unclaimed devidend
	 */
	public void setAMOUNT_DUE_IN_RS(double AMOUNT_DUE_IN_RS);

	/**
	 * Returns the proposed_date_transfer_ipef of this rpower unpaid unclaimed devidend.
	 *
	 * @return the proposed_date_transfer_ipef of this rpower unpaid unclaimed devidend
	 */
	public Date getPROPOSED_DATE_TRANSFER_IPEF();

	/**
	 * Sets the proposed_date_transfer_ipef of this rpower unpaid unclaimed devidend.
	 *
	 * @param PROPOSED_DATE_TRANSFER_IPEF the proposed_date_transfer_ipef of this rpower unpaid unclaimed devidend
	 */
	public void setPROPOSED_DATE_TRANSFER_IPEF(Date PROPOSED_DATE_TRANSFER_IPEF);

	/**
	 * Returns the createdate of this rpower unpaid unclaimed devidend.
	 *
	 * @return the createdate of this rpower unpaid unclaimed devidend
	 */
	public Date getCREATEDATE();

	/**
	 * Sets the createdate of this rpower unpaid unclaimed devidend.
	 *
	 * @param CREATEDATE the createdate of this rpower unpaid unclaimed devidend
	 */
	public void setCREATEDATE(Date CREATEDATE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		RpowerUnpaidUnclaimedDevidend rpowerUnpaidUnclaimedDevidend);

	@Override
	public int hashCode();

	@Override
	public CacheModel<RpowerUnpaidUnclaimedDevidend> toCacheModel();

	@Override
	public RpowerUnpaidUnclaimedDevidend toEscapedModel();

	@Override
	public RpowerUnpaidUnclaimedDevidend toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}