##
## Properties Override
##

    #
    # Specify where to get the overridden properties. Updates should not be made
    # on this file but on the overridden version of this file.
    #
    include-and-override=${base.path}/service-ext.properties

##
## Build
##

    build.namespace=PRESS_RELEASE
    build.number=110
    build.date=1664254471311
    build.auto.upgrade=true