/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.metro.mediarelease.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import com.metro.mediarelease.model.MetroMediaRelease;
import com.metro.mediarelease.service.MetroMediaReleaseLocalService;
import com.metro.mediarelease.service.persistence.MetroMediaReleaseFinder;
import com.metro.mediarelease.service.persistence.MetroMediaReleasePersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the metro media release local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.metro.mediarelease.service.impl.MetroMediaReleaseLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.metro.mediarelease.service.impl.MetroMediaReleaseLocalServiceImpl
 * @see com.metro.mediarelease.service.MetroMediaReleaseLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class MetroMediaReleaseLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements MetroMediaReleaseLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.metro.mediarelease.service.MetroMediaReleaseLocalServiceUtil} to access the metro media release local service.
	 */

	/**
	 * Adds the metro media release to the database. Also notifies the appropriate model listeners.
	 *
	 * @param metroMediaRelease the metro media release
	 * @return the metro media release that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MetroMediaRelease addMetroMediaRelease(
		MetroMediaRelease metroMediaRelease) {
		metroMediaRelease.setNew(true);

		return metroMediaReleasePersistence.update(metroMediaRelease);
	}

	/**
	 * Creates a new metro media release with the primary key. Does not add the metro media release to the database.
	 *
	 * @param SRNO the primary key for the new metro media release
	 * @return the new metro media release
	 */
	@Override
	public MetroMediaRelease createMetroMediaRelease(long SRNO) {
		return metroMediaReleasePersistence.create(SRNO);
	}

	/**
	 * Deletes the metro media release with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param SRNO the primary key of the metro media release
	 * @return the metro media release that was removed
	 * @throws PortalException if a metro media release with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MetroMediaRelease deleteMetroMediaRelease(long SRNO)
		throws PortalException {
		return metroMediaReleasePersistence.remove(SRNO);
	}

	/**
	 * Deletes the metro media release from the database. Also notifies the appropriate model listeners.
	 *
	 * @param metroMediaRelease the metro media release
	 * @return the metro media release that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MetroMediaRelease deleteMetroMediaRelease(
		MetroMediaRelease metroMediaRelease) {
		return metroMediaReleasePersistence.remove(metroMediaRelease);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(MetroMediaRelease.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return metroMediaReleasePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.metro.mediarelease.model.impl.MetroMediaReleaseModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return metroMediaReleasePersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.metro.mediarelease.model.impl.MetroMediaReleaseModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return metroMediaReleasePersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return metroMediaReleasePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return metroMediaReleasePersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public MetroMediaRelease fetchMetroMediaRelease(long SRNO) {
		return metroMediaReleasePersistence.fetchByPrimaryKey(SRNO);
	}

	/**
	 * Returns the metro media release with the primary key.
	 *
	 * @param SRNO the primary key of the metro media release
	 * @return the metro media release
	 * @throws PortalException if a metro media release with the primary key could not be found
	 */
	@Override
	public MetroMediaRelease getMetroMediaRelease(long SRNO)
		throws PortalException {
		return metroMediaReleasePersistence.findByPrimaryKey(SRNO);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(metroMediaReleaseLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MetroMediaRelease.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("SRNO");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(metroMediaReleaseLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(MetroMediaRelease.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("SRNO");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(metroMediaReleaseLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MetroMediaRelease.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("SRNO");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return metroMediaReleaseLocalService.deleteMetroMediaRelease((MetroMediaRelease)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return metroMediaReleasePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the metro media releases.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.metro.mediarelease.model.impl.MetroMediaReleaseModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of metro media releases
	 * @param end the upper bound of the range of metro media releases (not inclusive)
	 * @return the range of metro media releases
	 */
	@Override
	public List<MetroMediaRelease> getMetroMediaReleases(int start, int end) {
		return metroMediaReleasePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of metro media releases.
	 *
	 * @return the number of metro media releases
	 */
	@Override
	public int getMetroMediaReleasesCount() {
		return metroMediaReleasePersistence.countAll();
	}

	/**
	 * Updates the metro media release in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param metroMediaRelease the metro media release
	 * @return the metro media release that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MetroMediaRelease updateMetroMediaRelease(
		MetroMediaRelease metroMediaRelease) {
		return metroMediaReleasePersistence.update(metroMediaRelease);
	}

	/**
	 * Returns the metro media release local service.
	 *
	 * @return the metro media release local service
	 */
	public MetroMediaReleaseLocalService getMetroMediaReleaseLocalService() {
		return metroMediaReleaseLocalService;
	}

	/**
	 * Sets the metro media release local service.
	 *
	 * @param metroMediaReleaseLocalService the metro media release local service
	 */
	public void setMetroMediaReleaseLocalService(
		MetroMediaReleaseLocalService metroMediaReleaseLocalService) {
		this.metroMediaReleaseLocalService = metroMediaReleaseLocalService;
	}

	/**
	 * Returns the metro media release persistence.
	 *
	 * @return the metro media release persistence
	 */
	public MetroMediaReleasePersistence getMetroMediaReleasePersistence() {
		return metroMediaReleasePersistence;
	}

	/**
	 * Sets the metro media release persistence.
	 *
	 * @param metroMediaReleasePersistence the metro media release persistence
	 */
	public void setMetroMediaReleasePersistence(
		MetroMediaReleasePersistence metroMediaReleasePersistence) {
		this.metroMediaReleasePersistence = metroMediaReleasePersistence;
	}

	/**
	 * Returns the metro media release finder.
	 *
	 * @return the metro media release finder
	 */
	public MetroMediaReleaseFinder getMetroMediaReleaseFinder() {
		return metroMediaReleaseFinder;
	}

	/**
	 * Sets the metro media release finder.
	 *
	 * @param metroMediaReleaseFinder the metro media release finder
	 */
	public void setMetroMediaReleaseFinder(
		MetroMediaReleaseFinder metroMediaReleaseFinder) {
		this.metroMediaReleaseFinder = metroMediaReleaseFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.metro.mediarelease.model.MetroMediaRelease",
			metroMediaReleaseLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.metro.mediarelease.model.MetroMediaRelease");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return MetroMediaReleaseLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return MetroMediaRelease.class;
	}

	protected String getModelClassName() {
		return MetroMediaRelease.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = metroMediaReleasePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = MetroMediaReleaseLocalService.class)
	protected MetroMediaReleaseLocalService metroMediaReleaseLocalService;
	@BeanReference(type = MetroMediaReleasePersistence.class)
	protected MetroMediaReleasePersistence metroMediaReleasePersistence;
	@BeanReference(type = MetroMediaReleaseFinder.class)
	protected MetroMediaReleaseFinder metroMediaReleaseFinder;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}