/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package OCCModuleNew.service.base;

import OCCModuleNew.model.OccNew;

import OCCModuleNew.service.OccNewLocalService;

import OCCModuleNew.service.persistence.OccMessageNewFinder;
import OCCModuleNew.service.persistence.OccMessageNewPersistence;
import OCCModuleNew.service.persistence.OccNewFinder;
import OCCModuleNew.service.persistence.OccNewPersistence;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the occ new local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link OCCModuleNew.service.impl.OccNewLocalServiceImpl}.
 * </p>
 *
 * @author Mukesh Patidar
 * @see OCCModuleNew.service.impl.OccNewLocalServiceImpl
 * @see OCCModuleNew.service.OccNewLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class OccNewLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements OccNewLocalService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link OCCModuleNew.service.OccNewLocalServiceUtil} to access the occ new local service.
	 */

	/**
	 * Adds the occ new to the database. Also notifies the appropriate model listeners.
	 *
	 * @param occNew the occ new
	 * @return the occ new that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public OccNew addOccNew(OccNew occNew) {
		occNew.setNew(true);

		return occNewPersistence.update(occNew);
	}

	/**
	 * Creates a new occ new with the primary key. Does not add the occ new to the database.
	 *
	 * @param OCCID the primary key for the new occ new
	 * @return the new occ new
	 */
	@Override
	public OccNew createOccNew(long OCCID) {
		return occNewPersistence.create(OCCID);
	}

	/**
	 * Deletes the occ new with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param OCCID the primary key of the occ new
	 * @return the occ new that was removed
	 * @throws PortalException if a occ new with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public OccNew deleteOccNew(long OCCID) throws PortalException {
		return occNewPersistence.remove(OCCID);
	}

	/**
	 * Deletes the occ new from the database. Also notifies the appropriate model listeners.
	 *
	 * @param occNew the occ new
	 * @return the occ new that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public OccNew deleteOccNew(OccNew occNew) {
		return occNewPersistence.remove(occNew);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(OccNew.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return occNewPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link OCCModuleNew.model.impl.OccNewModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return occNewPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link OCCModuleNew.model.impl.OccNewModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return occNewPersistence.findWithDynamicQuery(dynamicQuery, start, end,
			orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return occNewPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return occNewPersistence.countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public OccNew fetchOccNew(long OCCID) {
		return occNewPersistence.fetchByPrimaryKey(OCCID);
	}

	/**
	 * Returns the occ new with the primary key.
	 *
	 * @param OCCID the primary key of the occ new
	 * @return the occ new
	 * @throws PortalException if a occ new with the primary key could not be found
	 */
	@Override
	public OccNew getOccNew(long OCCID) throws PortalException {
		return occNewPersistence.findByPrimaryKey(OCCID);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(occNewLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(OccNew.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("OCCID");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(occNewLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(OccNew.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("OCCID");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(occNewLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(OccNew.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("OCCID");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return occNewLocalService.deleteOccNew((OccNew)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return occNewPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the occ news.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link OCCModuleNew.model.impl.OccNewModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of occ news
	 * @param end the upper bound of the range of occ news (not inclusive)
	 * @return the range of occ news
	 */
	@Override
	public List<OccNew> getOccNews(int start, int end) {
		return occNewPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of occ news.
	 *
	 * @return the number of occ news
	 */
	@Override
	public int getOccNewsCount() {
		return occNewPersistence.countAll();
	}

	/**
	 * Updates the occ new in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param occNew the occ new
	 * @return the occ new that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public OccNew updateOccNew(OccNew occNew) {
		return occNewPersistence.update(occNew);
	}

	/**
	 * Returns the occ message new local service.
	 *
	 * @return the occ message new local service
	 */
	public OCCModuleNew.service.OccMessageNewLocalService getOccMessageNewLocalService() {
		return occMessageNewLocalService;
	}

	/**
	 * Sets the occ message new local service.
	 *
	 * @param occMessageNewLocalService the occ message new local service
	 */
	public void setOccMessageNewLocalService(
		OCCModuleNew.service.OccMessageNewLocalService occMessageNewLocalService) {
		this.occMessageNewLocalService = occMessageNewLocalService;
	}

	/**
	 * Returns the occ message new persistence.
	 *
	 * @return the occ message new persistence
	 */
	public OccMessageNewPersistence getOccMessageNewPersistence() {
		return occMessageNewPersistence;
	}

	/**
	 * Sets the occ message new persistence.
	 *
	 * @param occMessageNewPersistence the occ message new persistence
	 */
	public void setOccMessageNewPersistence(
		OccMessageNewPersistence occMessageNewPersistence) {
		this.occMessageNewPersistence = occMessageNewPersistence;
	}

	/**
	 * Returns the occ message new finder.
	 *
	 * @return the occ message new finder
	 */
	public OccMessageNewFinder getOccMessageNewFinder() {
		return occMessageNewFinder;
	}

	/**
	 * Sets the occ message new finder.
	 *
	 * @param occMessageNewFinder the occ message new finder
	 */
	public void setOccMessageNewFinder(OccMessageNewFinder occMessageNewFinder) {
		this.occMessageNewFinder = occMessageNewFinder;
	}

	/**
	 * Returns the occ new local service.
	 *
	 * @return the occ new local service
	 */
	public OccNewLocalService getOccNewLocalService() {
		return occNewLocalService;
	}

	/**
	 * Sets the occ new local service.
	 *
	 * @param occNewLocalService the occ new local service
	 */
	public void setOccNewLocalService(OccNewLocalService occNewLocalService) {
		this.occNewLocalService = occNewLocalService;
	}

	/**
	 * Returns the occ new persistence.
	 *
	 * @return the occ new persistence
	 */
	public OccNewPersistence getOccNewPersistence() {
		return occNewPersistence;
	}

	/**
	 * Sets the occ new persistence.
	 *
	 * @param occNewPersistence the occ new persistence
	 */
	public void setOccNewPersistence(OccNewPersistence occNewPersistence) {
		this.occNewPersistence = occNewPersistence;
	}

	/**
	 * Returns the occ new finder.
	 *
	 * @return the occ new finder
	 */
	public OccNewFinder getOccNewFinder() {
		return occNewFinder;
	}

	/**
	 * Sets the occ new finder.
	 *
	 * @param occNewFinder the occ new finder
	 */
	public void setOccNewFinder(OccNewFinder occNewFinder) {
		this.occNewFinder = occNewFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("OCCModuleNew.model.OccNew",
			occNewLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"OCCModuleNew.model.OccNew");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return OccNewLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return OccNew.class;
	}

	protected String getModelClassName() {
		return OccNew.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = occNewPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = OCCModuleNew.service.OccMessageNewLocalService.class)
	protected OCCModuleNew.service.OccMessageNewLocalService occMessageNewLocalService;
	@BeanReference(type = OccMessageNewPersistence.class)
	protected OccMessageNewPersistence occMessageNewPersistence;
	@BeanReference(type = OccMessageNewFinder.class)
	protected OccMessageNewFinder occMessageNewFinder;
	@BeanReference(type = OccNewLocalService.class)
	protected OccNewLocalService occNewLocalService;
	@BeanReference(type = OccNewPersistence.class)
	protected OccNewPersistence occNewPersistence;
	@BeanReference(type = OccNewFinder.class)
	protected OccNewFinder occNewFinder;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}