/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.reliance.reality.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.reliance.reality.model.RealityPropertyMaster;
import com.reliance.reality.model.RealityPropertyMasterModel;
import com.reliance.reality.model.RealityPropertyMasterSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the RealityPropertyMaster service. Represents a row in the &quot;REALITY_PROPERTY_MSTR&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link RealityPropertyMasterModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RealityPropertyMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RealityPropertyMasterImpl
 * @see RealityPropertyMaster
 * @see RealityPropertyMasterModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class RealityPropertyMasterModelImpl extends BaseModelImpl<RealityPropertyMaster>
	implements RealityPropertyMasterModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a reality property master model instance should use the {@link RealityPropertyMaster} interface instead.
	 */
	public static final String TABLE_NAME = "REALITY_PROPERTY_MSTR";
	public static final Object[][] TABLE_COLUMNS = {
			{ "PROPERTY_ID", Types.BIGINT },
			{ "CITY", Types.VARCHAR },
			{ "LOCATION", Types.VARCHAR },
			{ "ADDRESS", Types.VARCHAR },
			{ "AREA", Types.VARCHAR },
			{ "TYPE", Types.VARCHAR },
			{ "GUIDANCEPRICE", Types.VARCHAR },
			{ "PROPERTYBID", Types.BIGINT },
			{ "OFFER_PRICE", Types.VARCHAR },
			{ "AGEOFPROPERTY", Types.VARCHAR },
			{ "CREATEDATE", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("PROPERTY_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CITY", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("LOCATION", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ADDRESS", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("AREA", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("TYPE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("GUIDANCEPRICE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("PROPERTYBID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("OFFER_PRICE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("AGEOFPROPERTY", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CREATEDATE", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table REALITY_PROPERTY_MSTR (PROPERTY_ID LONG not null primary key,CITY VARCHAR(75) null,LOCATION VARCHAR(75) null,ADDRESS VARCHAR(75) null,AREA VARCHAR(75) null,TYPE VARCHAR(75) null,GUIDANCEPRICE VARCHAR(75) null,PROPERTYBID LONG,OFFER_PRICE VARCHAR(75) null,AGEOFPROPERTY VARCHAR(75) null,CREATEDATE DATE null)";
	public static final String TABLE_SQL_DROP = "drop table REALITY_PROPERTY_MSTR";
	public static final String ORDER_BY_JPQL = " ORDER BY realityPropertyMaster.property_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY REALITY_PROPERTY_MSTR.PROPERTY_ID ASC";
	public static final String DATA_SOURCE = "extDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.reliance.reality.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.reliance.reality.model.RealityPropertyMaster"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.reliance.reality.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.reliance.reality.model.RealityPropertyMaster"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static RealityPropertyMaster toModel(
		RealityPropertyMasterSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		RealityPropertyMaster model = new RealityPropertyMasterImpl();

		model.setProperty_ID(soapModel.getProperty_ID());
		model.setCity(soapModel.getCity());
		model.setLocation(soapModel.getLocation());
		model.setAddress(soapModel.getAddress());
		model.setArea(soapModel.getArea());
		model.setType(soapModel.getType());
		model.setGuidancePrice(soapModel.getGuidancePrice());
		model.setPropertyBid(soapModel.getPropertyBid());
		model.setOfferPrice(soapModel.getOfferPrice());
		model.setAgeOfProperty(soapModel.getAgeOfProperty());
		model.setCreateDate(soapModel.getCreateDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<RealityPropertyMaster> toModels(
		RealityPropertyMasterSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<RealityPropertyMaster> models = new ArrayList<RealityPropertyMaster>(soapModels.length);

		for (RealityPropertyMasterSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.reliance.reality.service.util.ServiceProps.get(
				"lock.expiration.time.com.reliance.reality.model.RealityPropertyMaster"));

	public RealityPropertyMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _property_ID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProperty_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _property_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RealityPropertyMaster.class;
	}

	@Override
	public String getModelClassName() {
		return RealityPropertyMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("property_ID", getProperty_ID());
		attributes.put("city", getCity());
		attributes.put("location", getLocation());
		attributes.put("address", getAddress());
		attributes.put("area", getArea());
		attributes.put("type", getType());
		attributes.put("guidancePrice", getGuidancePrice());
		attributes.put("propertyBid", getPropertyBid());
		attributes.put("offerPrice", getOfferPrice());
		attributes.put("ageOfProperty", getAgeOfProperty());
		attributes.put("createDate", getCreateDate());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long property_ID = (Long)attributes.get("property_ID");

		if (property_ID != null) {
			setProperty_ID(property_ID);
		}

		String city = (String)attributes.get("city");

		if (city != null) {
			setCity(city);
		}

		String location = (String)attributes.get("location");

		if (location != null) {
			setLocation(location);
		}

		String address = (String)attributes.get("address");

		if (address != null) {
			setAddress(address);
		}

		String area = (String)attributes.get("area");

		if (area != null) {
			setArea(area);
		}

		String type = (String)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		String guidancePrice = (String)attributes.get("guidancePrice");

		if (guidancePrice != null) {
			setGuidancePrice(guidancePrice);
		}

		Long propertyBid = (Long)attributes.get("propertyBid");

		if (propertyBid != null) {
			setPropertyBid(propertyBid);
		}

		String offerPrice = (String)attributes.get("offerPrice");

		if (offerPrice != null) {
			setOfferPrice(offerPrice);
		}

		String ageOfProperty = (String)attributes.get("ageOfProperty");

		if (ageOfProperty != null) {
			setAgeOfProperty(ageOfProperty);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}
	}

	@JSON
	@Override
	public long getProperty_ID() {
		return _property_ID;
	}

	@Override
	public void setProperty_ID(long property_ID) {
		_property_ID = property_ID;
	}

	@JSON
	@Override
	public String getCity() {
		if (_city == null) {
			return StringPool.BLANK;
		}
		else {
			return _city;
		}
	}

	@Override
	public void setCity(String city) {
		_city = city;
	}

	@JSON
	@Override
	public String getLocation() {
		if (_location == null) {
			return StringPool.BLANK;
		}
		else {
			return _location;
		}
	}

	@Override
	public void setLocation(String location) {
		_location = location;
	}

	@JSON
	@Override
	public String getAddress() {
		if (_address == null) {
			return StringPool.BLANK;
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		_address = address;
	}

	@JSON
	@Override
	public String getArea() {
		if (_area == null) {
			return StringPool.BLANK;
		}
		else {
			return _area;
		}
	}

	@Override
	public void setArea(String area) {
		_area = area;
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return StringPool.BLANK;
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_type = type;
	}

	@JSON
	@Override
	public String getGuidancePrice() {
		if (_guidancePrice == null) {
			return StringPool.BLANK;
		}
		else {
			return _guidancePrice;
		}
	}

	@Override
	public void setGuidancePrice(String guidancePrice) {
		_guidancePrice = guidancePrice;
	}

	@JSON
	@Override
	public long getPropertyBid() {
		return _propertyBid;
	}

	@Override
	public void setPropertyBid(long propertyBid) {
		_propertyBid = propertyBid;
	}

	@JSON
	@Override
	public String getOfferPrice() {
		if (_offerPrice == null) {
			return StringPool.BLANK;
		}
		else {
			return _offerPrice;
		}
	}

	@Override
	public void setOfferPrice(String offerPrice) {
		_offerPrice = offerPrice;
	}

	@JSON
	@Override
	public String getAgeOfProperty() {
		if (_ageOfProperty == null) {
			return StringPool.BLANK;
		}
		else {
			return _ageOfProperty;
		}
	}

	@Override
	public void setAgeOfProperty(String ageOfProperty) {
		_ageOfProperty = ageOfProperty;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			RealityPropertyMaster.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RealityPropertyMaster toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (RealityPropertyMaster)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RealityPropertyMasterImpl realityPropertyMasterImpl = new RealityPropertyMasterImpl();

		realityPropertyMasterImpl.setProperty_ID(getProperty_ID());
		realityPropertyMasterImpl.setCity(getCity());
		realityPropertyMasterImpl.setLocation(getLocation());
		realityPropertyMasterImpl.setAddress(getAddress());
		realityPropertyMasterImpl.setArea(getArea());
		realityPropertyMasterImpl.setType(getType());
		realityPropertyMasterImpl.setGuidancePrice(getGuidancePrice());
		realityPropertyMasterImpl.setPropertyBid(getPropertyBid());
		realityPropertyMasterImpl.setOfferPrice(getOfferPrice());
		realityPropertyMasterImpl.setAgeOfProperty(getAgeOfProperty());
		realityPropertyMasterImpl.setCreateDate(getCreateDate());

		realityPropertyMasterImpl.resetOriginalValues();

		return realityPropertyMasterImpl;
	}

	@Override
	public int compareTo(RealityPropertyMaster realityPropertyMaster) {
		long primaryKey = realityPropertyMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof RealityPropertyMaster)) {
			return false;
		}

		RealityPropertyMaster realityPropertyMaster = (RealityPropertyMaster)obj;

		long primaryKey = realityPropertyMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<RealityPropertyMaster> toCacheModel() {
		RealityPropertyMasterCacheModel realityPropertyMasterCacheModel = new RealityPropertyMasterCacheModel();

		realityPropertyMasterCacheModel.property_ID = getProperty_ID();

		realityPropertyMasterCacheModel.city = getCity();

		String city = realityPropertyMasterCacheModel.city;

		if ((city != null) && (city.length() == 0)) {
			realityPropertyMasterCacheModel.city = null;
		}

		realityPropertyMasterCacheModel.location = getLocation();

		String location = realityPropertyMasterCacheModel.location;

		if ((location != null) && (location.length() == 0)) {
			realityPropertyMasterCacheModel.location = null;
		}

		realityPropertyMasterCacheModel.address = getAddress();

		String address = realityPropertyMasterCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			realityPropertyMasterCacheModel.address = null;
		}

		realityPropertyMasterCacheModel.area = getArea();

		String area = realityPropertyMasterCacheModel.area;

		if ((area != null) && (area.length() == 0)) {
			realityPropertyMasterCacheModel.area = null;
		}

		realityPropertyMasterCacheModel.type = getType();

		String type = realityPropertyMasterCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			realityPropertyMasterCacheModel.type = null;
		}

		realityPropertyMasterCacheModel.guidancePrice = getGuidancePrice();

		String guidancePrice = realityPropertyMasterCacheModel.guidancePrice;

		if ((guidancePrice != null) && (guidancePrice.length() == 0)) {
			realityPropertyMasterCacheModel.guidancePrice = null;
		}

		realityPropertyMasterCacheModel.propertyBid = getPropertyBid();

		realityPropertyMasterCacheModel.offerPrice = getOfferPrice();

		String offerPrice = realityPropertyMasterCacheModel.offerPrice;

		if ((offerPrice != null) && (offerPrice.length() == 0)) {
			realityPropertyMasterCacheModel.offerPrice = null;
		}

		realityPropertyMasterCacheModel.ageOfProperty = getAgeOfProperty();

		String ageOfProperty = realityPropertyMasterCacheModel.ageOfProperty;

		if ((ageOfProperty != null) && (ageOfProperty.length() == 0)) {
			realityPropertyMasterCacheModel.ageOfProperty = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			realityPropertyMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			realityPropertyMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		return realityPropertyMasterCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{property_ID=");
		sb.append(getProperty_ID());
		sb.append(", city=");
		sb.append(getCity());
		sb.append(", location=");
		sb.append(getLocation());
		sb.append(", address=");
		sb.append(getAddress());
		sb.append(", area=");
		sb.append(getArea());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", guidancePrice=");
		sb.append(getGuidancePrice());
		sb.append(", propertyBid=");
		sb.append(getPropertyBid());
		sb.append(", offerPrice=");
		sb.append(getOfferPrice());
		sb.append(", ageOfProperty=");
		sb.append(getAgeOfProperty());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.reliance.reality.model.RealityPropertyMaster");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>property_ID</column-name><column-value><![CDATA[");
		sb.append(getProperty_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>city</column-name><column-value><![CDATA[");
		sb.append(getCity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>location</column-name><column-value><![CDATA[");
		sb.append(getLocation());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>address</column-name><column-value><![CDATA[");
		sb.append(getAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>area</column-name><column-value><![CDATA[");
		sb.append(getArea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>guidancePrice</column-name><column-value><![CDATA[");
		sb.append(getGuidancePrice());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>propertyBid</column-name><column-value><![CDATA[");
		sb.append(getPropertyBid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>offerPrice</column-name><column-value><![CDATA[");
		sb.append(getOfferPrice());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ageOfProperty</column-name><column-value><![CDATA[");
		sb.append(getAgeOfProperty());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = RealityPropertyMaster.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			RealityPropertyMaster.class
		};
	private long _property_ID;
	private String _city;
	private String _location;
	private String _address;
	private String _area;
	private String _type;
	private String _guidancePrice;
	private long _propertyBid;
	private String _offerPrice;
	private String _ageOfProperty;
	private Date _createDate;
	private RealityPropertyMaster _escapedModel;
}