/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.reliance.reality.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.reliance.reality.model.RelianceReality;
import com.reliance.reality.model.RelianceRealityModel;
import com.reliance.reality.model.RelianceRealitySoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the RelianceReality service. Represents a row in the &quot;RELIANCE_REALITY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link RelianceRealityModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RelianceRealityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RelianceRealityImpl
 * @see RelianceReality
 * @see RelianceRealityModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class RelianceRealityModelImpl extends BaseModelImpl<RelianceReality>
	implements RelianceRealityModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a reliance reality model instance should use the {@link RelianceReality} interface instead.
	 */
	public static final String TABLE_NAME = "RELIANCE_REALITY";
	public static final Object[][] TABLE_COLUMNS = {
			{ "R_ID", Types.BIGINT },
			{ "CITY", Types.VARCHAR },
			{ "LOCATION", Types.VARCHAR },
			{ "ADDRESS", Types.VARCHAR },
			{ "AREA", Types.VARCHAR },
			{ "TYPE", Types.VARCHAR },
			{ "GUIDANCEPRICE", Types.BIGINT },
			{ "PROPERTY_ID", Types.VARCHAR },
			{ "OFFER_PRICE", Types.VARCHAR },
			{ "FUNDING", Types.VARCHAR },
			{ "DAYS", Types.BIGINT },
			{ "EMPCODE", Types.VARCHAR },
			{ "NAME", Types.VARCHAR },
			{ "EMAIL_ID", Types.VARCHAR },
			{ "MOBILE", Types.VARCHAR },
			{ "AGEOFPROPERTY", Types.VARCHAR },
			{ "GROUPCOMPANYNAME", Types.VARCHAR },
			{ "CREATEDATE", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("R_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CITY", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("LOCATION", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ADDRESS", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("AREA", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("TYPE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("GUIDANCEPRICE", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("PROPERTY_ID", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("OFFER_PRICE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FUNDING", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DAYS", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("EMPCODE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("EMAIL_ID", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MOBILE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("AGEOFPROPERTY", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("GROUPCOMPANYNAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CREATEDATE", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table RELIANCE_REALITY (R_ID LONG not null primary key,CITY VARCHAR(75) null,LOCATION VARCHAR(75) null,ADDRESS VARCHAR(75) null,AREA VARCHAR(75) null,TYPE VARCHAR(75) null,GUIDANCEPRICE LONG,PROPERTY_ID VARCHAR(75) null,OFFER_PRICE VARCHAR(75) null,FUNDING VARCHAR(75) null,DAYS LONG,EMPCODE VARCHAR(75) null,NAME VARCHAR(75) null,EMAIL_ID VARCHAR(75) null,MOBILE VARCHAR(75) null,AGEOFPROPERTY VARCHAR(75) null,GROUPCOMPANYNAME VARCHAR(75) null,CREATEDATE DATE null)";
	public static final String TABLE_SQL_DROP = "drop table RELIANCE_REALITY";
	public static final String ORDER_BY_JPQL = " ORDER BY relianceReality.r_Id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY RELIANCE_REALITY.R_ID ASC";
	public static final String DATA_SOURCE = "extDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.reliance.reality.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.reliance.reality.model.RelianceReality"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.reliance.reality.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.reliance.reality.model.RelianceReality"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static RelianceReality toModel(RelianceRealitySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		RelianceReality model = new RelianceRealityImpl();

		model.setR_Id(soapModel.getR_Id());
		model.setCity(soapModel.getCity());
		model.setLocation(soapModel.getLocation());
		model.setAddress(soapModel.getAddress());
		model.setArea(soapModel.getArea());
		model.setType(soapModel.getType());
		model.setGuidancePrice(soapModel.getGuidancePrice());
		model.setPropertyId(soapModel.getPropertyId());
		model.setOfferPrice(soapModel.getOfferPrice());
		model.setFunding(soapModel.getFunding());
		model.setDays(soapModel.getDays());
		model.setEmpcode(soapModel.getEmpcode());
		model.setName(soapModel.getName());
		model.setEmail_id(soapModel.getEmail_id());
		model.setMobile(soapModel.getMobile());
		model.setAgeOfProperty(soapModel.getAgeOfProperty());
		model.setGroupCompanyName(soapModel.getGroupCompanyName());
		model.setCreateDate(soapModel.getCreateDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<RelianceReality> toModels(
		RelianceRealitySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<RelianceReality> models = new ArrayList<RelianceReality>(soapModels.length);

		for (RelianceRealitySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.reliance.reality.service.util.ServiceProps.get(
				"lock.expiration.time.com.reliance.reality.model.RelianceReality"));

	public RelianceRealityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _r_Id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setR_Id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _r_Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RelianceReality.class;
	}

	@Override
	public String getModelClassName() {
		return RelianceReality.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("r_Id", getR_Id());
		attributes.put("city", getCity());
		attributes.put("location", getLocation());
		attributes.put("address", getAddress());
		attributes.put("area", getArea());
		attributes.put("type", getType());
		attributes.put("guidancePrice", getGuidancePrice());
		attributes.put("propertyId", getPropertyId());
		attributes.put("offerPrice", getOfferPrice());
		attributes.put("funding", getFunding());
		attributes.put("days", getDays());
		attributes.put("empcode", getEmpcode());
		attributes.put("name", getName());
		attributes.put("email_id", getEmail_id());
		attributes.put("mobile", getMobile());
		attributes.put("ageOfProperty", getAgeOfProperty());
		attributes.put("groupCompanyName", getGroupCompanyName());
		attributes.put("createDate", getCreateDate());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long r_Id = (Long)attributes.get("r_Id");

		if (r_Id != null) {
			setR_Id(r_Id);
		}

		String city = (String)attributes.get("city");

		if (city != null) {
			setCity(city);
		}

		String location = (String)attributes.get("location");

		if (location != null) {
			setLocation(location);
		}

		String address = (String)attributes.get("address");

		if (address != null) {
			setAddress(address);
		}

		String area = (String)attributes.get("area");

		if (area != null) {
			setArea(area);
		}

		String type = (String)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		Long guidancePrice = (Long)attributes.get("guidancePrice");

		if (guidancePrice != null) {
			setGuidancePrice(guidancePrice);
		}

		String propertyId = (String)attributes.get("propertyId");

		if (propertyId != null) {
			setPropertyId(propertyId);
		}

		String offerPrice = (String)attributes.get("offerPrice");

		if (offerPrice != null) {
			setOfferPrice(offerPrice);
		}

		String funding = (String)attributes.get("funding");

		if (funding != null) {
			setFunding(funding);
		}

		Long days = (Long)attributes.get("days");

		if (days != null) {
			setDays(days);
		}

		String empcode = (String)attributes.get("empcode");

		if (empcode != null) {
			setEmpcode(empcode);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String email_id = (String)attributes.get("email_id");

		if (email_id != null) {
			setEmail_id(email_id);
		}

		String mobile = (String)attributes.get("mobile");

		if (mobile != null) {
			setMobile(mobile);
		}

		String ageOfProperty = (String)attributes.get("ageOfProperty");

		if (ageOfProperty != null) {
			setAgeOfProperty(ageOfProperty);
		}

		String groupCompanyName = (String)attributes.get("groupCompanyName");

		if (groupCompanyName != null) {
			setGroupCompanyName(groupCompanyName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}
	}

	@JSON
	@Override
	public long getR_Id() {
		return _r_Id;
	}

	@Override
	public void setR_Id(long r_Id) {
		_r_Id = r_Id;
	}

	@JSON
	@Override
	public String getCity() {
		if (_city == null) {
			return StringPool.BLANK;
		}
		else {
			return _city;
		}
	}

	@Override
	public void setCity(String city) {
		_city = city;
	}

	@JSON
	@Override
	public String getLocation() {
		if (_location == null) {
			return StringPool.BLANK;
		}
		else {
			return _location;
		}
	}

	@Override
	public void setLocation(String location) {
		_location = location;
	}

	@JSON
	@Override
	public String getAddress() {
		if (_address == null) {
			return StringPool.BLANK;
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		_address = address;
	}

	@JSON
	@Override
	public String getArea() {
		if (_area == null) {
			return StringPool.BLANK;
		}
		else {
			return _area;
		}
	}

	@Override
	public void setArea(String area) {
		_area = area;
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return StringPool.BLANK;
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_type = type;
	}

	@JSON
	@Override
	public long getGuidancePrice() {
		return _guidancePrice;
	}

	@Override
	public void setGuidancePrice(long guidancePrice) {
		_guidancePrice = guidancePrice;
	}

	@JSON
	@Override
	public String getPropertyId() {
		if (_propertyId == null) {
			return StringPool.BLANK;
		}
		else {
			return _propertyId;
		}
	}

	@Override
	public void setPropertyId(String propertyId) {
		_propertyId = propertyId;
	}

	@JSON
	@Override
	public String getOfferPrice() {
		if (_offerPrice == null) {
			return StringPool.BLANK;
		}
		else {
			return _offerPrice;
		}
	}

	@Override
	public void setOfferPrice(String offerPrice) {
		_offerPrice = offerPrice;
	}

	@JSON
	@Override
	public String getFunding() {
		if (_funding == null) {
			return StringPool.BLANK;
		}
		else {
			return _funding;
		}
	}

	@Override
	public void setFunding(String funding) {
		_funding = funding;
	}

	@JSON
	@Override
	public long getDays() {
		return _days;
	}

	@Override
	public void setDays(long days) {
		_days = days;
	}

	@JSON
	@Override
	public String getEmpcode() {
		if (_empcode == null) {
			return StringPool.BLANK;
		}
		else {
			return _empcode;
		}
	}

	@Override
	public void setEmpcode(String empcode) {
		_empcode = empcode;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getEmail_id() {
		if (_email_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _email_id;
		}
	}

	@Override
	public void setEmail_id(String email_id) {
		_email_id = email_id;
	}

	@JSON
	@Override
	public String getMobile() {
		if (_mobile == null) {
			return StringPool.BLANK;
		}
		else {
			return _mobile;
		}
	}

	@Override
	public void setMobile(String mobile) {
		_mobile = mobile;
	}

	@JSON
	@Override
	public String getAgeOfProperty() {
		if (_ageOfProperty == null) {
			return StringPool.BLANK;
		}
		else {
			return _ageOfProperty;
		}
	}

	@Override
	public void setAgeOfProperty(String ageOfProperty) {
		_ageOfProperty = ageOfProperty;
	}

	@JSON
	@Override
	public String getGroupCompanyName() {
		if (_groupCompanyName == null) {
			return StringPool.BLANK;
		}
		else {
			return _groupCompanyName;
		}
	}

	@Override
	public void setGroupCompanyName(String groupCompanyName) {
		_groupCompanyName = groupCompanyName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			RelianceReality.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RelianceReality toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (RelianceReality)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RelianceRealityImpl relianceRealityImpl = new RelianceRealityImpl();

		relianceRealityImpl.setR_Id(getR_Id());
		relianceRealityImpl.setCity(getCity());
		relianceRealityImpl.setLocation(getLocation());
		relianceRealityImpl.setAddress(getAddress());
		relianceRealityImpl.setArea(getArea());
		relianceRealityImpl.setType(getType());
		relianceRealityImpl.setGuidancePrice(getGuidancePrice());
		relianceRealityImpl.setPropertyId(getPropertyId());
		relianceRealityImpl.setOfferPrice(getOfferPrice());
		relianceRealityImpl.setFunding(getFunding());
		relianceRealityImpl.setDays(getDays());
		relianceRealityImpl.setEmpcode(getEmpcode());
		relianceRealityImpl.setName(getName());
		relianceRealityImpl.setEmail_id(getEmail_id());
		relianceRealityImpl.setMobile(getMobile());
		relianceRealityImpl.setAgeOfProperty(getAgeOfProperty());
		relianceRealityImpl.setGroupCompanyName(getGroupCompanyName());
		relianceRealityImpl.setCreateDate(getCreateDate());

		relianceRealityImpl.resetOriginalValues();

		return relianceRealityImpl;
	}

	@Override
	public int compareTo(RelianceReality relianceReality) {
		long primaryKey = relianceReality.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof RelianceReality)) {
			return false;
		}

		RelianceReality relianceReality = (RelianceReality)obj;

		long primaryKey = relianceReality.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<RelianceReality> toCacheModel() {
		RelianceRealityCacheModel relianceRealityCacheModel = new RelianceRealityCacheModel();

		relianceRealityCacheModel.r_Id = getR_Id();

		relianceRealityCacheModel.city = getCity();

		String city = relianceRealityCacheModel.city;

		if ((city != null) && (city.length() == 0)) {
			relianceRealityCacheModel.city = null;
		}

		relianceRealityCacheModel.location = getLocation();

		String location = relianceRealityCacheModel.location;

		if ((location != null) && (location.length() == 0)) {
			relianceRealityCacheModel.location = null;
		}

		relianceRealityCacheModel.address = getAddress();

		String address = relianceRealityCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			relianceRealityCacheModel.address = null;
		}

		relianceRealityCacheModel.area = getArea();

		String area = relianceRealityCacheModel.area;

		if ((area != null) && (area.length() == 0)) {
			relianceRealityCacheModel.area = null;
		}

		relianceRealityCacheModel.type = getType();

		String type = relianceRealityCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			relianceRealityCacheModel.type = null;
		}

		relianceRealityCacheModel.guidancePrice = getGuidancePrice();

		relianceRealityCacheModel.propertyId = getPropertyId();

		String propertyId = relianceRealityCacheModel.propertyId;

		if ((propertyId != null) && (propertyId.length() == 0)) {
			relianceRealityCacheModel.propertyId = null;
		}

		relianceRealityCacheModel.offerPrice = getOfferPrice();

		String offerPrice = relianceRealityCacheModel.offerPrice;

		if ((offerPrice != null) && (offerPrice.length() == 0)) {
			relianceRealityCacheModel.offerPrice = null;
		}

		relianceRealityCacheModel.funding = getFunding();

		String funding = relianceRealityCacheModel.funding;

		if ((funding != null) && (funding.length() == 0)) {
			relianceRealityCacheModel.funding = null;
		}

		relianceRealityCacheModel.days = getDays();

		relianceRealityCacheModel.empcode = getEmpcode();

		String empcode = relianceRealityCacheModel.empcode;

		if ((empcode != null) && (empcode.length() == 0)) {
			relianceRealityCacheModel.empcode = null;
		}

		relianceRealityCacheModel.name = getName();

		String name = relianceRealityCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			relianceRealityCacheModel.name = null;
		}

		relianceRealityCacheModel.email_id = getEmail_id();

		String email_id = relianceRealityCacheModel.email_id;

		if ((email_id != null) && (email_id.length() == 0)) {
			relianceRealityCacheModel.email_id = null;
		}

		relianceRealityCacheModel.mobile = getMobile();

		String mobile = relianceRealityCacheModel.mobile;

		if ((mobile != null) && (mobile.length() == 0)) {
			relianceRealityCacheModel.mobile = null;
		}

		relianceRealityCacheModel.ageOfProperty = getAgeOfProperty();

		String ageOfProperty = relianceRealityCacheModel.ageOfProperty;

		if ((ageOfProperty != null) && (ageOfProperty.length() == 0)) {
			relianceRealityCacheModel.ageOfProperty = null;
		}

		relianceRealityCacheModel.groupCompanyName = getGroupCompanyName();

		String groupCompanyName = relianceRealityCacheModel.groupCompanyName;

		if ((groupCompanyName != null) && (groupCompanyName.length() == 0)) {
			relianceRealityCacheModel.groupCompanyName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			relianceRealityCacheModel.createDate = createDate.getTime();
		}
		else {
			relianceRealityCacheModel.createDate = Long.MIN_VALUE;
		}

		return relianceRealityCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(37);

		sb.append("{r_Id=");
		sb.append(getR_Id());
		sb.append(", city=");
		sb.append(getCity());
		sb.append(", location=");
		sb.append(getLocation());
		sb.append(", address=");
		sb.append(getAddress());
		sb.append(", area=");
		sb.append(getArea());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", guidancePrice=");
		sb.append(getGuidancePrice());
		sb.append(", propertyId=");
		sb.append(getPropertyId());
		sb.append(", offerPrice=");
		sb.append(getOfferPrice());
		sb.append(", funding=");
		sb.append(getFunding());
		sb.append(", days=");
		sb.append(getDays());
		sb.append(", empcode=");
		sb.append(getEmpcode());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", email_id=");
		sb.append(getEmail_id());
		sb.append(", mobile=");
		sb.append(getMobile());
		sb.append(", ageOfProperty=");
		sb.append(getAgeOfProperty());
		sb.append(", groupCompanyName=");
		sb.append(getGroupCompanyName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(58);

		sb.append("<model><model-name>");
		sb.append("com.reliance.reality.model.RelianceReality");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>r_Id</column-name><column-value><![CDATA[");
		sb.append(getR_Id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>city</column-name><column-value><![CDATA[");
		sb.append(getCity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>location</column-name><column-value><![CDATA[");
		sb.append(getLocation());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>address</column-name><column-value><![CDATA[");
		sb.append(getAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>area</column-name><column-value><![CDATA[");
		sb.append(getArea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>guidancePrice</column-name><column-value><![CDATA[");
		sb.append(getGuidancePrice());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>propertyId</column-name><column-value><![CDATA[");
		sb.append(getPropertyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>offerPrice</column-name><column-value><![CDATA[");
		sb.append(getOfferPrice());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>funding</column-name><column-value><![CDATA[");
		sb.append(getFunding());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>days</column-name><column-value><![CDATA[");
		sb.append(getDays());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>empcode</column-name><column-value><![CDATA[");
		sb.append(getEmpcode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email_id</column-name><column-value><![CDATA[");
		sb.append(getEmail_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mobile</column-name><column-value><![CDATA[");
		sb.append(getMobile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ageOfProperty</column-name><column-value><![CDATA[");
		sb.append(getAgeOfProperty());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupCompanyName</column-name><column-value><![CDATA[");
		sb.append(getGroupCompanyName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = RelianceReality.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			RelianceReality.class
		};
	private long _r_Id;
	private String _city;
	private String _location;
	private String _address;
	private String _area;
	private String _type;
	private long _guidancePrice;
	private String _propertyId;
	private String _offerPrice;
	private String _funding;
	private long _days;
	private String _empcode;
	private String _name;
	private String _email_id;
	private String _mobile;
	private String _ageOfProperty;
	private String _groupCompanyName;
	private Date _createDate;
	private RelianceReality _escapedModel;
}