/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.newrpower.share.doc.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.newrpower.share.doc.model.RpowerShareHolders;
import com.newrpower.share.doc.model.RpowerShareHoldersModel;
import com.newrpower.share.doc.model.RpowerShareHoldersSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the RpowerShareHolders service. Represents a row in the &quot;RPOWER_SHARE_HOLDERS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link RpowerShareHoldersModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RpowerShareHoldersImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RpowerShareHoldersImpl
 * @see RpowerShareHolders
 * @see RpowerShareHoldersModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class RpowerShareHoldersModelImpl extends BaseModelImpl<RpowerShareHolders>
	implements RpowerShareHoldersModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rpower share holders model instance should use the {@link RpowerShareHolders} interface instead.
	 */
	public static final String TABLE_NAME = "RPOWER_SHARE_HOLDERS";
	public static final Object[][] TABLE_COLUMNS = {
			{ "SRNO", Types.BIGINT },
			{ "FOLIO_NO", Types.VARCHAR },
			{ "SHARES", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("SRNO", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FOLIO_NO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("SHARES", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table RPOWER_SHARE_HOLDERS (SRNO LONG,FOLIO_NO VARCHAR(75) not null primary key,SHARES VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table RPOWER_SHARE_HOLDERS";
	public static final String ORDER_BY_JPQL = " ORDER BY rpowerShareHolders.FOLIO_NO ASC";
	public static final String ORDER_BY_SQL = " ORDER BY RPOWER_SHARE_HOLDERS.FOLIO_NO ASC";
	public static final String DATA_SOURCE = "extDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.newrpower.share.doc.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.newrpower.share.doc.model.RpowerShareHolders"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.newrpower.share.doc.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.newrpower.share.doc.model.RpowerShareHolders"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static RpowerShareHolders toModel(RpowerShareHoldersSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		RpowerShareHolders model = new RpowerShareHoldersImpl();

		model.setSRNO(soapModel.getSRNO());
		model.setFOLIO_NO(soapModel.getFOLIO_NO());
		model.setSHARES(soapModel.getSHARES());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<RpowerShareHolders> toModels(
		RpowerShareHoldersSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<RpowerShareHolders> models = new ArrayList<RpowerShareHolders>(soapModels.length);

		for (RpowerShareHoldersSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.newrpower.share.doc.service.util.ServiceProps.get(
				"lock.expiration.time.com.newrpower.share.doc.model.RpowerShareHolders"));

	public RpowerShareHoldersModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _FOLIO_NO;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setFOLIO_NO(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _FOLIO_NO;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return RpowerShareHolders.class;
	}

	@Override
	public String getModelClassName() {
		return RpowerShareHolders.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("SRNO", getSRNO());
		attributes.put("FOLIO_NO", getFOLIO_NO());
		attributes.put("SHARES", getSHARES());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long SRNO = (Long)attributes.get("SRNO");

		if (SRNO != null) {
			setSRNO(SRNO);
		}

		String FOLIO_NO = (String)attributes.get("FOLIO_NO");

		if (FOLIO_NO != null) {
			setFOLIO_NO(FOLIO_NO);
		}

		String SHARES = (String)attributes.get("SHARES");

		if (SHARES != null) {
			setSHARES(SHARES);
		}
	}

	@JSON
	@Override
	public long getSRNO() {
		return _SRNO;
	}

	@Override
	public void setSRNO(long SRNO) {
		_SRNO = SRNO;
	}

	@JSON
	@Override
	public String getFOLIO_NO() {
		if (_FOLIO_NO == null) {
			return StringPool.BLANK;
		}
		else {
			return _FOLIO_NO;
		}
	}

	@Override
	public void setFOLIO_NO(String FOLIO_NO) {
		_FOLIO_NO = FOLIO_NO;
	}

	@JSON
	@Override
	public String getSHARES() {
		if (_SHARES == null) {
			return StringPool.BLANK;
		}
		else {
			return _SHARES;
		}
	}

	@Override
	public void setSHARES(String SHARES) {
		_SHARES = SHARES;
	}

	@Override
	public RpowerShareHolders toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (RpowerShareHolders)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RpowerShareHoldersImpl rpowerShareHoldersImpl = new RpowerShareHoldersImpl();

		rpowerShareHoldersImpl.setSRNO(getSRNO());
		rpowerShareHoldersImpl.setFOLIO_NO(getFOLIO_NO());
		rpowerShareHoldersImpl.setSHARES(getSHARES());

		rpowerShareHoldersImpl.resetOriginalValues();

		return rpowerShareHoldersImpl;
	}

	@Override
	public int compareTo(RpowerShareHolders rpowerShareHolders) {
		String primaryKey = rpowerShareHolders.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof RpowerShareHolders)) {
			return false;
		}

		RpowerShareHolders rpowerShareHolders = (RpowerShareHolders)obj;

		String primaryKey = rpowerShareHolders.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<RpowerShareHolders> toCacheModel() {
		RpowerShareHoldersCacheModel rpowerShareHoldersCacheModel = new RpowerShareHoldersCacheModel();

		rpowerShareHoldersCacheModel.SRNO = getSRNO();

		rpowerShareHoldersCacheModel.FOLIO_NO = getFOLIO_NO();

		String FOLIO_NO = rpowerShareHoldersCacheModel.FOLIO_NO;

		if ((FOLIO_NO != null) && (FOLIO_NO.length() == 0)) {
			rpowerShareHoldersCacheModel.FOLIO_NO = null;
		}

		rpowerShareHoldersCacheModel.SHARES = getSHARES();

		String SHARES = rpowerShareHoldersCacheModel.SHARES;

		if ((SHARES != null) && (SHARES.length() == 0)) {
			rpowerShareHoldersCacheModel.SHARES = null;
		}

		return rpowerShareHoldersCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{SRNO=");
		sb.append(getSRNO());
		sb.append(", FOLIO_NO=");
		sb.append(getFOLIO_NO());
		sb.append(", SHARES=");
		sb.append(getSHARES());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.newrpower.share.doc.model.RpowerShareHolders");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>SRNO</column-name><column-value><![CDATA[");
		sb.append(getSRNO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FOLIO_NO</column-name><column-value><![CDATA[");
		sb.append(getFOLIO_NO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SHARES</column-name><column-value><![CDATA[");
		sb.append(getSHARES());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = RpowerShareHolders.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			RpowerShareHolders.class
		};
	private long _SRNO;
	private String _FOLIO_NO;
	private String _SHARES;
	private RpowerShareHolders _escapedModel;
}