/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.newrpower.share.doc.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.newrpower.share.doc.model.ShareHoldersDoc;
import com.newrpower.share.doc.model.ShareHoldersDocModel;
import com.newrpower.share.doc.model.ShareHoldersDocSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ShareHoldersDoc service. Represents a row in the &quot;SHARE_HOLDERS_DOC&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ShareHoldersDocModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ShareHoldersDocImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ShareHoldersDocImpl
 * @see ShareHoldersDoc
 * @see ShareHoldersDocModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ShareHoldersDocModelImpl extends BaseModelImpl<ShareHoldersDoc>
	implements ShareHoldersDocModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a share holders doc model instance should use the {@link ShareHoldersDoc} interface instead.
	 */
	public static final String TABLE_NAME = "SHARE_HOLDERS_DOC";
	public static final Object[][] TABLE_COLUMNS = {
			{ "pressId", Types.BIGINT },
			{ "heading", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "fileURL", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("pressId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("heading", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileURL", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table SHARE_HOLDERS_DOC (pressId LONG not null primary key,heading VARCHAR(75) null,description VARCHAR(75) null,fileURL VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table SHARE_HOLDERS_DOC";
	public static final String ORDER_BY_JPQL = " ORDER BY shareHoldersDoc.pressId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SHARE_HOLDERS_DOC.pressId ASC";
	public static final String DATA_SOURCE = "extDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.newrpower.share.doc.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.newrpower.share.doc.model.ShareHoldersDoc"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.newrpower.share.doc.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.newrpower.share.doc.model.ShareHoldersDoc"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ShareHoldersDoc toModel(ShareHoldersDocSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ShareHoldersDoc model = new ShareHoldersDocImpl();

		model.setPressId(soapModel.getPressId());
		model.setHeading(soapModel.getHeading());
		model.setDescription(soapModel.getDescription());
		model.setFileURL(soapModel.getFileURL());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ShareHoldersDoc> toModels(
		ShareHoldersDocSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ShareHoldersDoc> models = new ArrayList<ShareHoldersDoc>(soapModels.length);

		for (ShareHoldersDocSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.newrpower.share.doc.service.util.ServiceProps.get(
				"lock.expiration.time.com.newrpower.share.doc.model.ShareHoldersDoc"));

	public ShareHoldersDocModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _pressId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPressId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _pressId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ShareHoldersDoc.class;
	}

	@Override
	public String getModelClassName() {
		return ShareHoldersDoc.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("pressId", getPressId());
		attributes.put("heading", getHeading());
		attributes.put("description", getDescription());
		attributes.put("fileURL", getFileURL());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long pressId = (Long)attributes.get("pressId");

		if (pressId != null) {
			setPressId(pressId);
		}

		String heading = (String)attributes.get("heading");

		if (heading != null) {
			setHeading(heading);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String fileURL = (String)attributes.get("fileURL");

		if (fileURL != null) {
			setFileURL(fileURL);
		}
	}

	@JSON
	@Override
	public long getPressId() {
		return _pressId;
	}

	@Override
	public void setPressId(long pressId) {
		_pressId = pressId;
	}

	@JSON
	@Override
	public String getHeading() {
		if (_heading == null) {
			return StringPool.BLANK;
		}
		else {
			return _heading;
		}
	}

	@Override
	public void setHeading(String heading) {
		_heading = heading;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public String getFileURL() {
		if (_fileURL == null) {
			return StringPool.BLANK;
		}
		else {
			return _fileURL;
		}
	}

	@Override
	public void setFileURL(String fileURL) {
		_fileURL = fileURL;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ShareHoldersDoc.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ShareHoldersDoc toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ShareHoldersDoc)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ShareHoldersDocImpl shareHoldersDocImpl = new ShareHoldersDocImpl();

		shareHoldersDocImpl.setPressId(getPressId());
		shareHoldersDocImpl.setHeading(getHeading());
		shareHoldersDocImpl.setDescription(getDescription());
		shareHoldersDocImpl.setFileURL(getFileURL());

		shareHoldersDocImpl.resetOriginalValues();

		return shareHoldersDocImpl;
	}

	@Override
	public int compareTo(ShareHoldersDoc shareHoldersDoc) {
		long primaryKey = shareHoldersDoc.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ShareHoldersDoc)) {
			return false;
		}

		ShareHoldersDoc shareHoldersDoc = (ShareHoldersDoc)obj;

		long primaryKey = shareHoldersDoc.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<ShareHoldersDoc> toCacheModel() {
		ShareHoldersDocCacheModel shareHoldersDocCacheModel = new ShareHoldersDocCacheModel();

		shareHoldersDocCacheModel.pressId = getPressId();

		shareHoldersDocCacheModel.heading = getHeading();

		String heading = shareHoldersDocCacheModel.heading;

		if ((heading != null) && (heading.length() == 0)) {
			shareHoldersDocCacheModel.heading = null;
		}

		shareHoldersDocCacheModel.description = getDescription();

		String description = shareHoldersDocCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			shareHoldersDocCacheModel.description = null;
		}

		shareHoldersDocCacheModel.fileURL = getFileURL();

		String fileURL = shareHoldersDocCacheModel.fileURL;

		if ((fileURL != null) && (fileURL.length() == 0)) {
			shareHoldersDocCacheModel.fileURL = null;
		}

		return shareHoldersDocCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{pressId=");
		sb.append(getPressId());
		sb.append(", heading=");
		sb.append(getHeading());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", fileURL=");
		sb.append(getFileURL());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.newrpower.share.doc.model.ShareHoldersDoc");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>pressId</column-name><column-value><![CDATA[");
		sb.append(getPressId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>heading</column-name><column-value><![CDATA[");
		sb.append(getHeading());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileURL</column-name><column-value><![CDATA[");
		sb.append(getFileURL());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ShareHoldersDoc.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ShareHoldersDoc.class
		};
	private long _pressId;
	private String _heading;
	private String _description;
	private String _fileURL;
	private ShareHoldersDoc _escapedModel;
}