/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.media.query.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.media.query.model.MediaQuery;
import com.media.query.model.MediaQueryModel;
import com.media.query.model.MediaQuerySoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the MediaQuery service. Represents a row in the &quot;MEDIA_QUERY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link MediaQueryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MediaQueryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MediaQueryImpl
 * @see MediaQuery
 * @see MediaQueryModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class MediaQueryModelImpl extends BaseModelImpl<MediaQuery>
	implements MediaQueryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a media query model instance should use the {@link MediaQuery} interface instead.
	 */
	public static final String TABLE_NAME = "MEDIA_QUERY";
	public static final Object[][] TABLE_COLUMNS = {
			{ "SR_NO", Types.BIGINT },
			{ "JOURNALIST_NAME", Types.VARCHAR },
			{ "ORGANISATION_NAME", Types.VARCHAR },
			{ "ORGANISATION_TYPE", Types.VARCHAR },
			{ "MOBILE", Types.VARCHAR },
			{ "EMAIL", Types.VARCHAR },
			{ "SUBJECT", Types.VARCHAR },
			{ "MEDIAQUERY", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("SR_NO", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("JOURNALIST_NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ORGANISATION_NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ORGANISATION_TYPE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MOBILE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("EMAIL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("SUBJECT", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MEDIAQUERY", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table MEDIA_QUERY (SR_NO LONG not null primary key,JOURNALIST_NAME VARCHAR(75) null,ORGANISATION_NAME VARCHAR(75) null,ORGANISATION_TYPE VARCHAR(75) null,MOBILE VARCHAR(75) null,EMAIL VARCHAR(75) null,SUBJECT VARCHAR(75) null,MEDIAQUERY VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table MEDIA_QUERY";
	public static final String ORDER_BY_JPQL = " ORDER BY mediaQuery.srNo ASC";
	public static final String ORDER_BY_SQL = " ORDER BY MEDIA_QUERY.SR_NO ASC";
	public static final String DATA_SOURCE = "extDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.media.query.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.media.query.model.MediaQuery"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.media.query.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.media.query.model.MediaQuery"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static MediaQuery toModel(MediaQuerySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MediaQuery model = new MediaQueryImpl();

		model.setSrNo(soapModel.getSrNo());
		model.setJournalistName(soapModel.getJournalistName());
		model.setNewsOrganisationName(soapModel.getNewsOrganisationName());
		model.setOrganisationType(soapModel.getOrganisationType());
		model.setMobile(soapModel.getMobile());
		model.setEmail(soapModel.getEmail());
		model.setSubject(soapModel.getSubject());
		model.setMediaQuery(soapModel.getMediaQuery());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<MediaQuery> toModels(MediaQuerySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MediaQuery> models = new ArrayList<MediaQuery>(soapModels.length);

		for (MediaQuerySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.media.query.service.util.ServiceProps.get(
				"lock.expiration.time.com.media.query.model.MediaQuery"));

	public MediaQueryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _srNo;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSrNo(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _srNo;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MediaQuery.class;
	}

	@Override
	public String getModelClassName() {
		return MediaQuery.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("srNo", getSrNo());
		attributes.put("journalistName", getJournalistName());
		attributes.put("newsOrganisationName", getNewsOrganisationName());
		attributes.put("organisationType", getOrganisationType());
		attributes.put("mobile", getMobile());
		attributes.put("email", getEmail());
		attributes.put("subject", getSubject());
		attributes.put("mediaQuery", getMediaQuery());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long srNo = (Long)attributes.get("srNo");

		if (srNo != null) {
			setSrNo(srNo);
		}

		String journalistName = (String)attributes.get("journalistName");

		if (journalistName != null) {
			setJournalistName(journalistName);
		}

		String newsOrganisationName = (String)attributes.get(
				"newsOrganisationName");

		if (newsOrganisationName != null) {
			setNewsOrganisationName(newsOrganisationName);
		}

		String organisationType = (String)attributes.get("organisationType");

		if (organisationType != null) {
			setOrganisationType(organisationType);
		}

		String mobile = (String)attributes.get("mobile");

		if (mobile != null) {
			setMobile(mobile);
		}

		String email = (String)attributes.get("email");

		if (email != null) {
			setEmail(email);
		}

		String subject = (String)attributes.get("subject");

		if (subject != null) {
			setSubject(subject);
		}

		String mediaQuery = (String)attributes.get("mediaQuery");

		if (mediaQuery != null) {
			setMediaQuery(mediaQuery);
		}
	}

	@JSON
	@Override
	public long getSrNo() {
		return _srNo;
	}

	@Override
	public void setSrNo(long srNo) {
		_srNo = srNo;
	}

	@JSON
	@Override
	public String getJournalistName() {
		if (_journalistName == null) {
			return StringPool.BLANK;
		}
		else {
			return _journalistName;
		}
	}

	@Override
	public void setJournalistName(String journalistName) {
		_journalistName = journalistName;
	}

	@JSON
	@Override
	public String getNewsOrganisationName() {
		if (_newsOrganisationName == null) {
			return StringPool.BLANK;
		}
		else {
			return _newsOrganisationName;
		}
	}

	@Override
	public void setNewsOrganisationName(String newsOrganisationName) {
		_newsOrganisationName = newsOrganisationName;
	}

	@JSON
	@Override
	public String getOrganisationType() {
		if (_organisationType == null) {
			return StringPool.BLANK;
		}
		else {
			return _organisationType;
		}
	}

	@Override
	public void setOrganisationType(String organisationType) {
		_organisationType = organisationType;
	}

	@JSON
	@Override
	public String getMobile() {
		if (_mobile == null) {
			return StringPool.BLANK;
		}
		else {
			return _mobile;
		}
	}

	@Override
	public void setMobile(String mobile) {
		_mobile = mobile;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		_email = email;
	}

	@JSON
	@Override
	public String getSubject() {
		if (_subject == null) {
			return StringPool.BLANK;
		}
		else {
			return _subject;
		}
	}

	@Override
	public void setSubject(String subject) {
		_subject = subject;
	}

	@JSON
	@Override
	public String getMediaQuery() {
		if (_mediaQuery == null) {
			return StringPool.BLANK;
		}
		else {
			return _mediaQuery;
		}
	}

	@Override
	public void setMediaQuery(String mediaQuery) {
		_mediaQuery = mediaQuery;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			MediaQuery.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MediaQuery toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MediaQuery)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MediaQueryImpl mediaQueryImpl = new MediaQueryImpl();

		mediaQueryImpl.setSrNo(getSrNo());
		mediaQueryImpl.setJournalistName(getJournalistName());
		mediaQueryImpl.setNewsOrganisationName(getNewsOrganisationName());
		mediaQueryImpl.setOrganisationType(getOrganisationType());
		mediaQueryImpl.setMobile(getMobile());
		mediaQueryImpl.setEmail(getEmail());
		mediaQueryImpl.setSubject(getSubject());
		mediaQueryImpl.setMediaQuery(getMediaQuery());

		mediaQueryImpl.resetOriginalValues();

		return mediaQueryImpl;
	}

	@Override
	public int compareTo(MediaQuery mediaQuery) {
		long primaryKey = mediaQuery.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MediaQuery)) {
			return false;
		}

		MediaQuery mediaQuery = (MediaQuery)obj;

		long primaryKey = mediaQuery.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<MediaQuery> toCacheModel() {
		MediaQueryCacheModel mediaQueryCacheModel = new MediaQueryCacheModel();

		mediaQueryCacheModel.srNo = getSrNo();

		mediaQueryCacheModel.journalistName = getJournalistName();

		String journalistName = mediaQueryCacheModel.journalistName;

		if ((journalistName != null) && (journalistName.length() == 0)) {
			mediaQueryCacheModel.journalistName = null;
		}

		mediaQueryCacheModel.newsOrganisationName = getNewsOrganisationName();

		String newsOrganisationName = mediaQueryCacheModel.newsOrganisationName;

		if ((newsOrganisationName != null) &&
				(newsOrganisationName.length() == 0)) {
			mediaQueryCacheModel.newsOrganisationName = null;
		}

		mediaQueryCacheModel.organisationType = getOrganisationType();

		String organisationType = mediaQueryCacheModel.organisationType;

		if ((organisationType != null) && (organisationType.length() == 0)) {
			mediaQueryCacheModel.organisationType = null;
		}

		mediaQueryCacheModel.mobile = getMobile();

		String mobile = mediaQueryCacheModel.mobile;

		if ((mobile != null) && (mobile.length() == 0)) {
			mediaQueryCacheModel.mobile = null;
		}

		mediaQueryCacheModel.email = getEmail();

		String email = mediaQueryCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			mediaQueryCacheModel.email = null;
		}

		mediaQueryCacheModel.subject = getSubject();

		String subject = mediaQueryCacheModel.subject;

		if ((subject != null) && (subject.length() == 0)) {
			mediaQueryCacheModel.subject = null;
		}

		mediaQueryCacheModel.mediaQuery = getMediaQuery();

		String mediaQuery = mediaQueryCacheModel.mediaQuery;

		if ((mediaQuery != null) && (mediaQuery.length() == 0)) {
			mediaQueryCacheModel.mediaQuery = null;
		}

		return mediaQueryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{srNo=");
		sb.append(getSrNo());
		sb.append(", journalistName=");
		sb.append(getJournalistName());
		sb.append(", newsOrganisationName=");
		sb.append(getNewsOrganisationName());
		sb.append(", organisationType=");
		sb.append(getOrganisationType());
		sb.append(", mobile=");
		sb.append(getMobile());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", subject=");
		sb.append(getSubject());
		sb.append(", mediaQuery=");
		sb.append(getMediaQuery());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.media.query.model.MediaQuery");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>srNo</column-name><column-value><![CDATA[");
		sb.append(getSrNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>journalistName</column-name><column-value><![CDATA[");
		sb.append(getJournalistName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>newsOrganisationName</column-name><column-value><![CDATA[");
		sb.append(getNewsOrganisationName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organisationType</column-name><column-value><![CDATA[");
		sb.append(getOrganisationType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mobile</column-name><column-value><![CDATA[");
		sb.append(getMobile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>subject</column-name><column-value><![CDATA[");
		sb.append(getSubject());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mediaQuery</column-name><column-value><![CDATA[");
		sb.append(getMediaQuery());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = MediaQuery.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			MediaQuery.class
		};
	private long _srNo;
	private String _journalistName;
	private String _newsOrganisationName;
	private String _organisationType;
	private String _mobile;
	private String _email;
	private String _subject;
	private String _mediaQuery;
	private MediaQuery _escapedModel;
}