/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.relieanceada.rinfra.portal.pressRelease.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.relieanceada.rinfra.portal.pressRelease.model.PressRelease;
import com.relieanceada.rinfra.portal.pressRelease.model.PressReleaseModel;
import com.relieanceada.rinfra.portal.pressRelease.model.PressReleaseSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the PressRelease service. Represents a row in the &quot;PRESS_RELEASE_PressRelease&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link PressReleaseModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PressReleaseImpl}.
 * </p>
 *
 * @author Vipin Singh
 * @see PressReleaseImpl
 * @see PressRelease
 * @see PressReleaseModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class PressReleaseModelImpl extends BaseModelImpl<PressRelease>
	implements PressReleaseModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a press release model instance should use the {@link PressRelease} interface instead.
	 */
	public static final String TABLE_NAME = "PRESS_RELEASE_PressRelease";
	public static final Object[][] TABLE_COLUMNS = {
			{ "pressId", Types.BIGINT },
			{ "newsYear", Types.VARCHAR },
			{ "newsDate", Types.TIMESTAMP },
			{ "heading", Types.VARCHAR },
			{ "data_", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "show_", Types.VARCHAR },
			{ "createdDate", Types.TIMESTAMP },
			{ "fileName", Types.VARCHAR },
			{ "fileURL", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("pressId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("newsYear", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("newsDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("heading", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("data_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("show_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("fileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileURL", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table PRESS_RELEASE_PressRelease (pressId LONG not null primary key,newsYear VARCHAR(75) null,newsDate DATE null,heading VARCHAR(75) null,data_ VARCHAR(75) null,description VARCHAR(75) null,show_ VARCHAR(75) null,createdDate DATE null,fileName VARCHAR(75) null,fileURL VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table PRESS_RELEASE_PressRelease";
	public static final String ORDER_BY_JPQL = " ORDER BY pressRelease.newsDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY PRESS_RELEASE_PressRelease.newsDate DESC";
	public static final String DATA_SOURCE = "extDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.relieanceada.rinfra.portal.pressRelease.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.relieanceada.rinfra.portal.pressRelease.model.PressRelease"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.relieanceada.rinfra.portal.pressRelease.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.relieanceada.rinfra.portal.pressRelease.model.PressRelease"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.relieanceada.rinfra.portal.pressRelease.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.relieanceada.rinfra.portal.pressRelease.model.PressRelease"),
			true);
	public static final long HEADING_COLUMN_BITMASK = 1L;
	public static final long NEWSYEAR_COLUMN_BITMASK = 2L;
	public static final long NEWSDATE_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static PressRelease toModel(PressReleaseSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PressRelease model = new PressReleaseImpl();

		model.setPressId(soapModel.getPressId());
		model.setNewsYear(soapModel.getNewsYear());
		model.setNewsDate(soapModel.getNewsDate());
		model.setHeading(soapModel.getHeading());
		model.setData(soapModel.getData());
		model.setDescription(soapModel.getDescription());
		model.setShow(soapModel.getShow());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setFileName(soapModel.getFileName());
		model.setFileURL(soapModel.getFileURL());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<PressRelease> toModels(PressReleaseSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<PressRelease> models = new ArrayList<PressRelease>(soapModels.length);

		for (PressReleaseSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.relieanceada.rinfra.portal.pressRelease.service.util.ServiceProps.get(
				"lock.expiration.time.com.relieanceada.rinfra.portal.pressRelease.model.PressRelease"));

	public PressReleaseModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _pressId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPressId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _pressId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PressRelease.class;
	}

	@Override
	public String getModelClassName() {
		return PressRelease.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("pressId", getPressId());
		attributes.put("newsYear", getNewsYear());
		attributes.put("newsDate", getNewsDate());
		attributes.put("heading", getHeading());
		attributes.put("data", getData());
		attributes.put("description", getDescription());
		attributes.put("show", getShow());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("fileName", getFileName());
		attributes.put("fileURL", getFileURL());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long pressId = (Long)attributes.get("pressId");

		if (pressId != null) {
			setPressId(pressId);
		}

		String newsYear = (String)attributes.get("newsYear");

		if (newsYear != null) {
			setNewsYear(newsYear);
		}

		Date newsDate = (Date)attributes.get("newsDate");

		if (newsDate != null) {
			setNewsDate(newsDate);
		}

		String heading = (String)attributes.get("heading");

		if (heading != null) {
			setHeading(heading);
		}

		String data = (String)attributes.get("data");

		if (data != null) {
			setData(data);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String show = (String)attributes.get("show");

		if (show != null) {
			setShow(show);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String fileName = (String)attributes.get("fileName");

		if (fileName != null) {
			setFileName(fileName);
		}

		String fileURL = (String)attributes.get("fileURL");

		if (fileURL != null) {
			setFileURL(fileURL);
		}
	}

	@JSON
	@Override
	public long getPressId() {
		return _pressId;
	}

	@Override
	public void setPressId(long pressId) {
		_pressId = pressId;
	}

	@JSON
	@Override
	public String getNewsYear() {
		if (_newsYear == null) {
			return StringPool.BLANK;
		}
		else {
			return _newsYear;
		}
	}

	@Override
	public void setNewsYear(String newsYear) {
		_columnBitmask |= NEWSYEAR_COLUMN_BITMASK;

		if (_originalNewsYear == null) {
			_originalNewsYear = _newsYear;
		}

		_newsYear = newsYear;
	}

	public String getOriginalNewsYear() {
		return GetterUtil.getString(_originalNewsYear);
	}

	@JSON
	@Override
	public Date getNewsDate() {
		return _newsDate;
	}

	@Override
	public void setNewsDate(Date newsDate) {
		_columnBitmask = -1L;

		_newsDate = newsDate;
	}

	@JSON
	@Override
	public String getHeading() {
		if (_heading == null) {
			return StringPool.BLANK;
		}
		else {
			return _heading;
		}
	}

	@Override
	public void setHeading(String heading) {
		_columnBitmask |= HEADING_COLUMN_BITMASK;

		if (_originalHeading == null) {
			_originalHeading = _heading;
		}

		_heading = heading;
	}

	public String getOriginalHeading() {
		return GetterUtil.getString(_originalHeading);
	}

	@JSON
	@Override
	public String getData() {
		if (_data == null) {
			return StringPool.BLANK;
		}
		else {
			return _data;
		}
	}

	@Override
	public void setData(String data) {
		_data = data;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public String getShow() {
		if (_show == null) {
			return StringPool.BLANK;
		}
		else {
			return _show;
		}
	}

	@Override
	public void setShow(String show) {
		_show = show;
	}

	@JSON
	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@JSON
	@Override
	public String getFileName() {
		if (_fileName == null) {
			return StringPool.BLANK;
		}
		else {
			return _fileName;
		}
	}

	@Override
	public void setFileName(String fileName) {
		_fileName = fileName;
	}

	@JSON
	@Override
	public String getFileURL() {
		if (_fileURL == null) {
			return StringPool.BLANK;
		}
		else {
			return _fileURL;
		}
	}

	@Override
	public void setFileURL(String fileURL) {
		_fileURL = fileURL;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			PressRelease.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PressRelease toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PressRelease)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PressReleaseImpl pressReleaseImpl = new PressReleaseImpl();

		pressReleaseImpl.setPressId(getPressId());
		pressReleaseImpl.setNewsYear(getNewsYear());
		pressReleaseImpl.setNewsDate(getNewsDate());
		pressReleaseImpl.setHeading(getHeading());
		pressReleaseImpl.setData(getData());
		pressReleaseImpl.setDescription(getDescription());
		pressReleaseImpl.setShow(getShow());
		pressReleaseImpl.setCreatedDate(getCreatedDate());
		pressReleaseImpl.setFileName(getFileName());
		pressReleaseImpl.setFileURL(getFileURL());

		pressReleaseImpl.resetOriginalValues();

		return pressReleaseImpl;
	}

	@Override
	public int compareTo(PressRelease pressRelease) {
		int value = 0;

		value = DateUtil.compareTo(getNewsDate(), pressRelease.getNewsDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PressRelease)) {
			return false;
		}

		PressRelease pressRelease = (PressRelease)obj;

		long primaryKey = pressRelease.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		PressReleaseModelImpl pressReleaseModelImpl = this;

		pressReleaseModelImpl._originalNewsYear = pressReleaseModelImpl._newsYear;

		pressReleaseModelImpl._originalHeading = pressReleaseModelImpl._heading;

		pressReleaseModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PressRelease> toCacheModel() {
		PressReleaseCacheModel pressReleaseCacheModel = new PressReleaseCacheModel();

		pressReleaseCacheModel.pressId = getPressId();

		pressReleaseCacheModel.newsYear = getNewsYear();

		String newsYear = pressReleaseCacheModel.newsYear;

		if ((newsYear != null) && (newsYear.length() == 0)) {
			pressReleaseCacheModel.newsYear = null;
		}

		Date newsDate = getNewsDate();

		if (newsDate != null) {
			pressReleaseCacheModel.newsDate = newsDate.getTime();
		}
		else {
			pressReleaseCacheModel.newsDate = Long.MIN_VALUE;
		}

		pressReleaseCacheModel.heading = getHeading();

		String heading = pressReleaseCacheModel.heading;

		if ((heading != null) && (heading.length() == 0)) {
			pressReleaseCacheModel.heading = null;
		}

		pressReleaseCacheModel.data = getData();

		String data = pressReleaseCacheModel.data;

		if ((data != null) && (data.length() == 0)) {
			pressReleaseCacheModel.data = null;
		}

		pressReleaseCacheModel.description = getDescription();

		String description = pressReleaseCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			pressReleaseCacheModel.description = null;
		}

		pressReleaseCacheModel.show = getShow();

		String show = pressReleaseCacheModel.show;

		if ((show != null) && (show.length() == 0)) {
			pressReleaseCacheModel.show = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			pressReleaseCacheModel.createdDate = createdDate.getTime();
		}
		else {
			pressReleaseCacheModel.createdDate = Long.MIN_VALUE;
		}

		pressReleaseCacheModel.fileName = getFileName();

		String fileName = pressReleaseCacheModel.fileName;

		if ((fileName != null) && (fileName.length() == 0)) {
			pressReleaseCacheModel.fileName = null;
		}

		pressReleaseCacheModel.fileURL = getFileURL();

		String fileURL = pressReleaseCacheModel.fileURL;

		if ((fileURL != null) && (fileURL.length() == 0)) {
			pressReleaseCacheModel.fileURL = null;
		}

		return pressReleaseCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{pressId=");
		sb.append(getPressId());
		sb.append(", newsYear=");
		sb.append(getNewsYear());
		sb.append(", newsDate=");
		sb.append(getNewsDate());
		sb.append(", heading=");
		sb.append(getHeading());
		sb.append(", data=");
		sb.append(getData());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", show=");
		sb.append(getShow());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", fileName=");
		sb.append(getFileName());
		sb.append(", fileURL=");
		sb.append(getFileURL());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append(
			"com.relieanceada.rinfra.portal.pressRelease.model.PressRelease");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>pressId</column-name><column-value><![CDATA[");
		sb.append(getPressId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>newsYear</column-name><column-value><![CDATA[");
		sb.append(getNewsYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>newsDate</column-name><column-value><![CDATA[");
		sb.append(getNewsDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>heading</column-name><column-value><![CDATA[");
		sb.append(getHeading());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data</column-name><column-value><![CDATA[");
		sb.append(getData());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>show</column-name><column-value><![CDATA[");
		sb.append(getShow());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileName</column-name><column-value><![CDATA[");
		sb.append(getFileName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileURL</column-name><column-value><![CDATA[");
		sb.append(getFileURL());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = PressRelease.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			PressRelease.class
		};
	private long _pressId;
	private String _newsYear;
	private String _originalNewsYear;
	private Date _newsDate;
	private String _heading;
	private String _originalHeading;
	private String _data;
	private String _description;
	private String _show;
	private Date _createdDate;
	private String _fileName;
	private String _fileURL;
	private long _columnBitmask;
	private PressRelease _escapedModel;
}