/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package attendence.rinfra.services.service.base;

import aQute.bnd.annotation.ProviderType;

import attendence.rinfra.services.model.AttendenceTransaction;
import attendence.rinfra.services.service.AttendenceTransactionLocalService;
import attendence.rinfra.services.service.persistence.AttendenceTransactionFinder;
import attendence.rinfra.services.service.persistence.AttendenceTransactionPersistence;
import attendence.rinfra.services.service.persistence.EmpMasterPersistence;
import attendence.rinfra.services.service.persistence.EmpOtpMasterPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the attendence transaction local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link attendence.rinfra.services.service.impl.AttendenceTransactionLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see attendence.rinfra.services.service.impl.AttendenceTransactionLocalServiceImpl
 * @see attendence.rinfra.services.service.AttendenceTransactionLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class AttendenceTransactionLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements AttendenceTransactionLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link attendence.rinfra.services.service.AttendenceTransactionLocalServiceUtil} to access the attendence transaction local service.
	 */

	/**
	 * Adds the attendence transaction to the database. Also notifies the appropriate model listeners.
	 *
	 * @param attendenceTransaction the attendence transaction
	 * @return the attendence transaction that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AttendenceTransaction addAttendenceTransaction(
		AttendenceTransaction attendenceTransaction) {
		attendenceTransaction.setNew(true);

		return attendenceTransactionPersistence.update(attendenceTransaction);
	}

	/**
	 * Creates a new attendence transaction with the primary key. Does not add the attendence transaction to the database.
	 *
	 * @param srNo the primary key for the new attendence transaction
	 * @return the new attendence transaction
	 */
	@Override
	public AttendenceTransaction createAttendenceTransaction(String srNo) {
		return attendenceTransactionPersistence.create(srNo);
	}

	/**
	 * Deletes the attendence transaction with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param srNo the primary key of the attendence transaction
	 * @return the attendence transaction that was removed
	 * @throws PortalException if a attendence transaction with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AttendenceTransaction deleteAttendenceTransaction(String srNo)
		throws PortalException {
		return attendenceTransactionPersistence.remove(srNo);
	}

	/**
	 * Deletes the attendence transaction from the database. Also notifies the appropriate model listeners.
	 *
	 * @param attendenceTransaction the attendence transaction
	 * @return the attendence transaction that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AttendenceTransaction deleteAttendenceTransaction(
		AttendenceTransaction attendenceTransaction) {
		return attendenceTransactionPersistence.remove(attendenceTransaction);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(AttendenceTransaction.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return attendenceTransactionPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link attendence.rinfra.services.model.impl.AttendenceTransactionModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return attendenceTransactionPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link attendence.rinfra.services.model.impl.AttendenceTransactionModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return attendenceTransactionPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return attendenceTransactionPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return attendenceTransactionPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public AttendenceTransaction fetchAttendenceTransaction(String srNo) {
		return attendenceTransactionPersistence.fetchByPrimaryKey(srNo);
	}

	/**
	 * Returns the attendence transaction with the primary key.
	 *
	 * @param srNo the primary key of the attendence transaction
	 * @return the attendence transaction
	 * @throws PortalException if a attendence transaction with the primary key could not be found
	 */
	@Override
	public AttendenceTransaction getAttendenceTransaction(String srNo)
		throws PortalException {
		return attendenceTransactionPersistence.findByPrimaryKey(srNo);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return attendenceTransactionLocalService.deleteAttendenceTransaction((AttendenceTransaction)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return attendenceTransactionPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the attendence transactions.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link attendence.rinfra.services.model.impl.AttendenceTransactionModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of attendence transactions
	 * @param end the upper bound of the range of attendence transactions (not inclusive)
	 * @return the range of attendence transactions
	 */
	@Override
	public List<AttendenceTransaction> getAttendenceTransactions(int start,
		int end) {
		return attendenceTransactionPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of attendence transactions.
	 *
	 * @return the number of attendence transactions
	 */
	@Override
	public int getAttendenceTransactionsCount() {
		return attendenceTransactionPersistence.countAll();
	}

	/**
	 * Updates the attendence transaction in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param attendenceTransaction the attendence transaction
	 * @return the attendence transaction that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AttendenceTransaction updateAttendenceTransaction(
		AttendenceTransaction attendenceTransaction) {
		return attendenceTransactionPersistence.update(attendenceTransaction);
	}

	/**
	 * Returns the attendence transaction local service.
	 *
	 * @return the attendence transaction local service
	 */
	public AttendenceTransactionLocalService getAttendenceTransactionLocalService() {
		return attendenceTransactionLocalService;
	}

	/**
	 * Sets the attendence transaction local service.
	 *
	 * @param attendenceTransactionLocalService the attendence transaction local service
	 */
	public void setAttendenceTransactionLocalService(
		AttendenceTransactionLocalService attendenceTransactionLocalService) {
		this.attendenceTransactionLocalService = attendenceTransactionLocalService;
	}

	/**
	 * Returns the attendence transaction persistence.
	 *
	 * @return the attendence transaction persistence
	 */
	public AttendenceTransactionPersistence getAttendenceTransactionPersistence() {
		return attendenceTransactionPersistence;
	}

	/**
	 * Sets the attendence transaction persistence.
	 *
	 * @param attendenceTransactionPersistence the attendence transaction persistence
	 */
	public void setAttendenceTransactionPersistence(
		AttendenceTransactionPersistence attendenceTransactionPersistence) {
		this.attendenceTransactionPersistence = attendenceTransactionPersistence;
	}

	/**
	 * Returns the attendence transaction finder.
	 *
	 * @return the attendence transaction finder
	 */
	public AttendenceTransactionFinder getAttendenceTransactionFinder() {
		return attendenceTransactionFinder;
	}

	/**
	 * Sets the attendence transaction finder.
	 *
	 * @param attendenceTransactionFinder the attendence transaction finder
	 */
	public void setAttendenceTransactionFinder(
		AttendenceTransactionFinder attendenceTransactionFinder) {
		this.attendenceTransactionFinder = attendenceTransactionFinder;
	}

	/**
	 * Returns the emp master local service.
	 *
	 * @return the emp master local service
	 */
	public attendence.rinfra.services.service.EmpMasterLocalService getEmpMasterLocalService() {
		return empMasterLocalService;
	}

	/**
	 * Sets the emp master local service.
	 *
	 * @param empMasterLocalService the emp master local service
	 */
	public void setEmpMasterLocalService(
		attendence.rinfra.services.service.EmpMasterLocalService empMasterLocalService) {
		this.empMasterLocalService = empMasterLocalService;
	}

	/**
	 * Returns the emp master persistence.
	 *
	 * @return the emp master persistence
	 */
	public EmpMasterPersistence getEmpMasterPersistence() {
		return empMasterPersistence;
	}

	/**
	 * Sets the emp master persistence.
	 *
	 * @param empMasterPersistence the emp master persistence
	 */
	public void setEmpMasterPersistence(
		EmpMasterPersistence empMasterPersistence) {
		this.empMasterPersistence = empMasterPersistence;
	}

	/**
	 * Returns the emp otp master local service.
	 *
	 * @return the emp otp master local service
	 */
	public attendence.rinfra.services.service.EmpOtpMasterLocalService getEmpOtpMasterLocalService() {
		return empOtpMasterLocalService;
	}

	/**
	 * Sets the emp otp master local service.
	 *
	 * @param empOtpMasterLocalService the emp otp master local service
	 */
	public void setEmpOtpMasterLocalService(
		attendence.rinfra.services.service.EmpOtpMasterLocalService empOtpMasterLocalService) {
		this.empOtpMasterLocalService = empOtpMasterLocalService;
	}

	/**
	 * Returns the emp otp master persistence.
	 *
	 * @return the emp otp master persistence
	 */
	public EmpOtpMasterPersistence getEmpOtpMasterPersistence() {
		return empOtpMasterPersistence;
	}

	/**
	 * Sets the emp otp master persistence.
	 *
	 * @param empOtpMasterPersistence the emp otp master persistence
	 */
	public void setEmpOtpMasterPersistence(
		EmpOtpMasterPersistence empOtpMasterPersistence) {
		this.empOtpMasterPersistence = empOtpMasterPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("attendence.rinfra.services.model.AttendenceTransaction",
			attendenceTransactionLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"attendence.rinfra.services.model.AttendenceTransaction");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AttendenceTransactionLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AttendenceTransaction.class;
	}

	protected String getModelClassName() {
		return AttendenceTransaction.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = attendenceTransactionPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = AttendenceTransactionLocalService.class)
	protected AttendenceTransactionLocalService attendenceTransactionLocalService;
	@BeanReference(type = AttendenceTransactionPersistence.class)
	protected AttendenceTransactionPersistence attendenceTransactionPersistence;
	@BeanReference(type = AttendenceTransactionFinder.class)
	protected AttendenceTransactionFinder attendenceTransactionFinder;
	@BeanReference(type = attendence.rinfra.services.service.EmpMasterLocalService.class)
	protected attendence.rinfra.services.service.EmpMasterLocalService empMasterLocalService;
	@BeanReference(type = EmpMasterPersistence.class)
	protected EmpMasterPersistence empMasterPersistence;
	@BeanReference(type = attendence.rinfra.services.service.EmpOtpMasterLocalService.class)
	protected attendence.rinfra.services.service.EmpOtpMasterLocalService empOtpMasterLocalService;
	@BeanReference(type = EmpOtpMasterPersistence.class)
	protected EmpOtpMasterPersistence empOtpMasterPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}