/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rinfra.satisfactionsurvey.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Shareholders service. Represents a row in the &quot;SHAREHOLDERS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rinfra.satisfactionsurvey.model.impl.ShareholdersModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rinfra.satisfactionsurvey.model.impl.ShareholdersImpl}.
 * </p>
 *
 * @author Mukesh
 * @see Shareholders
 * @see com.rinfra.satisfactionsurvey.model.impl.ShareholdersImpl
 * @see com.rinfra.satisfactionsurvey.model.impl.ShareholdersModelImpl
 * @generated
 */
@ProviderType
public interface ShareholdersModel extends BaseModel<Shareholders> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a shareholders model instance should use the {@link Shareholders} interface instead.
	 */

	/**
	 * Returns the primary key of this shareholders.
	 *
	 * @return the primary key of this shareholders
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this shareholders.
	 *
	 * @param primaryKey the primary key of this shareholders
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the shareholdersid of this shareholders.
	 *
	 * @return the shareholdersid of this shareholders
	 */
	public long getSHAREHOLDERSID();

	/**
	 * Sets the shareholdersid of this shareholders.
	 *
	 * @param SHAREHOLDERSID the shareholdersid of this shareholders
	 */
	public void setSHAREHOLDERSID(long SHAREHOLDERSID);

	/**
	 * Returns the sole_id of this shareholders.
	 *
	 * @return the sole_id of this shareholders
	 */
	public long getSOLE_ID();

	/**
	 * Sets the sole_id of this shareholders.
	 *
	 * @param SOLE_ID the sole_id of this shareholders
	 */
	public void setSOLE_ID(long SOLE_ID);

	/**
	 * Returns the sole_name of this shareholders.
	 *
	 * @return the sole_name of this shareholders
	 */
	@AutoEscape
	public String getSOLE_NAME();

	/**
	 * Sets the sole_name of this shareholders.
	 *
	 * @param SOLE_NAME the sole_name of this shareholders
	 */
	public void setSOLE_NAME(String SOLE_NAME);

	/**
	 * Returns the id_number of this shareholders.
	 *
	 * @return the id_number of this shareholders
	 */
	public long getID_NUMBER();

	/**
	 * Sets the id_number of this shareholders.
	 *
	 * @param ID_NUMBER the id_number of this shareholders
	 */
	public void setID_NUMBER(long ID_NUMBER);

	/**
	 * Returns the mobile of this shareholders.
	 *
	 * @return the mobile of this shareholders
	 */
	public long getMOBILE();

	/**
	 * Sets the mobile of this shareholders.
	 *
	 * @param MOBILE the mobile of this shareholders
	 */
	public void setMOBILE(long MOBILE);

	/**
	 * Returns the telephone of this shareholders.
	 *
	 * @return the telephone of this shareholders
	 */
	public long getTELEPHONE();

	/**
	 * Sets the telephone of this shareholders.
	 *
	 * @param TELEPHONE the telephone of this shareholders
	 */
	public void setTELEPHONE(long TELEPHONE);

	/**
	 * Returns the email of this shareholders.
	 *
	 * @return the email of this shareholders
	 */
	@AutoEscape
	public String getEMAIL();

	/**
	 * Sets the email of this shareholders.
	 *
	 * @param EMAIL the email of this shareholders
	 */
	public void setEMAIL(String EMAIL);

	/**
	 * Returns the query_response of this shareholders.
	 *
	 * @return the query_response of this shareholders
	 */
	@AutoEscape
	public String getQUERY_RESPONSE();

	/**
	 * Sets the query_response of this shareholders.
	 *
	 * @param QUERY_RESPONSE the query_response of this shareholders
	 */
	public void setQUERY_RESPONSE(String QUERY_RESPONSE);

	/**
	 * Returns the overall_rating of this shareholders.
	 *
	 * @return the overall_rating of this shareholders
	 */
	@AutoEscape
	public String getOVERALL_RATING();

	/**
	 * Sets the overall_rating of this shareholders.
	 *
	 * @param OVERALL_RATING the overall_rating of this shareholders
	 */
	public void setOVERALL_RATING(String OVERALL_RATING);

	/**
	 * Returns the comp_information of this shareholders.
	 *
	 * @return the comp_information of this shareholders
	 */
	@AutoEscape
	public String getCOMP_INFORMATION();

	/**
	 * Sets the comp_information of this shareholders.
	 *
	 * @param COMP_INFORMATION the comp_information of this shareholders
	 */
	public void setCOMP_INFORMATION(String COMP_INFORMATION);

	/**
	 * Returns the quality_report of this shareholders.
	 *
	 * @return the quality_report of this shareholders
	 */
	@AutoEscape
	public String getQUALITY_REPORT();

	/**
	 * Sets the quality_report of this shareholders.
	 *
	 * @param QUALITY_REPORT the quality_report of this shareholders
	 */
	public void setQUALITY_REPORT(String QUALITY_REPORT);

	/**
	 * Returns the description of this shareholders.
	 *
	 * @return the description of this shareholders
	 */
	@AutoEscape
	public String getDESCRIPTION();

	/**
	 * Sets the description of this shareholders.
	 *
	 * @param DESCRIPTION the description of this shareholders
	 */
	public void setDESCRIPTION(String DESCRIPTION);

	/**
	 * Returns the comments of this shareholders.
	 *
	 * @return the comments of this shareholders
	 */
	@AutoEscape
	public String getCOMMENTS();

	/**
	 * Sets the comments of this shareholders.
	 *
	 * @param COMMENTS the comments of this shareholders
	 */
	public void setCOMMENTS(String COMMENTS);

	/**
	 * Returns the grievance of this shareholders.
	 *
	 * @return the grievance of this shareholders
	 */
	@AutoEscape
	public String getGRIEVANCE();

	/**
	 * Sets the grievance of this shareholders.
	 *
	 * @param GRIEVANCE the grievance of this shareholders
	 */
	public void setGRIEVANCE(String GRIEVANCE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Shareholders shareholders);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Shareholders> toCacheModel();

	@Override
	public Shareholders toEscapedModel();

	@Override
	public Shareholders toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}