/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package rpower.shareholders.doc.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the RpowerShareHolders service. Represents a row in the &quot;RPOWER_SHARE_HOLDERS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link rpower.shareholders.doc.model.impl.RpowerShareHoldersModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link rpower.shareholders.doc.model.impl.RpowerShareHoldersImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RpowerShareHolders
 * @see rpower.shareholders.doc.model.impl.RpowerShareHoldersImpl
 * @see rpower.shareholders.doc.model.impl.RpowerShareHoldersModelImpl
 * @generated
 */
@ProviderType
public interface RpowerShareHoldersModel extends BaseModel<RpowerShareHolders> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rpower share holders model instance should use the {@link RpowerShareHolders} interface instead.
	 */

	/**
	 * Returns the primary key of this rpower share holders.
	 *
	 * @return the primary key of this rpower share holders
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this rpower share holders.
	 *
	 * @param primaryKey the primary key of this rpower share holders
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the srno of this rpower share holders.
	 *
	 * @return the srno of this rpower share holders
	 */
	public long getSRNO();

	/**
	 * Sets the srno of this rpower share holders.
	 *
	 * @param SRNO the srno of this rpower share holders
	 */
	public void setSRNO(long SRNO);

	/**
	 * Returns the folio_no of this rpower share holders.
	 *
	 * @return the folio_no of this rpower share holders
	 */
	@AutoEscape
	public String getFOLIO_NO();

	/**
	 * Sets the folio_no of this rpower share holders.
	 *
	 * @param FOLIO_NO the folio_no of this rpower share holders
	 */
	public void setFOLIO_NO(String FOLIO_NO);

	/**
	 * Returns the shares of this rpower share holders.
	 *
	 * @return the shares of this rpower share holders
	 */
	@AutoEscape
	public String getSHARES();

	/**
	 * Sets the shares of this rpower share holders.
	 *
	 * @param SHARES the shares of this rpower share holders
	 */
	public void setSHARES(String SHARES);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		rpower.shareholders.doc.model.RpowerShareHolders rpowerShareHolders);

	@Override
	public int hashCode();

	@Override
	public CacheModel<rpower.shareholders.doc.model.RpowerShareHolders> toCacheModel();

	@Override
	public rpower.shareholders.doc.model.RpowerShareHolders toEscapedModel();

	@Override
	public rpower.shareholders.doc.model.RpowerShareHolders toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}