/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package OCCModuleNew.model.impl;

import OCCModuleNew.model.OccMessageNew;
import OCCModuleNew.model.OccMessageNewModel;
import OCCModuleNew.model.OccMessageNewSoap;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the OccMessageNew service. Represents a row in the &quot;OCCMESSAGENEW&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link OccMessageNewModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OccMessageNewImpl}.
 * </p>
 *
 * @author Mukesh Patidar
 * @see OccMessageNewImpl
 * @see OccMessageNew
 * @see OccMessageNewModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class OccMessageNewModelImpl extends BaseModelImpl<OccMessageNew>
	implements OccMessageNewModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a occ message new model instance should use the {@link OccMessageNew} interface instead.
	 */
	public static final String TABLE_NAME = "OCCMESSAGENEW";
	public static final Object[][] TABLE_COLUMNS = {
			{ "MSG_ID", Types.BIGINT },
			{ "LISTNAME", Types.VARCHAR },
			{ "MESSAGE", Types.VARCHAR },
			{ "MSGSENDDATE", Types.VARCHAR },
			{ "SEVERITY", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("MSG_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("LISTNAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MESSAGE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MSGSENDDATE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("SEVERITY", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table OCCMESSAGENEW (MSG_ID LONG not null primary key,LISTNAME VARCHAR(75) null,MESSAGE VARCHAR(75) null,MSGSENDDATE VARCHAR(75) null,SEVERITY VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table OCCMESSAGENEW";
	public static final String ORDER_BY_JPQL = " ORDER BY occMessageNew.MSG_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OCCMESSAGENEW.MSG_ID ASC";
	public static final String DATA_SOURCE = "extDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(OCCModuleNew.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.OCCModuleNew.model.OccMessageNew"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(OCCModuleNew.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.OCCModuleNew.model.OccMessageNew"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static OccMessageNew toModel(OccMessageNewSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		OccMessageNew model = new OccMessageNewImpl();

		model.setMSG_ID(soapModel.getMSG_ID());
		model.setListName(soapModel.getListName());
		model.setMessage(soapModel.getMessage());
		model.setMSgSendDate(soapModel.getMSgSendDate());
		model.setSeverity(soapModel.getSeverity());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<OccMessageNew> toModels(OccMessageNewSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<OccMessageNew> models = new ArrayList<OccMessageNew>(soapModels.length);

		for (OccMessageNewSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(OCCModuleNew.service.util.ServiceProps.get(
				"lock.expiration.time.OCCModuleNew.model.OccMessageNew"));

	public OccMessageNewModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _MSG_ID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMSG_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _MSG_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OccMessageNew.class;
	}

	@Override
	public String getModelClassName() {
		return OccMessageNew.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("MSG_ID", getMSG_ID());
		attributes.put("ListName", getListName());
		attributes.put("Message", getMessage());
		attributes.put("MSgSendDate", getMSgSendDate());
		attributes.put("Severity", getSeverity());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long MSG_ID = (Long)attributes.get("MSG_ID");

		if (MSG_ID != null) {
			setMSG_ID(MSG_ID);
		}

		String ListName = (String)attributes.get("ListName");

		if (ListName != null) {
			setListName(ListName);
		}

		String Message = (String)attributes.get("Message");

		if (Message != null) {
			setMessage(Message);
		}

		String MSgSendDate = (String)attributes.get("MSgSendDate");

		if (MSgSendDate != null) {
			setMSgSendDate(MSgSendDate);
		}

		String Severity = (String)attributes.get("Severity");

		if (Severity != null) {
			setSeverity(Severity);
		}
	}

	@JSON
	@Override
	public long getMSG_ID() {
		return _MSG_ID;
	}

	@Override
	public void setMSG_ID(long MSG_ID) {
		_MSG_ID = MSG_ID;
	}

	@JSON
	@Override
	public String getListName() {
		if (_ListName == null) {
			return StringPool.BLANK;
		}
		else {
			return _ListName;
		}
	}

	@Override
	public void setListName(String ListName) {
		_ListName = ListName;
	}

	@JSON
	@Override
	public String getMessage() {
		if (_Message == null) {
			return StringPool.BLANK;
		}
		else {
			return _Message;
		}
	}

	@Override
	public void setMessage(String Message) {
		_Message = Message;
	}

	@JSON
	@Override
	public String getMSgSendDate() {
		if (_MSgSendDate == null) {
			return StringPool.BLANK;
		}
		else {
			return _MSgSendDate;
		}
	}

	@Override
	public void setMSgSendDate(String MSgSendDate) {
		_MSgSendDate = MSgSendDate;
	}

	@JSON
	@Override
	public String getSeverity() {
		if (_Severity == null) {
			return StringPool.BLANK;
		}
		else {
			return _Severity;
		}
	}

	@Override
	public void setSeverity(String Severity) {
		_Severity = Severity;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			OccMessageNew.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OccMessageNew toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (OccMessageNew)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OccMessageNewImpl occMessageNewImpl = new OccMessageNewImpl();

		occMessageNewImpl.setMSG_ID(getMSG_ID());
		occMessageNewImpl.setListName(getListName());
		occMessageNewImpl.setMessage(getMessage());
		occMessageNewImpl.setMSgSendDate(getMSgSendDate());
		occMessageNewImpl.setSeverity(getSeverity());

		occMessageNewImpl.resetOriginalValues();

		return occMessageNewImpl;
	}

	@Override
	public int compareTo(OccMessageNew occMessageNew) {
		long primaryKey = occMessageNew.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof OccMessageNew)) {
			return false;
		}

		OccMessageNew occMessageNew = (OccMessageNew)obj;

		long primaryKey = occMessageNew.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<OccMessageNew> toCacheModel() {
		OccMessageNewCacheModel occMessageNewCacheModel = new OccMessageNewCacheModel();

		occMessageNewCacheModel.MSG_ID = getMSG_ID();

		occMessageNewCacheModel.ListName = getListName();

		String ListName = occMessageNewCacheModel.ListName;

		if ((ListName != null) && (ListName.length() == 0)) {
			occMessageNewCacheModel.ListName = null;
		}

		occMessageNewCacheModel.Message = getMessage();

		String Message = occMessageNewCacheModel.Message;

		if ((Message != null) && (Message.length() == 0)) {
			occMessageNewCacheModel.Message = null;
		}

		occMessageNewCacheModel.MSgSendDate = getMSgSendDate();

		String MSgSendDate = occMessageNewCacheModel.MSgSendDate;

		if ((MSgSendDate != null) && (MSgSendDate.length() == 0)) {
			occMessageNewCacheModel.MSgSendDate = null;
		}

		occMessageNewCacheModel.Severity = getSeverity();

		String Severity = occMessageNewCacheModel.Severity;

		if ((Severity != null) && (Severity.length() == 0)) {
			occMessageNewCacheModel.Severity = null;
		}

		return occMessageNewCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{MSG_ID=");
		sb.append(getMSG_ID());
		sb.append(", ListName=");
		sb.append(getListName());
		sb.append(", Message=");
		sb.append(getMessage());
		sb.append(", MSgSendDate=");
		sb.append(getMSgSendDate());
		sb.append(", Severity=");
		sb.append(getSeverity());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("OCCModuleNew.model.OccMessageNew");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>MSG_ID</column-name><column-value><![CDATA[");
		sb.append(getMSG_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ListName</column-name><column-value><![CDATA[");
		sb.append(getListName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Message</column-name><column-value><![CDATA[");
		sb.append(getMessage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MSgSendDate</column-name><column-value><![CDATA[");
		sb.append(getMSgSendDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Severity</column-name><column-value><![CDATA[");
		sb.append(getSeverity());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = OccMessageNew.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			OccMessageNew.class
		};
	private long _MSG_ID;
	private String _ListName;
	private String _Message;
	private String _MSgSendDate;
	private String _Severity;
	private OccMessageNew _escapedModel;
}