/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package OCCModuleNew.model.impl;

import OCCModuleNew.model.OccNew;
import OCCModuleNew.model.OccNewModel;
import OCCModuleNew.model.OccNewSoap;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the OccNew service. Represents a row in the &quot;OCCNEW&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link OccNewModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OccNewImpl}.
 * </p>
 *
 * @author Mukesh Patidar
 * @see OccNewImpl
 * @see OccNew
 * @see OccNewModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class OccNewModelImpl extends BaseModelImpl<OccNew>
	implements OccNewModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a occ new model instance should use the {@link OccNew} interface instead.
	 */
	public static final String TABLE_NAME = "OCCNEW";
	public static final Object[][] TABLE_COLUMNS = {
			{ "OCCID", Types.BIGINT },
			{ "LISTID", Types.BIGINT },
			{ "LISTNAME", Types.VARCHAR },
			{ "ROLLNO", Types.VARCHAR },
			{ "NAME", Types.VARCHAR },
			{ "MOBILENO", Types.BIGINT },
			{ "EMAIL", Types.VARCHAR },
			{ "DEPT", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("OCCID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("LISTID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("LISTNAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ROLLNO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MOBILENO", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("EMAIL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DEPT", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table OCCNEW (OCCID LONG not null primary key,LISTID LONG,LISTNAME VARCHAR(75) null,ROLLNO VARCHAR(75) null,NAME VARCHAR(75) null,MOBILENO LONG,EMAIL VARCHAR(75) null,DEPT VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table OCCNEW";
	public static final String ORDER_BY_JPQL = " ORDER BY occNew.OCCID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OCCNEW.OCCID ASC";
	public static final String DATA_SOURCE = "extDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(OCCModuleNew.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.OCCModuleNew.model.OccNew"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(OCCModuleNew.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.OCCModuleNew.model.OccNew"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static OccNew toModel(OccNewSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		OccNew model = new OccNewImpl();

		model.setOCCID(soapModel.getOCCID());
		model.setListID(soapModel.getListID());
		model.setListName(soapModel.getListName());
		model.setRollNo(soapModel.getRollNo());
		model.setName(soapModel.getName());
		model.setMobileNo(soapModel.getMobileNo());
		model.setEmail(soapModel.getEmail());
		model.setDept(soapModel.getDept());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<OccNew> toModels(OccNewSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<OccNew> models = new ArrayList<OccNew>(soapModels.length);

		for (OccNewSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(OCCModuleNew.service.util.ServiceProps.get(
				"lock.expiration.time.OCCModuleNew.model.OccNew"));

	public OccNewModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _OCCID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOCCID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _OCCID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OccNew.class;
	}

	@Override
	public String getModelClassName() {
		return OccNew.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("OCCID", getOCCID());
		attributes.put("ListID", getListID());
		attributes.put("ListName", getListName());
		attributes.put("RollNo", getRollNo());
		attributes.put("Name", getName());
		attributes.put("MobileNo", getMobileNo());
		attributes.put("Email", getEmail());
		attributes.put("Dept", getDept());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long OCCID = (Long)attributes.get("OCCID");

		if (OCCID != null) {
			setOCCID(OCCID);
		}

		Long ListID = (Long)attributes.get("ListID");

		if (ListID != null) {
			setListID(ListID);
		}

		String ListName = (String)attributes.get("ListName");

		if (ListName != null) {
			setListName(ListName);
		}

		String RollNo = (String)attributes.get("RollNo");

		if (RollNo != null) {
			setRollNo(RollNo);
		}

		String Name = (String)attributes.get("Name");

		if (Name != null) {
			setName(Name);
		}

		Long MobileNo = (Long)attributes.get("MobileNo");

		if (MobileNo != null) {
			setMobileNo(MobileNo);
		}

		String Email = (String)attributes.get("Email");

		if (Email != null) {
			setEmail(Email);
		}

		String Dept = (String)attributes.get("Dept");

		if (Dept != null) {
			setDept(Dept);
		}
	}

	@JSON
	@Override
	public long getOCCID() {
		return _OCCID;
	}

	@Override
	public void setOCCID(long OCCID) {
		_OCCID = OCCID;
	}

	@JSON
	@Override
	public long getListID() {
		return _ListID;
	}

	@Override
	public void setListID(long ListID) {
		_ListID = ListID;
	}

	@JSON
	@Override
	public String getListName() {
		if (_ListName == null) {
			return StringPool.BLANK;
		}
		else {
			return _ListName;
		}
	}

	@Override
	public void setListName(String ListName) {
		_ListName = ListName;
	}

	@JSON
	@Override
	public String getRollNo() {
		if (_RollNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _RollNo;
		}
	}

	@Override
	public void setRollNo(String RollNo) {
		_RollNo = RollNo;
	}

	@JSON
	@Override
	public String getName() {
		if (_Name == null) {
			return StringPool.BLANK;
		}
		else {
			return _Name;
		}
	}

	@Override
	public void setName(String Name) {
		_Name = Name;
	}

	@JSON
	@Override
	public long getMobileNo() {
		return _MobileNo;
	}

	@Override
	public void setMobileNo(long MobileNo) {
		_MobileNo = MobileNo;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_Email == null) {
			return StringPool.BLANK;
		}
		else {
			return _Email;
		}
	}

	@Override
	public void setEmail(String Email) {
		_Email = Email;
	}

	@JSON
	@Override
	public String getDept() {
		if (_Dept == null) {
			return StringPool.BLANK;
		}
		else {
			return _Dept;
		}
	}

	@Override
	public void setDept(String Dept) {
		_Dept = Dept;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			OccNew.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OccNew toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (OccNew)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OccNewImpl occNewImpl = new OccNewImpl();

		occNewImpl.setOCCID(getOCCID());
		occNewImpl.setListID(getListID());
		occNewImpl.setListName(getListName());
		occNewImpl.setRollNo(getRollNo());
		occNewImpl.setName(getName());
		occNewImpl.setMobileNo(getMobileNo());
		occNewImpl.setEmail(getEmail());
		occNewImpl.setDept(getDept());

		occNewImpl.resetOriginalValues();

		return occNewImpl;
	}

	@Override
	public int compareTo(OccNew occNew) {
		long primaryKey = occNew.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof OccNew)) {
			return false;
		}

		OccNew occNew = (OccNew)obj;

		long primaryKey = occNew.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<OccNew> toCacheModel() {
		OccNewCacheModel occNewCacheModel = new OccNewCacheModel();

		occNewCacheModel.OCCID = getOCCID();

		occNewCacheModel.ListID = getListID();

		occNewCacheModel.ListName = getListName();

		String ListName = occNewCacheModel.ListName;

		if ((ListName != null) && (ListName.length() == 0)) {
			occNewCacheModel.ListName = null;
		}

		occNewCacheModel.RollNo = getRollNo();

		String RollNo = occNewCacheModel.RollNo;

		if ((RollNo != null) && (RollNo.length() == 0)) {
			occNewCacheModel.RollNo = null;
		}

		occNewCacheModel.Name = getName();

		String Name = occNewCacheModel.Name;

		if ((Name != null) && (Name.length() == 0)) {
			occNewCacheModel.Name = null;
		}

		occNewCacheModel.MobileNo = getMobileNo();

		occNewCacheModel.Email = getEmail();

		String Email = occNewCacheModel.Email;

		if ((Email != null) && (Email.length() == 0)) {
			occNewCacheModel.Email = null;
		}

		occNewCacheModel.Dept = getDept();

		String Dept = occNewCacheModel.Dept;

		if ((Dept != null) && (Dept.length() == 0)) {
			occNewCacheModel.Dept = null;
		}

		return occNewCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{OCCID=");
		sb.append(getOCCID());
		sb.append(", ListID=");
		sb.append(getListID());
		sb.append(", ListName=");
		sb.append(getListName());
		sb.append(", RollNo=");
		sb.append(getRollNo());
		sb.append(", Name=");
		sb.append(getName());
		sb.append(", MobileNo=");
		sb.append(getMobileNo());
		sb.append(", Email=");
		sb.append(getEmail());
		sb.append(", Dept=");
		sb.append(getDept());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("OCCModuleNew.model.OccNew");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>OCCID</column-name><column-value><![CDATA[");
		sb.append(getOCCID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ListID</column-name><column-value><![CDATA[");
		sb.append(getListID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ListName</column-name><column-value><![CDATA[");
		sb.append(getListName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>RollNo</column-name><column-value><![CDATA[");
		sb.append(getRollNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MobileNo</column-name><column-value><![CDATA[");
		sb.append(getMobileNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Dept</column-name><column-value><![CDATA[");
		sb.append(getDept());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = OccNew.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			OccNew.class
		};
	private long _OCCID;
	private long _ListID;
	private String _ListName;
	private String _RollNo;
	private String _Name;
	private long _MobileNo;
	private String _Email;
	private String _Dept;
	private OccNew _escapedModel;
}