/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rinfra.news.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PressNews service. Represents a row in the &quot;Rinfra_news&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rinfra.news.model.impl.PressNewsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rinfra.news.model.impl.PressNewsImpl}.
 * </p>
 *
 * @author Vipin Singh
 * @see PressNews
 * @see com.rinfra.news.model.impl.PressNewsImpl
 * @see com.rinfra.news.model.impl.PressNewsModelImpl
 * @generated
 */
@ProviderType
public interface PressNewsModel extends BaseModel<PressNews> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a press news model instance should use the {@link PressNews} interface instead.
	 */

	/**
	 * Returns the primary key of this press news.
	 *
	 * @return the primary key of this press news
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this press news.
	 *
	 * @param primaryKey the primary key of this press news
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the news ID of this press news.
	 *
	 * @return the news ID of this press news
	 */
	public long getNewsId();

	/**
	 * Sets the news ID of this press news.
	 *
	 * @param newsId the news ID of this press news
	 */
	public void setNewsId(long newsId);

	/**
	 * Returns the head line of this press news.
	 *
	 * @return the head line of this press news
	 */
	@AutoEscape
	public String getHeadLine();

	/**
	 * Sets the head line of this press news.
	 *
	 * @param headLine the head line of this press news
	 */
	public void setHeadLine(String headLine);

	/**
	 * Returns the publication of this press news.
	 *
	 * @return the publication of this press news
	 */
	@AutoEscape
	public String getPublication();

	/**
	 * Sets the publication of this press news.
	 *
	 * @param publication the publication of this press news
	 */
	public void setPublication(String publication);

	/**
	 * Returns the download url of this press news.
	 *
	 * @return the download url of this press news
	 */
	@AutoEscape
	public String getDownloadUrl();

	/**
	 * Sets the download url of this press news.
	 *
	 * @param downloadUrl the download url of this press news
	 */
	public void setDownloadUrl(String downloadUrl);

	/**
	 * Returns the file name of this press news.
	 *
	 * @return the file name of this press news
	 */
	@AutoEscape
	public String getFileName();

	/**
	 * Sets the file name of this press news.
	 *
	 * @param fileName the file name of this press news
	 */
	public void setFileName(String fileName);

	/**
	 * Returns the date of this press news.
	 *
	 * @return the date of this press news
	 */
	public Date getDate();

	/**
	 * Sets the date of this press news.
	 *
	 * @param date the date of this press news
	 */
	public void setDate(Date date);

	/**
	 * Returns the year of this press news.
	 *
	 * @return the year of this press news
	 */
	public int getYear();

	/**
	 * Sets the year of this press news.
	 *
	 * @param year the year of this press news
	 */
	public void setYear(int year);

	/**
	 * Returns the month of this press news.
	 *
	 * @return the month of this press news
	 */
	public int getMonth();

	/**
	 * Sets the month of this press news.
	 *
	 * @param month the month of this press news
	 */
	public void setMonth(int month);

	/**
	 * Returns the show of this press news.
	 *
	 * @return the show of this press news
	 */
	@AutoEscape
	public String getShow();

	/**
	 * Sets the show of this press news.
	 *
	 * @param show the show of this press news
	 */
	public void setShow(String show);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PressNews pressNews);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PressNews> toCacheModel();

	@Override
	public PressNews toEscapedModel();

	@Override
	public PressNews toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}