/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rinfra.unpaid.unclaimed.devidend.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.rinfra.unpaid.unclaimed.devidend.model.UnpaidUnclaimedDevidend;
import com.rinfra.unpaid.unclaimed.devidend.model.UnpaidUnclaimedDevidendModel;
import com.rinfra.unpaid.unclaimed.devidend.model.UnpaidUnclaimedDevidendSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the UnpaidUnclaimedDevidend service. Represents a row in the &quot;UNPAID_DIVIDEND_FY_2018&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link UnpaidUnclaimedDevidendModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UnpaidUnclaimedDevidendImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UnpaidUnclaimedDevidendImpl
 * @see UnpaidUnclaimedDevidend
 * @see UnpaidUnclaimedDevidendModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class UnpaidUnclaimedDevidendModelImpl extends BaseModelImpl<UnpaidUnclaimedDevidend>
	implements UnpaidUnclaimedDevidendModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a unpaid unclaimed devidend model instance should use the {@link UnpaidUnclaimedDevidend} interface instead.
	 */
	public static final String TABLE_NAME = "UNPAID_DIVIDEND_FY_2018";
	public static final Object[][] TABLE_COLUMNS = {
			{ "SRNO", Types.BIGINT },
			{ "FIRST_NAME", Types.VARCHAR },
			{ "MIDDLE_NAME", Types.VARCHAR },
			{ "LAST_NAME", Types.VARCHAR },
			{ "FATHER_HUSBAND_FIRST_NAME", Types.VARCHAR },
			{ "FATHER_HUSBAND_MIDDLE_NAME", Types.VARCHAR },
			{ "FATHER_HUSBAND_LAST_NAME", Types.VARCHAR },
			{ "ADDRESS", Types.VARCHAR },
			{ "COUNTRY", Types.VARCHAR },
			{ "STATE", Types.VARCHAR },
			{ "DISTRICT", Types.VARCHAR },
			{ "PIN_CODE", Types.BIGINT },
			{ "FOLIO_NO_OF_ITIES", Types.VARCHAR },
			{ "INVESTMENT_TYPE", Types.VARCHAR },
			{ "AMOUNT_DUE_IN_RS", Types.DOUBLE },
			{ "PROPOSED_DATE_TRANSFER_IPEF", Types.TIMESTAMP },
			{ "CREATEDATE", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("SRNO", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FIRST_NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MIDDLE_NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("LAST_NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FATHER_HUSBAND_FIRST_NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FATHER_HUSBAND_MIDDLE_NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FATHER_HUSBAND_LAST_NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ADDRESS", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("COUNTRY", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("STATE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DISTRICT", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("PIN_CODE", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FOLIO_NO_OF_ITIES", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("INVESTMENT_TYPE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("AMOUNT_DUE_IN_RS", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("PROPOSED_DATE_TRANSFER_IPEF", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CREATEDATE", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table UNPAID_DIVIDEND_FY_2018 (SRNO LONG not null primary key,FIRST_NAME VARCHAR(75) null,MIDDLE_NAME VARCHAR(75) null,LAST_NAME VARCHAR(75) null,FATHER_HUSBAND_FIRST_NAME VARCHAR(75) null,FATHER_HUSBAND_MIDDLE_NAME VARCHAR(75) null,FATHER_HUSBAND_LAST_NAME VARCHAR(75) null,ADDRESS VARCHAR(75) null,COUNTRY VARCHAR(75) null,STATE VARCHAR(75) null,DISTRICT VARCHAR(75) null,PIN_CODE LONG,FOLIO_NO_OF_ITIES VARCHAR(75) null,INVESTMENT_TYPE VARCHAR(75) null,AMOUNT_DUE_IN_RS DOUBLE,PROPOSED_DATE_TRANSFER_IPEF DATE null,CREATEDATE DATE null)";
	public static final String TABLE_SQL_DROP = "drop table UNPAID_DIVIDEND_FY_2018";
	public static final String ORDER_BY_JPQL = " ORDER BY unpaidUnclaimedDevidend.SRNO ASC";
	public static final String ORDER_BY_SQL = " ORDER BY UNPAID_DIVIDEND_FY_2018.SRNO ASC";
	public static final String DATA_SOURCE = "extDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.rinfra.unpaid.unclaimed.devidend.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rinfra.unpaid.unclaimed.devidend.model.UnpaidUnclaimedDevidend"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.rinfra.unpaid.unclaimed.devidend.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rinfra.unpaid.unclaimed.devidend.model.UnpaidUnclaimedDevidend"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static UnpaidUnclaimedDevidend toModel(
		UnpaidUnclaimedDevidendSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		UnpaidUnclaimedDevidend model = new UnpaidUnclaimedDevidendImpl();

		model.setSRNO(soapModel.getSRNO());
		model.setFIRST_NAME(soapModel.getFIRST_NAME());
		model.setMIDDLE_NAME(soapModel.getMIDDLE_NAME());
		model.setLAST_NAME(soapModel.getLAST_NAME());
		model.setFATHER_HUSBAND_FIRST_NAME(soapModel.getFATHER_HUSBAND_FIRST_NAME());
		model.setFATHER_HUSBAND_MIDDLE_NAME(soapModel.getFATHER_HUSBAND_MIDDLE_NAME());
		model.setFATHER_HUSBAND_LAST_NAME(soapModel.getFATHER_HUSBAND_LAST_NAME());
		model.setADDRESS(soapModel.getADDRESS());
		model.setCOUNTRY(soapModel.getCOUNTRY());
		model.setSTATE(soapModel.getSTATE());
		model.setDISTRICT(soapModel.getDISTRICT());
		model.setPIN_CODE(soapModel.getPIN_CODE());
		model.setFOLIO_NO_OF_ITIES(soapModel.getFOLIO_NO_OF_ITIES());
		model.setINVESTMENT_TYPE(soapModel.getINVESTMENT_TYPE());
		model.setAMOUNT_DUE_IN_RS(soapModel.getAMOUNT_DUE_IN_RS());
		model.setPROPOSED_DATE_TRANSFER_IPEF(soapModel.getPROPOSED_DATE_TRANSFER_IPEF());
		model.setCREATEDATE(soapModel.getCREATEDATE());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<UnpaidUnclaimedDevidend> toModels(
		UnpaidUnclaimedDevidendSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<UnpaidUnclaimedDevidend> models = new ArrayList<UnpaidUnclaimedDevidend>(soapModels.length);

		for (UnpaidUnclaimedDevidendSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.rinfra.unpaid.unclaimed.devidend.service.util.ServiceProps.get(
				"lock.expiration.time.com.rinfra.unpaid.unclaimed.devidend.model.UnpaidUnclaimedDevidend"));

	public UnpaidUnclaimedDevidendModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _SRNO;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSRNO(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _SRNO;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UnpaidUnclaimedDevidend.class;
	}

	@Override
	public String getModelClassName() {
		return UnpaidUnclaimedDevidend.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("SRNO", getSRNO());
		attributes.put("FIRST_NAME", getFIRST_NAME());
		attributes.put("MIDDLE_NAME", getMIDDLE_NAME());
		attributes.put("LAST_NAME", getLAST_NAME());
		attributes.put("FATHER_HUSBAND_FIRST_NAME",
			getFATHER_HUSBAND_FIRST_NAME());
		attributes.put("FATHER_HUSBAND_MIDDLE_NAME",
			getFATHER_HUSBAND_MIDDLE_NAME());
		attributes.put("FATHER_HUSBAND_LAST_NAME", getFATHER_HUSBAND_LAST_NAME());
		attributes.put("ADDRESS", getADDRESS());
		attributes.put("COUNTRY", getCOUNTRY());
		attributes.put("STATE", getSTATE());
		attributes.put("DISTRICT", getDISTRICT());
		attributes.put("PIN_CODE", getPIN_CODE());
		attributes.put("FOLIO_NO_OF_ITIES", getFOLIO_NO_OF_ITIES());
		attributes.put("INVESTMENT_TYPE", getINVESTMENT_TYPE());
		attributes.put("AMOUNT_DUE_IN_RS", getAMOUNT_DUE_IN_RS());
		attributes.put("PROPOSED_DATE_TRANSFER_IPEF",
			getPROPOSED_DATE_TRANSFER_IPEF());
		attributes.put("CREATEDATE", getCREATEDATE());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long SRNO = (Long)attributes.get("SRNO");

		if (SRNO != null) {
			setSRNO(SRNO);
		}

		String FIRST_NAME = (String)attributes.get("FIRST_NAME");

		if (FIRST_NAME != null) {
			setFIRST_NAME(FIRST_NAME);
		}

		String MIDDLE_NAME = (String)attributes.get("MIDDLE_NAME");

		if (MIDDLE_NAME != null) {
			setMIDDLE_NAME(MIDDLE_NAME);
		}

		String LAST_NAME = (String)attributes.get("LAST_NAME");

		if (LAST_NAME != null) {
			setLAST_NAME(LAST_NAME);
		}

		String FATHER_HUSBAND_FIRST_NAME = (String)attributes.get(
				"FATHER_HUSBAND_FIRST_NAME");

		if (FATHER_HUSBAND_FIRST_NAME != null) {
			setFATHER_HUSBAND_FIRST_NAME(FATHER_HUSBAND_FIRST_NAME);
		}

		String FATHER_HUSBAND_MIDDLE_NAME = (String)attributes.get(
				"FATHER_HUSBAND_MIDDLE_NAME");

		if (FATHER_HUSBAND_MIDDLE_NAME != null) {
			setFATHER_HUSBAND_MIDDLE_NAME(FATHER_HUSBAND_MIDDLE_NAME);
		}

		String FATHER_HUSBAND_LAST_NAME = (String)attributes.get(
				"FATHER_HUSBAND_LAST_NAME");

		if (FATHER_HUSBAND_LAST_NAME != null) {
			setFATHER_HUSBAND_LAST_NAME(FATHER_HUSBAND_LAST_NAME);
		}

		String ADDRESS = (String)attributes.get("ADDRESS");

		if (ADDRESS != null) {
			setADDRESS(ADDRESS);
		}

		String COUNTRY = (String)attributes.get("COUNTRY");

		if (COUNTRY != null) {
			setCOUNTRY(COUNTRY);
		}

		String STATE = (String)attributes.get("STATE");

		if (STATE != null) {
			setSTATE(STATE);
		}

		String DISTRICT = (String)attributes.get("DISTRICT");

		if (DISTRICT != null) {
			setDISTRICT(DISTRICT);
		}

		Long PIN_CODE = (Long)attributes.get("PIN_CODE");

		if (PIN_CODE != null) {
			setPIN_CODE(PIN_CODE);
		}

		String FOLIO_NO_OF_ITIES = (String)attributes.get("FOLIO_NO_OF_ITIES");

		if (FOLIO_NO_OF_ITIES != null) {
			setFOLIO_NO_OF_ITIES(FOLIO_NO_OF_ITIES);
		}

		String INVESTMENT_TYPE = (String)attributes.get("INVESTMENT_TYPE");

		if (INVESTMENT_TYPE != null) {
			setINVESTMENT_TYPE(INVESTMENT_TYPE);
		}

		Double AMOUNT_DUE_IN_RS = (Double)attributes.get("AMOUNT_DUE_IN_RS");

		if (AMOUNT_DUE_IN_RS != null) {
			setAMOUNT_DUE_IN_RS(AMOUNT_DUE_IN_RS);
		}

		Date PROPOSED_DATE_TRANSFER_IPEF = (Date)attributes.get(
				"PROPOSED_DATE_TRANSFER_IPEF");

		if (PROPOSED_DATE_TRANSFER_IPEF != null) {
			setPROPOSED_DATE_TRANSFER_IPEF(PROPOSED_DATE_TRANSFER_IPEF);
		}

		Date CREATEDATE = (Date)attributes.get("CREATEDATE");

		if (CREATEDATE != null) {
			setCREATEDATE(CREATEDATE);
		}
	}

	@JSON
	@Override
	public long getSRNO() {
		return _SRNO;
	}

	@Override
	public void setSRNO(long SRNO) {
		_SRNO = SRNO;
	}

	@JSON
	@Override
	public String getFIRST_NAME() {
		if (_FIRST_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _FIRST_NAME;
		}
	}

	@Override
	public void setFIRST_NAME(String FIRST_NAME) {
		_FIRST_NAME = FIRST_NAME;
	}

	@JSON
	@Override
	public String getMIDDLE_NAME() {
		if (_MIDDLE_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _MIDDLE_NAME;
		}
	}

	@Override
	public void setMIDDLE_NAME(String MIDDLE_NAME) {
		_MIDDLE_NAME = MIDDLE_NAME;
	}

	@JSON
	@Override
	public String getLAST_NAME() {
		if (_LAST_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _LAST_NAME;
		}
	}

	@Override
	public void setLAST_NAME(String LAST_NAME) {
		_LAST_NAME = LAST_NAME;
	}

	@JSON
	@Override
	public String getFATHER_HUSBAND_FIRST_NAME() {
		if (_FATHER_HUSBAND_FIRST_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _FATHER_HUSBAND_FIRST_NAME;
		}
	}

	@Override
	public void setFATHER_HUSBAND_FIRST_NAME(String FATHER_HUSBAND_FIRST_NAME) {
		_FATHER_HUSBAND_FIRST_NAME = FATHER_HUSBAND_FIRST_NAME;
	}

	@JSON
	@Override
	public String getFATHER_HUSBAND_MIDDLE_NAME() {
		if (_FATHER_HUSBAND_MIDDLE_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _FATHER_HUSBAND_MIDDLE_NAME;
		}
	}

	@Override
	public void setFATHER_HUSBAND_MIDDLE_NAME(String FATHER_HUSBAND_MIDDLE_NAME) {
		_FATHER_HUSBAND_MIDDLE_NAME = FATHER_HUSBAND_MIDDLE_NAME;
	}

	@JSON
	@Override
	public String getFATHER_HUSBAND_LAST_NAME() {
		if (_FATHER_HUSBAND_LAST_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _FATHER_HUSBAND_LAST_NAME;
		}
	}

	@Override
	public void setFATHER_HUSBAND_LAST_NAME(String FATHER_HUSBAND_LAST_NAME) {
		_FATHER_HUSBAND_LAST_NAME = FATHER_HUSBAND_LAST_NAME;
	}

	@JSON
	@Override
	public String getADDRESS() {
		if (_ADDRESS == null) {
			return StringPool.BLANK;
		}
		else {
			return _ADDRESS;
		}
	}

	@Override
	public void setADDRESS(String ADDRESS) {
		_ADDRESS = ADDRESS;
	}

	@JSON
	@Override
	public String getCOUNTRY() {
		if (_COUNTRY == null) {
			return StringPool.BLANK;
		}
		else {
			return _COUNTRY;
		}
	}

	@Override
	public void setCOUNTRY(String COUNTRY) {
		_COUNTRY = COUNTRY;
	}

	@JSON
	@Override
	public String getSTATE() {
		if (_STATE == null) {
			return StringPool.BLANK;
		}
		else {
			return _STATE;
		}
	}

	@Override
	public void setSTATE(String STATE) {
		_STATE = STATE;
	}

	@JSON
	@Override
	public String getDISTRICT() {
		if (_DISTRICT == null) {
			return StringPool.BLANK;
		}
		else {
			return _DISTRICT;
		}
	}

	@Override
	public void setDISTRICT(String DISTRICT) {
		_DISTRICT = DISTRICT;
	}

	@JSON
	@Override
	public long getPIN_CODE() {
		return _PIN_CODE;
	}

	@Override
	public void setPIN_CODE(long PIN_CODE) {
		_PIN_CODE = PIN_CODE;
	}

	@JSON
	@Override
	public String getFOLIO_NO_OF_ITIES() {
		if (_FOLIO_NO_OF_ITIES == null) {
			return StringPool.BLANK;
		}
		else {
			return _FOLIO_NO_OF_ITIES;
		}
	}

	@Override
	public void setFOLIO_NO_OF_ITIES(String FOLIO_NO_OF_ITIES) {
		_FOLIO_NO_OF_ITIES = FOLIO_NO_OF_ITIES;
	}

	@JSON
	@Override
	public String getINVESTMENT_TYPE() {
		if (_INVESTMENT_TYPE == null) {
			return StringPool.BLANK;
		}
		else {
			return _INVESTMENT_TYPE;
		}
	}

	@Override
	public void setINVESTMENT_TYPE(String INVESTMENT_TYPE) {
		_INVESTMENT_TYPE = INVESTMENT_TYPE;
	}

	@JSON
	@Override
	public double getAMOUNT_DUE_IN_RS() {
		return _AMOUNT_DUE_IN_RS;
	}

	@Override
	public void setAMOUNT_DUE_IN_RS(double AMOUNT_DUE_IN_RS) {
		_AMOUNT_DUE_IN_RS = AMOUNT_DUE_IN_RS;
	}

	@JSON
	@Override
	public Date getPROPOSED_DATE_TRANSFER_IPEF() {
		return _PROPOSED_DATE_TRANSFER_IPEF;
	}

	@Override
	public void setPROPOSED_DATE_TRANSFER_IPEF(Date PROPOSED_DATE_TRANSFER_IPEF) {
		_PROPOSED_DATE_TRANSFER_IPEF = PROPOSED_DATE_TRANSFER_IPEF;
	}

	@JSON
	@Override
	public Date getCREATEDATE() {
		return _CREATEDATE;
	}

	@Override
	public void setCREATEDATE(Date CREATEDATE) {
		_CREATEDATE = CREATEDATE;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			UnpaidUnclaimedDevidend.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UnpaidUnclaimedDevidend toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (UnpaidUnclaimedDevidend)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UnpaidUnclaimedDevidendImpl unpaidUnclaimedDevidendImpl = new UnpaidUnclaimedDevidendImpl();

		unpaidUnclaimedDevidendImpl.setSRNO(getSRNO());
		unpaidUnclaimedDevidendImpl.setFIRST_NAME(getFIRST_NAME());
		unpaidUnclaimedDevidendImpl.setMIDDLE_NAME(getMIDDLE_NAME());
		unpaidUnclaimedDevidendImpl.setLAST_NAME(getLAST_NAME());
		unpaidUnclaimedDevidendImpl.setFATHER_HUSBAND_FIRST_NAME(getFATHER_HUSBAND_FIRST_NAME());
		unpaidUnclaimedDevidendImpl.setFATHER_HUSBAND_MIDDLE_NAME(getFATHER_HUSBAND_MIDDLE_NAME());
		unpaidUnclaimedDevidendImpl.setFATHER_HUSBAND_LAST_NAME(getFATHER_HUSBAND_LAST_NAME());
		unpaidUnclaimedDevidendImpl.setADDRESS(getADDRESS());
		unpaidUnclaimedDevidendImpl.setCOUNTRY(getCOUNTRY());
		unpaidUnclaimedDevidendImpl.setSTATE(getSTATE());
		unpaidUnclaimedDevidendImpl.setDISTRICT(getDISTRICT());
		unpaidUnclaimedDevidendImpl.setPIN_CODE(getPIN_CODE());
		unpaidUnclaimedDevidendImpl.setFOLIO_NO_OF_ITIES(getFOLIO_NO_OF_ITIES());
		unpaidUnclaimedDevidendImpl.setINVESTMENT_TYPE(getINVESTMENT_TYPE());
		unpaidUnclaimedDevidendImpl.setAMOUNT_DUE_IN_RS(getAMOUNT_DUE_IN_RS());
		unpaidUnclaimedDevidendImpl.setPROPOSED_DATE_TRANSFER_IPEF(getPROPOSED_DATE_TRANSFER_IPEF());
		unpaidUnclaimedDevidendImpl.setCREATEDATE(getCREATEDATE());

		unpaidUnclaimedDevidendImpl.resetOriginalValues();

		return unpaidUnclaimedDevidendImpl;
	}

	@Override
	public int compareTo(UnpaidUnclaimedDevidend unpaidUnclaimedDevidend) {
		long primaryKey = unpaidUnclaimedDevidend.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof UnpaidUnclaimedDevidend)) {
			return false;
		}

		UnpaidUnclaimedDevidend unpaidUnclaimedDevidend = (UnpaidUnclaimedDevidend)obj;

		long primaryKey = unpaidUnclaimedDevidend.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<UnpaidUnclaimedDevidend> toCacheModel() {
		UnpaidUnclaimedDevidendCacheModel unpaidUnclaimedDevidendCacheModel = new UnpaidUnclaimedDevidendCacheModel();

		unpaidUnclaimedDevidendCacheModel.SRNO = getSRNO();

		unpaidUnclaimedDevidendCacheModel.FIRST_NAME = getFIRST_NAME();

		String FIRST_NAME = unpaidUnclaimedDevidendCacheModel.FIRST_NAME;

		if ((FIRST_NAME != null) && (FIRST_NAME.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.FIRST_NAME = null;
		}

		unpaidUnclaimedDevidendCacheModel.MIDDLE_NAME = getMIDDLE_NAME();

		String MIDDLE_NAME = unpaidUnclaimedDevidendCacheModel.MIDDLE_NAME;

		if ((MIDDLE_NAME != null) && (MIDDLE_NAME.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.MIDDLE_NAME = null;
		}

		unpaidUnclaimedDevidendCacheModel.LAST_NAME = getLAST_NAME();

		String LAST_NAME = unpaidUnclaimedDevidendCacheModel.LAST_NAME;

		if ((LAST_NAME != null) && (LAST_NAME.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.LAST_NAME = null;
		}

		unpaidUnclaimedDevidendCacheModel.FATHER_HUSBAND_FIRST_NAME = getFATHER_HUSBAND_FIRST_NAME();

		String FATHER_HUSBAND_FIRST_NAME = unpaidUnclaimedDevidendCacheModel.FATHER_HUSBAND_FIRST_NAME;

		if ((FATHER_HUSBAND_FIRST_NAME != null) &&
				(FATHER_HUSBAND_FIRST_NAME.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.FATHER_HUSBAND_FIRST_NAME = null;
		}

		unpaidUnclaimedDevidendCacheModel.FATHER_HUSBAND_MIDDLE_NAME = getFATHER_HUSBAND_MIDDLE_NAME();

		String FATHER_HUSBAND_MIDDLE_NAME = unpaidUnclaimedDevidendCacheModel.FATHER_HUSBAND_MIDDLE_NAME;

		if ((FATHER_HUSBAND_MIDDLE_NAME != null) &&
				(FATHER_HUSBAND_MIDDLE_NAME.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.FATHER_HUSBAND_MIDDLE_NAME = null;
		}

		unpaidUnclaimedDevidendCacheModel.FATHER_HUSBAND_LAST_NAME = getFATHER_HUSBAND_LAST_NAME();

		String FATHER_HUSBAND_LAST_NAME = unpaidUnclaimedDevidendCacheModel.FATHER_HUSBAND_LAST_NAME;

		if ((FATHER_HUSBAND_LAST_NAME != null) &&
				(FATHER_HUSBAND_LAST_NAME.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.FATHER_HUSBAND_LAST_NAME = null;
		}

		unpaidUnclaimedDevidendCacheModel.ADDRESS = getADDRESS();

		String ADDRESS = unpaidUnclaimedDevidendCacheModel.ADDRESS;

		if ((ADDRESS != null) && (ADDRESS.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.ADDRESS = null;
		}

		unpaidUnclaimedDevidendCacheModel.COUNTRY = getCOUNTRY();

		String COUNTRY = unpaidUnclaimedDevidendCacheModel.COUNTRY;

		if ((COUNTRY != null) && (COUNTRY.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.COUNTRY = null;
		}

		unpaidUnclaimedDevidendCacheModel.STATE = getSTATE();

		String STATE = unpaidUnclaimedDevidendCacheModel.STATE;

		if ((STATE != null) && (STATE.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.STATE = null;
		}

		unpaidUnclaimedDevidendCacheModel.DISTRICT = getDISTRICT();

		String DISTRICT = unpaidUnclaimedDevidendCacheModel.DISTRICT;

		if ((DISTRICT != null) && (DISTRICT.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.DISTRICT = null;
		}

		unpaidUnclaimedDevidendCacheModel.PIN_CODE = getPIN_CODE();

		unpaidUnclaimedDevidendCacheModel.FOLIO_NO_OF_ITIES = getFOLIO_NO_OF_ITIES();

		String FOLIO_NO_OF_ITIES = unpaidUnclaimedDevidendCacheModel.FOLIO_NO_OF_ITIES;

		if ((FOLIO_NO_OF_ITIES != null) && (FOLIO_NO_OF_ITIES.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.FOLIO_NO_OF_ITIES = null;
		}

		unpaidUnclaimedDevidendCacheModel.INVESTMENT_TYPE = getINVESTMENT_TYPE();

		String INVESTMENT_TYPE = unpaidUnclaimedDevidendCacheModel.INVESTMENT_TYPE;

		if ((INVESTMENT_TYPE != null) && (INVESTMENT_TYPE.length() == 0)) {
			unpaidUnclaimedDevidendCacheModel.INVESTMENT_TYPE = null;
		}

		unpaidUnclaimedDevidendCacheModel.AMOUNT_DUE_IN_RS = getAMOUNT_DUE_IN_RS();

		Date PROPOSED_DATE_TRANSFER_IPEF = getPROPOSED_DATE_TRANSFER_IPEF();

		if (PROPOSED_DATE_TRANSFER_IPEF != null) {
			unpaidUnclaimedDevidendCacheModel.PROPOSED_DATE_TRANSFER_IPEF = PROPOSED_DATE_TRANSFER_IPEF.getTime();
		}
		else {
			unpaidUnclaimedDevidendCacheModel.PROPOSED_DATE_TRANSFER_IPEF = Long.MIN_VALUE;
		}

		Date CREATEDATE = getCREATEDATE();

		if (CREATEDATE != null) {
			unpaidUnclaimedDevidendCacheModel.CREATEDATE = CREATEDATE.getTime();
		}
		else {
			unpaidUnclaimedDevidendCacheModel.CREATEDATE = Long.MIN_VALUE;
		}

		return unpaidUnclaimedDevidendCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(35);

		sb.append("{SRNO=");
		sb.append(getSRNO());
		sb.append(", FIRST_NAME=");
		sb.append(getFIRST_NAME());
		sb.append(", MIDDLE_NAME=");
		sb.append(getMIDDLE_NAME());
		sb.append(", LAST_NAME=");
		sb.append(getLAST_NAME());
		sb.append(", FATHER_HUSBAND_FIRST_NAME=");
		sb.append(getFATHER_HUSBAND_FIRST_NAME());
		sb.append(", FATHER_HUSBAND_MIDDLE_NAME=");
		sb.append(getFATHER_HUSBAND_MIDDLE_NAME());
		sb.append(", FATHER_HUSBAND_LAST_NAME=");
		sb.append(getFATHER_HUSBAND_LAST_NAME());
		sb.append(", ADDRESS=");
		sb.append(getADDRESS());
		sb.append(", COUNTRY=");
		sb.append(getCOUNTRY());
		sb.append(", STATE=");
		sb.append(getSTATE());
		sb.append(", DISTRICT=");
		sb.append(getDISTRICT());
		sb.append(", PIN_CODE=");
		sb.append(getPIN_CODE());
		sb.append(", FOLIO_NO_OF_ITIES=");
		sb.append(getFOLIO_NO_OF_ITIES());
		sb.append(", INVESTMENT_TYPE=");
		sb.append(getINVESTMENT_TYPE());
		sb.append(", AMOUNT_DUE_IN_RS=");
		sb.append(getAMOUNT_DUE_IN_RS());
		sb.append(", PROPOSED_DATE_TRANSFER_IPEF=");
		sb.append(getPROPOSED_DATE_TRANSFER_IPEF());
		sb.append(", CREATEDATE=");
		sb.append(getCREATEDATE());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(55);

		sb.append("<model><model-name>");
		sb.append(
			"com.rinfra.unpaid.unclaimed.devidend.model.UnpaidUnclaimedDevidend");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>SRNO</column-name><column-value><![CDATA[");
		sb.append(getSRNO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FIRST_NAME</column-name><column-value><![CDATA[");
		sb.append(getFIRST_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MIDDLE_NAME</column-name><column-value><![CDATA[");
		sb.append(getMIDDLE_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LAST_NAME</column-name><column-value><![CDATA[");
		sb.append(getLAST_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FATHER_HUSBAND_FIRST_NAME</column-name><column-value><![CDATA[");
		sb.append(getFATHER_HUSBAND_FIRST_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FATHER_HUSBAND_MIDDLE_NAME</column-name><column-value><![CDATA[");
		sb.append(getFATHER_HUSBAND_MIDDLE_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FATHER_HUSBAND_LAST_NAME</column-name><column-value><![CDATA[");
		sb.append(getFATHER_HUSBAND_LAST_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ADDRESS</column-name><column-value><![CDATA[");
		sb.append(getADDRESS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>COUNTRY</column-name><column-value><![CDATA[");
		sb.append(getCOUNTRY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>STATE</column-name><column-value><![CDATA[");
		sb.append(getSTATE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DISTRICT</column-name><column-value><![CDATA[");
		sb.append(getDISTRICT());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PIN_CODE</column-name><column-value><![CDATA[");
		sb.append(getPIN_CODE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FOLIO_NO_OF_ITIES</column-name><column-value><![CDATA[");
		sb.append(getFOLIO_NO_OF_ITIES());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>INVESTMENT_TYPE</column-name><column-value><![CDATA[");
		sb.append(getINVESTMENT_TYPE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>AMOUNT_DUE_IN_RS</column-name><column-value><![CDATA[");
		sb.append(getAMOUNT_DUE_IN_RS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PROPOSED_DATE_TRANSFER_IPEF</column-name><column-value><![CDATA[");
		sb.append(getPROPOSED_DATE_TRANSFER_IPEF());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CREATEDATE</column-name><column-value><![CDATA[");
		sb.append(getCREATEDATE());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = UnpaidUnclaimedDevidend.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			UnpaidUnclaimedDevidend.class
		};
	private long _SRNO;
	private String _FIRST_NAME;
	private String _MIDDLE_NAME;
	private String _LAST_NAME;
	private String _FATHER_HUSBAND_FIRST_NAME;
	private String _FATHER_HUSBAND_MIDDLE_NAME;
	private String _FATHER_HUSBAND_LAST_NAME;
	private String _ADDRESS;
	private String _COUNTRY;
	private String _STATE;
	private String _DISTRICT;
	private long _PIN_CODE;
	private String _FOLIO_NO_OF_ITIES;
	private String _INVESTMENT_TYPE;
	private double _AMOUNT_DUE_IN_RS;
	private Date _PROPOSED_DATE_TRANSFER_IPEF;
	private Date _CREATEDATE;
	private UnpaidUnclaimedDevidend _escapedModel;
}