/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.redlatm.form.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the CandidateForm service. Represents a row in the &quot;CANDIDATE_APPLICATION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.redlatm.form.model.impl.CandidateFormModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.redlatm.form.model.impl.CandidateFormImpl}.
 * </p>
 *
 * @author Mukesh,Vipin
 * @see CandidateForm
 * @see com.redlatm.form.model.impl.CandidateFormImpl
 * @see com.redlatm.form.model.impl.CandidateFormModelImpl
 * @generated
 */
@ProviderType
public interface CandidateFormModel extends BaseModel<CandidateForm> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a candidate form model instance should use the {@link CandidateForm} interface instead.
	 */

	/**
	 * Returns the primary key of this candidate form.
	 *
	 * @return the primary key of this candidate form
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this candidate form.
	 *
	 * @param primaryKey the primary key of this candidate form
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ca ID of this candidate form.
	 *
	 * @return the ca ID of this candidate form
	 */
	public long getCaId();

	/**
	 * Sets the ca ID of this candidate form.
	 *
	 * @param CaId the ca ID of this candidate form
	 */
	public void setCaId(long CaId);

	/**
	 * Returns the first name of this candidate form.
	 *
	 * @return the first name of this candidate form
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this candidate form.
	 *
	 * @param firstName the first name of this candidate form
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the surname of this candidate form.
	 *
	 * @return the surname of this candidate form
	 */
	@AutoEscape
	public String getSurname();

	/**
	 * Sets the surname of this candidate form.
	 *
	 * @param surname the surname of this candidate form
	 */
	public void setSurname(String surname);

	/**
	 * Returns the password of this candidate form.
	 *
	 * @return the password of this candidate form
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this candidate form.
	 *
	 * @param password the password of this candidate form
	 */
	public void setPassword(String password);

	/**
	 * Returns the father_ spouse name of this candidate form.
	 *
	 * @return the father_ spouse name of this candidate form
	 */
	@AutoEscape
	public String getFather_SpouseName();

	/**
	 * Sets the father_ spouse name of this candidate form.
	 *
	 * @param father_SpouseName the father_ spouse name of this candidate form
	 */
	public void setFather_SpouseName(String father_SpouseName);

	/**
	 * Returns the aadhar card no of this candidate form.
	 *
	 * @return the aadhar card no of this candidate form
	 */
	@AutoEscape
	public String getAadharCardNo();

	/**
	 * Sets the aadhar card no of this candidate form.
	 *
	 * @param aadharCardNo the aadhar card no of this candidate form
	 */
	public void setAadharCardNo(String aadharCardNo);

	/**
	 * Returns the pan card no of this candidate form.
	 *
	 * @return the pan card no of this candidate form
	 */
	@AutoEscape
	public String getPanCardNo();

	/**
	 * Sets the pan card no of this candidate form.
	 *
	 * @param panCardNo the pan card no of this candidate form
	 */
	public void setPanCardNo(String panCardNo);

	/**
	 * Returns the bank account no of this candidate form.
	 *
	 * @return the bank account no of this candidate form
	 */
	@AutoEscape
	public String getBankAccountNo();

	/**
	 * Sets the bank account no of this candidate form.
	 *
	 * @param bankAccountNo the bank account no of this candidate form
	 */
	public void setBankAccountNo(String bankAccountNo);

	/**
	 * Returns the employment ex regn no of this candidate form.
	 *
	 * @return the employment ex regn no of this candidate form
	 */
	@AutoEscape
	public String getEmploymentExRegnNo();

	/**
	 * Sets the employment ex regn no of this candidate form.
	 *
	 * @param employmentExRegnNo the employment ex regn no of this candidate form
	 */
	public void setEmploymentExRegnNo(String employmentExRegnNo);

	/**
	 * Returns the date of birth of this candidate form.
	 *
	 * @return the date of birth of this candidate form
	 */
	@AutoEscape
	public String getDateOfBirth();

	/**
	 * Sets the date of birth of this candidate form.
	 *
	 * @param dateOfBirth the date of birth of this candidate form
	 */
	public void setDateOfBirth(String dateOfBirth);

	/**
	 * Returns the native location of this candidate form.
	 *
	 * @return the native location of this candidate form
	 */
	@AutoEscape
	public String getNativeLocation();

	/**
	 * Sets the native location of this candidate form.
	 *
	 * @param nativeLocation the native location of this candidate form
	 */
	public void setNativeLocation(String nativeLocation);

	/**
	 * Returns the mother tongue of this candidate form.
	 *
	 * @return the mother tongue of this candidate form
	 */
	@AutoEscape
	public String getMotherTongue();

	/**
	 * Sets the mother tongue of this candidate form.
	 *
	 * @param motherTongue the mother tongue of this candidate form
	 */
	public void setMotherTongue(String motherTongue);

	/**
	 * Returns the identification mark of this candidate form.
	 *
	 * @return the identification mark of this candidate form
	 */
	@AutoEscape
	public String getIdentificationMark();

	/**
	 * Sets the identification mark of this candidate form.
	 *
	 * @param identificationMark the identification mark of this candidate form
	 */
	public void setIdentificationMark(String identificationMark);

	/**
	 * Returns the domicile of this candidate form.
	 *
	 * @return the domicile of this candidate form
	 */
	@AutoEscape
	public String getDomicile();

	/**
	 * Sets the domicile of this candidate form.
	 *
	 * @param domicile the domicile of this candidate form
	 */
	public void setDomicile(String domicile);

	/**
	 * Returns the languages known of this candidate form.
	 *
	 * @return the languages known of this candidate form
	 */
	@AutoEscape
	public String getLanguagesKnown();

	/**
	 * Sets the languages known of this candidate form.
	 *
	 * @param languagesKnown the languages known of this candidate form
	 */
	public void setLanguagesKnown(String languagesKnown);

	/**
	 * Returns the rel company of this candidate form.
	 *
	 * @return the rel company of this candidate form
	 */
	@AutoEscape
	public String getRelCompany();

	/**
	 * Sets the rel company of this candidate form.
	 *
	 * @param relCompany the rel company of this candidate form
	 */
	public void setRelCompany(String relCompany);

	/**
	 * Returns the rel location of this candidate form.
	 *
	 * @return the rel location of this candidate form
	 */
	@AutoEscape
	public String getRelLocation();

	/**
	 * Sets the rel location of this candidate form.
	 *
	 * @param relLocation the rel location of this candidate form
	 */
	public void setRelLocation(String relLocation);

	/**
	 * Returns the rel role of this candidate form.
	 *
	 * @return the rel role of this candidate form
	 */
	@AutoEscape
	public String getRelRole();

	/**
	 * Sets the rel role of this candidate form.
	 *
	 * @param relRole the rel role of this candidate form
	 */
	public void setRelRole(String relRole);

	/**
	 * Returns the rel from date of this candidate form.
	 *
	 * @return the rel from date of this candidate form
	 */
	@AutoEscape
	public String getRelFromDate();

	/**
	 * Sets the rel from date of this candidate form.
	 *
	 * @param relFromDate the rel from date of this candidate form
	 */
	public void setRelFromDate(String relFromDate);

	/**
	 * Returns the rel to date of this candidate form.
	 *
	 * @return the rel to date of this candidate form
	 */
	@AutoEscape
	public String getRelToDate();

	/**
	 * Sets the rel to date of this candidate form.
	 *
	 * @param relToDate the rel to date of this candidate form
	 */
	public void setRelToDate(String relToDate);

	/**
	 * Returns the rel leaving reason of this candidate form.
	 *
	 * @return the rel leaving reason of this candidate form
	 */
	@AutoEscape
	public String getRelLeavingReason();

	/**
	 * Sets the rel leaving reason of this candidate form.
	 *
	 * @param relLeavingReason the rel leaving reason of this candidate form
	 */
	public void setRelLeavingReason(String relLeavingReason);

	/**
	 * Returns the handicap detail of this candidate form.
	 *
	 * @return the handicap detail of this candidate form
	 */
	@AutoEscape
	public String getHandicapDetail();

	/**
	 * Sets the handicap detail of this candidate form.
	 *
	 * @param handicapDetail the handicap detail of this candidate form
	 */
	public void setHandicapDetail(String handicapDetail);

	/**
	 * Returns the religion of this candidate form.
	 *
	 * @return the religion of this candidate form
	 */
	@AutoEscape
	public String getReligion();

	/**
	 * Sets the religion of this candidate form.
	 *
	 * @param religion the religion of this candidate form
	 */
	public void setReligion(String religion);

	/**
	 * Returns the caste of this candidate form.
	 *
	 * @return the caste of this candidate form
	 */
	@AutoEscape
	public String getCaste();

	/**
	 * Sets the caste of this candidate form.
	 *
	 * @param caste the caste of this candidate form
	 */
	public void setCaste(String caste);

	/**
	 * Returns the sub caste of this candidate form.
	 *
	 * @return the sub caste of this candidate form
	 */
	@AutoEscape
	public String getSubCaste();

	/**
	 * Sets the sub caste of this candidate form.
	 *
	 * @param subCaste the sub caste of this candidate form
	 */
	public void setSubCaste(String subCaste);

	/**
	 * Returns the marital status of this candidate form.
	 *
	 * @return the marital status of this candidate form
	 */
	@AutoEscape
	public String getMaritalStatus();

	/**
	 * Sets the marital status of this candidate form.
	 *
	 * @param maritalStatus the marital status of this candidate form
	 */
	public void setMaritalStatus(String maritalStatus);

	/**
	 * Returns the able to join of this candidate form.
	 *
	 * @return the able to join of this candidate form
	 */
	@AutoEscape
	public String getAbleToJoin();

	/**
	 * Sets the able to join of this candidate form.
	 *
	 * @param ableToJoin the able to join of this candidate form
	 */
	public void setAbleToJoin(String ableToJoin);

	/**
	 * Returns the able to days of this candidate form.
	 *
	 * @return the able to days of this candidate form
	 */
	@AutoEscape
	public String getAbleToDays();

	/**
	 * Sets the able to days of this candidate form.
	 *
	 * @param ableToDays the able to days of this candidate form
	 */
	public void setAbleToDays(String ableToDays);

	/**
	 * Returns the able to month of this candidate form.
	 *
	 * @return the able to month of this candidate form
	 */
	@AutoEscape
	public String getAbleToMonth();

	/**
	 * Sets the able to month of this candidate form.
	 *
	 * @param ableToMonth the able to month of this candidate form
	 */
	public void setAbleToMonth(String ableToMonth);

	/**
	 * Returns the address of this candidate form.
	 *
	 * @return the address of this candidate form
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this candidate form.
	 *
	 * @param address the address of this candidate form
	 */
	public void setAddress(String address);

	/**
	 * Returns the city of this candidate form.
	 *
	 * @return the city of this candidate form
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this candidate form.
	 *
	 * @param city the city of this candidate form
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this candidate form.
	 *
	 * @return the state of this candidate form
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this candidate form.
	 *
	 * @param state the state of this candidate form
	 */
	public void setState(String state);

	/**
	 * Returns the pin of this candidate form.
	 *
	 * @return the pin of this candidate form
	 */
	@AutoEscape
	public String getPin();

	/**
	 * Sets the pin of this candidate form.
	 *
	 * @param pin the pin of this candidate form
	 */
	public void setPin(String pin);

	/**
	 * Returns the email address of this candidate form.
	 *
	 * @return the email address of this candidate form
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this candidate form.
	 *
	 * @param emailAddress the email address of this candidate form
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the alternate email ID of this candidate form.
	 *
	 * @return the alternate email ID of this candidate form
	 */
	@AutoEscape
	public String getAlternateEmailID();

	/**
	 * Sets the alternate email ID of this candidate form.
	 *
	 * @param alternateEmailID the alternate email ID of this candidate form
	 */
	public void setAlternateEmailID(String alternateEmailID);

	/**
	 * Returns the mobile of this candidate form.
	 *
	 * @return the mobile of this candidate form
	 */
	@AutoEscape
	public String getMobile();

	/**
	 * Sets the mobile of this candidate form.
	 *
	 * @param mobile the mobile of this candidate form
	 */
	public void setMobile(String mobile);

	/**
	 * Returns the alternate mobile of this candidate form.
	 *
	 * @return the alternate mobile of this candidate form
	 */
	@AutoEscape
	public String getAlternateMobile();

	/**
	 * Sets the alternate mobile of this candidate form.
	 *
	 * @param alternateMobile the alternate mobile of this candidate form
	 */
	public void setAlternateMobile(String alternateMobile);

	/**
	 * Returns the person alternate no given of this candidate form.
	 *
	 * @return the person alternate no given of this candidate form
	 */
	@AutoEscape
	public String getPersonAlternateNoGiven();

	/**
	 * Sets the person alternate no given of this candidate form.
	 *
	 * @param personAlternateNoGiven the person alternate no given of this candidate form
	 */
	public void setPersonAlternateNoGiven(String personAlternateNoGiven);

	/**
	 * Returns the main qualification of this candidate form.
	 *
	 * @return the main qualification of this candidate form
	 */
	@AutoEscape
	public String getMainQualification();

	/**
	 * Sets the main qualification of this candidate form.
	 *
	 * @param mainQualification the main qualification of this candidate form
	 */
	public void setMainQualification(String mainQualification);

	/**
	 * Returns the specialization of this candidate form.
	 *
	 * @return the specialization of this candidate form
	 */
	@AutoEscape
	public String getSpecialization();

	/**
	 * Sets the specialization of this candidate form.
	 *
	 * @param specialization the specialization of this candidate form
	 */
	public void setSpecialization(String specialization);

	/**
	 * Returns the trade of this candidate form.
	 *
	 * @return the trade of this candidate form
	 */
	@AutoEscape
	public String getTrade();

	/**
	 * Sets the trade of this candidate form.
	 *
	 * @param trade the trade of this candidate form
	 */
	public void setTrade(String trade);

	/**
	 * Returns the total yr experience of this candidate form.
	 *
	 * @return the total yr experience of this candidate form
	 */
	@AutoEscape
	public String getTotalYrExperience();

	/**
	 * Sets the total yr experience of this candidate form.
	 *
	 * @param totalYrExperience the total yr experience of this candidate form
	 */
	public void setTotalYrExperience(String totalYrExperience);

	/**
	 * Returns the skill_ proficiency of this candidate form.
	 *
	 * @return the skill_ proficiency of this candidate form
	 */
	@AutoEscape
	public String getSkill_Proficiency();

	/**
	 * Sets the skill_ proficiency of this candidate form.
	 *
	 * @param skill_Proficiency the skill_ proficiency of this candidate form
	 */
	public void setSkill_Proficiency(String skill_Proficiency);

	/**
	 * Returns the securityclearfrom of this candidate form.
	 *
	 * @return the securityclearfrom of this candidate form
	 */
	@AutoEscape
	public String getSECURITYCLEARFROM();

	/**
	 * Sets the securityclearfrom of this candidate form.
	 *
	 * @param SECURITYCLEARFROM the securityclearfrom of this candidate form
	 */
	public void setSECURITYCLEARFROM(String SECURITYCLEARFROM);

	/**
	 * Returns the securitycleartill of this candidate form.
	 *
	 * @return the securitycleartill of this candidate form
	 */
	@AutoEscape
	public String getSECURITYCLEARTILL();

	/**
	 * Sets the securitycleartill of this candidate form.
	 *
	 * @param SECURITYCLEARTILL the securitycleartill of this candidate form
	 */
	public void setSECURITYCLEARTILL(String SECURITYCLEARTILL);

	/**
	 * Returns the medicalfitdocname of this candidate form.
	 *
	 * @return the medicalfitdocname of this candidate form
	 */
	@AutoEscape
	public String getMEDICALFITDOCNAME();

	/**
	 * Sets the medicalfitdocname of this candidate form.
	 *
	 * @param MEDICALFITDOCNAME the medicalfitdocname of this candidate form
	 */
	public void setMEDICALFITDOCNAME(String MEDICALFITDOCNAME);

	/**
	 * Returns the medicalfitdocaddr of this candidate form.
	 *
	 * @return the medicalfitdocaddr of this candidate form
	 */
	@AutoEscape
	public String getMEDICALFITDOCADDR();

	/**
	 * Sets the medicalfitdocaddr of this candidate form.
	 *
	 * @param MEDICALFITDOCADDR the medicalfitdocaddr of this candidate form
	 */
	public void setMEDICALFITDOCADDR(String MEDICALFITDOCADDR);

	/**
	 * Returns the medicalfitdocregnno of this candidate form.
	 *
	 * @return the medicalfitdocregnno of this candidate form
	 */
	@AutoEscape
	public String getMEDICALFITDOCREGNNO();

	/**
	 * Sets the medicalfitdocregnno of this candidate form.
	 *
	 * @param MEDICALFITDOCREGNNO the medicalfitdocregnno of this candidate form
	 */
	public void setMEDICALFITDOCREGNNO(String MEDICALFITDOCREGNNO);

	/**
	 * Returns the medicalfitdoctill of this candidate form.
	 *
	 * @return the medicalfitdoctill of this candidate form
	 */
	@AutoEscape
	public String getMEDICALFITDOCTILL();

	/**
	 * Sets the medicalfitdoctill of this candidate form.
	 *
	 * @param MEDICALFITDOCTILL the medicalfitdoctill of this candidate form
	 */
	public void setMEDICALFITDOCTILL(String MEDICALFITDOCTILL);

	/**
	 * Returns the current company name of this candidate form.
	 *
	 * @return the current company name of this candidate form
	 */
	@AutoEscape
	public String getCurrentCompanyName();

	/**
	 * Sets the current company name of this candidate form.
	 *
	 * @param currentCompanyName the current company name of this candidate form
	 */
	public void setCurrentCompanyName(String currentCompanyName);

	/**
	 * Returns the current company address of this candidate form.
	 *
	 * @return the current company address of this candidate form
	 */
	@AutoEscape
	public String getCurrentCompanyAddress();

	/**
	 * Sets the current company address of this candidate form.
	 *
	 * @param currentCompanyAddress the current company address of this candidate form
	 */
	public void setCurrentCompanyAddress(String currentCompanyAddress);

	/**
	 * Returns the working since date of this candidate form.
	 *
	 * @return the working since date of this candidate form
	 */
	@AutoEscape
	public String getWorkingSinceDate();

	/**
	 * Sets the working since date of this candidate form.
	 *
	 * @param workingSinceDate the working since date of this candidate form
	 */
	public void setWorkingSinceDate(String workingSinceDate);

	/**
	 * Returns the designation of this candidate form.
	 *
	 * @return the designation of this candidate form
	 */
	@AutoEscape
	public String getDesignation();

	/**
	 * Sets the designation of this candidate form.
	 *
	 * @param designation the designation of this candidate form
	 */
	public void setDesignation(String designation);

	/**
	 * Returns the ctc fixed of this candidate form.
	 *
	 * @return the ctc fixed of this candidate form
	 */
	@AutoEscape
	public String getCTCFixed();

	/**
	 * Sets the ctc fixed of this candidate form.
	 *
	 * @param CTCFixed the ctc fixed of this candidate form
	 */
	public void setCTCFixed(String CTCFixed);

	/**
	 * Returns the ctc variable of this candidate form.
	 *
	 * @return the ctc variable of this candidate form
	 */
	@AutoEscape
	public String getCTCVariable();

	/**
	 * Sets the ctc variable of this candidate form.
	 *
	 * @param CTCVariable the ctc variable of this candidate form
	 */
	public void setCTCVariable(String CTCVariable);

	/**
	 * Returns the ctc total of this candidate form.
	 *
	 * @return the ctc total of this candidate form
	 */
	@AutoEscape
	public String getCTCTotal();

	/**
	 * Sets the ctc total of this candidate form.
	 *
	 * @param CTCTotal the ctc total of this candidate form
	 */
	public void setCTCTotal(String CTCTotal);

	/**
	 * Returns the role of this candidate form.
	 *
	 * @return the role of this candidate form
	 */
	@AutoEscape
	public String getRole();

	/**
	 * Sets the role of this candidate form.
	 *
	 * @param role the role of this candidate form
	 */
	public void setRole(String role);

	/**
	 * Returns the location of this candidate form.
	 *
	 * @return the location of this candidate form
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this candidate form.
	 *
	 * @param location the location of this candidate form
	 */
	public void setLocation(String location);

	/**
	 * Returns the notice period of this candidate form.
	 *
	 * @return the notice period of this candidate form
	 */
	@AutoEscape
	public String getNoticePeriod();

	/**
	 * Sets the notice period of this candidate form.
	 *
	 * @param noticePeriod the notice period of this candidate form
	 */
	public void setNoticePeriod(String noticePeriod);

	/**
	 * Returns the first company name of this candidate form.
	 *
	 * @return the first company name of this candidate form
	 */
	@AutoEscape
	public String getFirstCompanyName();

	/**
	 * Sets the first company name of this candidate form.
	 *
	 * @param firstCompanyName the first company name of this candidate form
	 */
	public void setFirstCompanyName(String firstCompanyName);

	/**
	 * Returns the first from date of this candidate form.
	 *
	 * @return the first from date of this candidate form
	 */
	@AutoEscape
	public String getFirstFromDate();

	/**
	 * Sets the first from date of this candidate form.
	 *
	 * @param firstFromDate the first from date of this candidate form
	 */
	public void setFirstFromDate(String firstFromDate);

	/**
	 * Returns the first to date of this candidate form.
	 *
	 * @return the first to date of this candidate form
	 */
	@AutoEscape
	public String getFirstToDate();

	/**
	 * Sets the first to date of this candidate form.
	 *
	 * @param firstToDate the first to date of this candidate form
	 */
	public void setFirstToDate(String firstToDate);

	/**
	 * Returns the first c location of this candidate form.
	 *
	 * @return the first c location of this candidate form
	 */
	@AutoEscape
	public String getFirstCLocation();

	/**
	 * Sets the first c location of this candidate form.
	 *
	 * @param firstCLocation the first c location of this candidate form
	 */
	public void setFirstCLocation(String firstCLocation);

	/**
	 * Returns the first c designation of this candidate form.
	 *
	 * @return the first c designation of this candidate form
	 */
	@AutoEscape
	public String getFirstCDesignation();

	/**
	 * Sets the first c designation of this candidate form.
	 *
	 * @param firstCDesignation the first c designation of this candidate form
	 */
	public void setFirstCDesignation(String firstCDesignation);

	/**
	 * Returns the first fixed ctc of this candidate form.
	 *
	 * @return the first fixed ctc of this candidate form
	 */
	@AutoEscape
	public String getFirstFixedCTC();

	/**
	 * Sets the first fixed ctc of this candidate form.
	 *
	 * @param firstFixedCTC the first fixed ctc of this candidate form
	 */
	public void setFirstFixedCTC(String firstFixedCTC);

	/**
	 * Returns the first variable ctc of this candidate form.
	 *
	 * @return the first variable ctc of this candidate form
	 */
	@AutoEscape
	public String getFirstVariableCTC();

	/**
	 * Sets the first variable ctc of this candidate form.
	 *
	 * @param firstVariableCTC the first variable ctc of this candidate form
	 */
	public void setFirstVariableCTC(String firstVariableCTC);

	/**
	 * Returns the first total ctc of this candidate form.
	 *
	 * @return the first total ctc of this candidate form
	 */
	@AutoEscape
	public String getFirstTotalCTC();

	/**
	 * Sets the first total ctc of this candidate form.
	 *
	 * @param firstTotalCTC the first total ctc of this candidate form
	 */
	public void setFirstTotalCTC(String firstTotalCTC);

	/**
	 * Returns the first remark if any of this candidate form.
	 *
	 * @return the first remark if any of this candidate form
	 */
	@AutoEscape
	public String getFirstRemarkIfAny();

	/**
	 * Sets the first remark if any of this candidate form.
	 *
	 * @param firstRemarkIfAny the first remark if any of this candidate form
	 */
	public void setFirstRemarkIfAny(String firstRemarkIfAny);

	/**
	 * Returns the secound company name of this candidate form.
	 *
	 * @return the secound company name of this candidate form
	 */
	@AutoEscape
	public String getSecoundCompanyName();

	/**
	 * Sets the secound company name of this candidate form.
	 *
	 * @param secoundCompanyName the secound company name of this candidate form
	 */
	public void setSecoundCompanyName(String secoundCompanyName);

	/**
	 * Returns the secound from date of this candidate form.
	 *
	 * @return the secound from date of this candidate form
	 */
	@AutoEscape
	public String getSecoundFromDate();

	/**
	 * Sets the secound from date of this candidate form.
	 *
	 * @param secoundFromDate the secound from date of this candidate form
	 */
	public void setSecoundFromDate(String secoundFromDate);

	/**
	 * Returns the secound to date of this candidate form.
	 *
	 * @return the secound to date of this candidate form
	 */
	@AutoEscape
	public String getSecoundToDate();

	/**
	 * Sets the secound to date of this candidate form.
	 *
	 * @param secoundToDate the secound to date of this candidate form
	 */
	public void setSecoundToDate(String secoundToDate);

	/**
	 * Returns the secound c location of this candidate form.
	 *
	 * @return the secound c location of this candidate form
	 */
	@AutoEscape
	public String getSecoundCLocation();

	/**
	 * Sets the secound c location of this candidate form.
	 *
	 * @param secoundCLocation the secound c location of this candidate form
	 */
	public void setSecoundCLocation(String secoundCLocation);

	/**
	 * Returns the secound c designation of this candidate form.
	 *
	 * @return the secound c designation of this candidate form
	 */
	@AutoEscape
	public String getSecoundCDesignation();

	/**
	 * Sets the secound c designation of this candidate form.
	 *
	 * @param secoundCDesignation the secound c designation of this candidate form
	 */
	public void setSecoundCDesignation(String secoundCDesignation);

	/**
	 * Returns the secound fixed ctc of this candidate form.
	 *
	 * @return the secound fixed ctc of this candidate form
	 */
	@AutoEscape
	public String getSecoundFixedCTC();

	/**
	 * Sets the secound fixed ctc of this candidate form.
	 *
	 * @param secoundFixedCTC the secound fixed ctc of this candidate form
	 */
	public void setSecoundFixedCTC(String secoundFixedCTC);

	/**
	 * Returns the secound variable ctc of this candidate form.
	 *
	 * @return the secound variable ctc of this candidate form
	 */
	@AutoEscape
	public String getSecoundVariableCTC();

	/**
	 * Sets the secound variable ctc of this candidate form.
	 *
	 * @param secoundVariableCTC the secound variable ctc of this candidate form
	 */
	public void setSecoundVariableCTC(String secoundVariableCTC);

	/**
	 * Returns the secound total ctc of this candidate form.
	 *
	 * @return the secound total ctc of this candidate form
	 */
	@AutoEscape
	public String getSecoundTotalCTC();

	/**
	 * Sets the secound total ctc of this candidate form.
	 *
	 * @param secoundTotalCTC the secound total ctc of this candidate form
	 */
	public void setSecoundTotalCTC(String secoundTotalCTC);

	/**
	 * Returns the secound remark if any of this candidate form.
	 *
	 * @return the secound remark if any of this candidate form
	 */
	@AutoEscape
	public String getSecoundRemarkIfAny();

	/**
	 * Sets the secound remark if any of this candidate form.
	 *
	 * @param secoundRemarkIfAny the secound remark if any of this candidate form
	 */
	public void setSecoundRemarkIfAny(String secoundRemarkIfAny);

	/**
	 * Returns the third company name of this candidate form.
	 *
	 * @return the third company name of this candidate form
	 */
	@AutoEscape
	public String getThirdCompanyName();

	/**
	 * Sets the third company name of this candidate form.
	 *
	 * @param thirdCompanyName the third company name of this candidate form
	 */
	public void setThirdCompanyName(String thirdCompanyName);

	/**
	 * Returns the third from date of this candidate form.
	 *
	 * @return the third from date of this candidate form
	 */
	@AutoEscape
	public String getThirdFromDate();

	/**
	 * Sets the third from date of this candidate form.
	 *
	 * @param thirdFromDate the third from date of this candidate form
	 */
	public void setThirdFromDate(String thirdFromDate);

	/**
	 * Returns the third to date of this candidate form.
	 *
	 * @return the third to date of this candidate form
	 */
	@AutoEscape
	public String getThirdToDate();

	/**
	 * Sets the third to date of this candidate form.
	 *
	 * @param thirdToDate the third to date of this candidate form
	 */
	public void setThirdToDate(String thirdToDate);

	/**
	 * Returns the third c location of this candidate form.
	 *
	 * @return the third c location of this candidate form
	 */
	@AutoEscape
	public String getThirdCLocation();

	/**
	 * Sets the third c location of this candidate form.
	 *
	 * @param thirdCLocation the third c location of this candidate form
	 */
	public void setThirdCLocation(String thirdCLocation);

	/**
	 * Returns the third c designation of this candidate form.
	 *
	 * @return the third c designation of this candidate form
	 */
	@AutoEscape
	public String getThirdCDesignation();

	/**
	 * Sets the third c designation of this candidate form.
	 *
	 * @param thirdCDesignation the third c designation of this candidate form
	 */
	public void setThirdCDesignation(String thirdCDesignation);

	/**
	 * Returns the third fixed ctc of this candidate form.
	 *
	 * @return the third fixed ctc of this candidate form
	 */
	@AutoEscape
	public String getThirdFixedCTC();

	/**
	 * Sets the third fixed ctc of this candidate form.
	 *
	 * @param thirdFixedCTC the third fixed ctc of this candidate form
	 */
	public void setThirdFixedCTC(String thirdFixedCTC);

	/**
	 * Returns the third variable ctc of this candidate form.
	 *
	 * @return the third variable ctc of this candidate form
	 */
	@AutoEscape
	public String getThirdVariableCTC();

	/**
	 * Sets the third variable ctc of this candidate form.
	 *
	 * @param thirdVariableCTC the third variable ctc of this candidate form
	 */
	public void setThirdVariableCTC(String thirdVariableCTC);

	/**
	 * Returns the third total ctc of this candidate form.
	 *
	 * @return the third total ctc of this candidate form
	 */
	@AutoEscape
	public String getThirdTotalCTC();

	/**
	 * Sets the third total ctc of this candidate form.
	 *
	 * @param thirdTotalCTC the third total ctc of this candidate form
	 */
	public void setThirdTotalCTC(String thirdTotalCTC);

	/**
	 * Returns the third remark if any of this candidate form.
	 *
	 * @return the third remark if any of this candidate form
	 */
	@AutoEscape
	public String getThirdRemarkIfAny();

	/**
	 * Sets the third remark if any of this candidate form.
	 *
	 * @param thirdRemarkIfAny the third remark if any of this candidate form
	 */
	public void setThirdRemarkIfAny(String thirdRemarkIfAny);

	/**
	 * Returns the forth company name of this candidate form.
	 *
	 * @return the forth company name of this candidate form
	 */
	@AutoEscape
	public String getForthCompanyName();

	/**
	 * Sets the forth company name of this candidate form.
	 *
	 * @param forthCompanyName the forth company name of this candidate form
	 */
	public void setForthCompanyName(String forthCompanyName);

	/**
	 * Returns the forth from date of this candidate form.
	 *
	 * @return the forth from date of this candidate form
	 */
	@AutoEscape
	public String getForthFromDate();

	/**
	 * Sets the forth from date of this candidate form.
	 *
	 * @param forthFromDate the forth from date of this candidate form
	 */
	public void setForthFromDate(String forthFromDate);

	/**
	 * Returns the forth to date of this candidate form.
	 *
	 * @return the forth to date of this candidate form
	 */
	@AutoEscape
	public String getForthToDate();

	/**
	 * Sets the forth to date of this candidate form.
	 *
	 * @param forthToDate the forth to date of this candidate form
	 */
	public void setForthToDate(String forthToDate);

	/**
	 * Returns the forth c location of this candidate form.
	 *
	 * @return the forth c location of this candidate form
	 */
	@AutoEscape
	public String getForthCLocation();

	/**
	 * Sets the forth c location of this candidate form.
	 *
	 * @param forthCLocation the forth c location of this candidate form
	 */
	public void setForthCLocation(String forthCLocation);

	/**
	 * Returns the forth c designation of this candidate form.
	 *
	 * @return the forth c designation of this candidate form
	 */
	@AutoEscape
	public String getForthCDesignation();

	/**
	 * Sets the forth c designation of this candidate form.
	 *
	 * @param forthCDesignation the forth c designation of this candidate form
	 */
	public void setForthCDesignation(String forthCDesignation);

	/**
	 * Returns the forth fixed ctc of this candidate form.
	 *
	 * @return the forth fixed ctc of this candidate form
	 */
	@AutoEscape
	public String getForthFixedCTC();

	/**
	 * Sets the forth fixed ctc of this candidate form.
	 *
	 * @param forthFixedCTC the forth fixed ctc of this candidate form
	 */
	public void setForthFixedCTC(String forthFixedCTC);

	/**
	 * Returns the forth variable ctc of this candidate form.
	 *
	 * @return the forth variable ctc of this candidate form
	 */
	@AutoEscape
	public String getForthVariableCTC();

	/**
	 * Sets the forth variable ctc of this candidate form.
	 *
	 * @param forthVariableCTC the forth variable ctc of this candidate form
	 */
	public void setForthVariableCTC(String forthVariableCTC);

	/**
	 * Returns the forth total ctc of this candidate form.
	 *
	 * @return the forth total ctc of this candidate form
	 */
	@AutoEscape
	public String getForthTotalCTC();

	/**
	 * Sets the forth total ctc of this candidate form.
	 *
	 * @param forthTotalCTC the forth total ctc of this candidate form
	 */
	public void setForthTotalCTC(String forthTotalCTC);

	/**
	 * Returns the forth remark if any of this candidate form.
	 *
	 * @return the forth remark if any of this candidate form
	 */
	@AutoEscape
	public String getForthRemarkIfAny();

	/**
	 * Sets the forth remark if any of this candidate form.
	 *
	 * @param forthRemarkIfAny the forth remark if any of this candidate form
	 */
	public void setForthRemarkIfAny(String forthRemarkIfAny);

	/**
	 * Returns the fifth company name of this candidate form.
	 *
	 * @return the fifth company name of this candidate form
	 */
	@AutoEscape
	public String getFifthCompanyName();

	/**
	 * Sets the fifth company name of this candidate form.
	 *
	 * @param fifthCompanyName the fifth company name of this candidate form
	 */
	public void setFifthCompanyName(String fifthCompanyName);

	/**
	 * Returns the fifth from date of this candidate form.
	 *
	 * @return the fifth from date of this candidate form
	 */
	@AutoEscape
	public String getFifthFromDate();

	/**
	 * Sets the fifth from date of this candidate form.
	 *
	 * @param fifthFromDate the fifth from date of this candidate form
	 */
	public void setFifthFromDate(String fifthFromDate);

	/**
	 * Returns the fifth to date of this candidate form.
	 *
	 * @return the fifth to date of this candidate form
	 */
	@AutoEscape
	public String getFifthToDate();

	/**
	 * Sets the fifth to date of this candidate form.
	 *
	 * @param fifthToDate the fifth to date of this candidate form
	 */
	public void setFifthToDate(String fifthToDate);

	/**
	 * Returns the fifth c location of this candidate form.
	 *
	 * @return the fifth c location of this candidate form
	 */
	@AutoEscape
	public String getFifthCLocation();

	/**
	 * Sets the fifth c location of this candidate form.
	 *
	 * @param fifthCLocation the fifth c location of this candidate form
	 */
	public void setFifthCLocation(String fifthCLocation);

	/**
	 * Returns the fifth c designation of this candidate form.
	 *
	 * @return the fifth c designation of this candidate form
	 */
	@AutoEscape
	public String getFifthCDesignation();

	/**
	 * Sets the fifth c designation of this candidate form.
	 *
	 * @param fifthCDesignation the fifth c designation of this candidate form
	 */
	public void setFifthCDesignation(String fifthCDesignation);

	/**
	 * Returns the fifth fixed ctc of this candidate form.
	 *
	 * @return the fifth fixed ctc of this candidate form
	 */
	@AutoEscape
	public String getFifthFixedCTC();

	/**
	 * Sets the fifth fixed ctc of this candidate form.
	 *
	 * @param fifthFixedCTC the fifth fixed ctc of this candidate form
	 */
	public void setFifthFixedCTC(String fifthFixedCTC);

	/**
	 * Returns the fifth variable ctc of this candidate form.
	 *
	 * @return the fifth variable ctc of this candidate form
	 */
	@AutoEscape
	public String getFifthVariableCTC();

	/**
	 * Sets the fifth variable ctc of this candidate form.
	 *
	 * @param fifthVariableCTC the fifth variable ctc of this candidate form
	 */
	public void setFifthVariableCTC(String fifthVariableCTC);

	/**
	 * Returns the fifth total ctc of this candidate form.
	 *
	 * @return the fifth total ctc of this candidate form
	 */
	@AutoEscape
	public String getFifthTotalCTC();

	/**
	 * Sets the fifth total ctc of this candidate form.
	 *
	 * @param fifthTotalCTC the fifth total ctc of this candidate form
	 */
	public void setFifthTotalCTC(String fifthTotalCTC);

	/**
	 * Returns the fifth remark if any of this candidate form.
	 *
	 * @return the fifth remark if any of this candidate form
	 */
	@AutoEscape
	public String getFifthRemarkIfAny();

	/**
	 * Sets the fifth remark if any of this candidate form.
	 *
	 * @param fifthRemarkIfAny the fifth remark if any of this candidate form
	 */
	public void setFifthRemarkIfAny(String fifthRemarkIfAny);

	/**
	 * Returns the ssc qualification of this candidate form.
	 *
	 * @return the ssc qualification of this candidate form
	 */
	@AutoEscape
	public String getSSCQualification();

	/**
	 * Sets the ssc qualification of this candidate form.
	 *
	 * @param SSCQualification the ssc qualification of this candidate form
	 */
	public void setSSCQualification(String SSCQualification);

	/**
	 * Returns the ssc university institute of this candidate form.
	 *
	 * @return the ssc university institute of this candidate form
	 */
	@AutoEscape
	public String getSSCUniversityInstitute();

	/**
	 * Sets the ssc university institute of this candidate form.
	 *
	 * @param SSCUniversityInstitute the ssc university institute of this candidate form
	 */
	public void setSSCUniversityInstitute(String SSCUniversityInstitute);

	/**
	 * Returns the ssc year of passing of this candidate form.
	 *
	 * @return the ssc year of passing of this candidate form
	 */
	@AutoEscape
	public String getSSCYearOfPassing();

	/**
	 * Sets the ssc year of passing of this candidate form.
	 *
	 * @param SSCYearOfPassing the ssc year of passing of this candidate form
	 */
	public void setSSCYearOfPassing(String SSCYearOfPassing);

	/**
	 * Returns the ssc grade of this candidate form.
	 *
	 * @return the ssc grade of this candidate form
	 */
	@AutoEscape
	public String getSSCGrade();

	/**
	 * Sets the ssc grade of this candidate form.
	 *
	 * @param SSCGrade the ssc grade of this candidate form
	 */
	public void setSSCGrade(String SSCGrade);

	/**
	 * Returns the hsc university institute of this candidate form.
	 *
	 * @return the hsc university institute of this candidate form
	 */
	@AutoEscape
	public String getHSCUniversityInstitute();

	/**
	 * Sets the hsc university institute of this candidate form.
	 *
	 * @param HSCUniversityInstitute the hsc university institute of this candidate form
	 */
	public void setHSCUniversityInstitute(String HSCUniversityInstitute);

	/**
	 * Returns the hsc qualification of this candidate form.
	 *
	 * @return the hsc qualification of this candidate form
	 */
	@AutoEscape
	public String getHSCQualification();

	/**
	 * Sets the hsc qualification of this candidate form.
	 *
	 * @param HSCQualification the hsc qualification of this candidate form
	 */
	public void setHSCQualification(String HSCQualification);

	/**
	 * Returns the hsc year of passing of this candidate form.
	 *
	 * @return the hsc year of passing of this candidate form
	 */
	@AutoEscape
	public String getHSCYearOfPassing();

	/**
	 * Sets the hsc year of passing of this candidate form.
	 *
	 * @param HSCYearOfPassing the hsc year of passing of this candidate form
	 */
	public void setHSCYearOfPassing(String HSCYearOfPassing);

	/**
	 * Returns the hsc grade of this candidate form.
	 *
	 * @return the hsc grade of this candidate form
	 */
	@AutoEscape
	public String getHSCGrade();

	/**
	 * Sets the hsc grade of this candidate form.
	 *
	 * @param HSCGrade the hsc grade of this candidate form
	 */
	public void setHSCGrade(String HSCGrade);

	/**
	 * Returns the grad university institute of this candidate form.
	 *
	 * @return the grad university institute of this candidate form
	 */
	@AutoEscape
	public String getGradUniversityInstitute();

	/**
	 * Sets the grad university institute of this candidate form.
	 *
	 * @param GradUniversityInstitute the grad university institute of this candidate form
	 */
	public void setGradUniversityInstitute(String GradUniversityInstitute);

	/**
	 * Returns the grad qualification of this candidate form.
	 *
	 * @return the grad qualification of this candidate form
	 */
	@AutoEscape
	public String getGradQualification();

	/**
	 * Sets the grad qualification of this candidate form.
	 *
	 * @param GradQualification the grad qualification of this candidate form
	 */
	public void setGradQualification(String GradQualification);

	/**
	 * Returns the grad year of passing of this candidate form.
	 *
	 * @return the grad year of passing of this candidate form
	 */
	@AutoEscape
	public String getGradYearOfPassing();

	/**
	 * Sets the grad year of passing of this candidate form.
	 *
	 * @param GradYearOfPassing the grad year of passing of this candidate form
	 */
	public void setGradYearOfPassing(String GradYearOfPassing);

	/**
	 * Returns the grad grade of this candidate form.
	 *
	 * @return the grad grade of this candidate form
	 */
	@AutoEscape
	public String getGradGrade();

	/**
	 * Sets the grad grade of this candidate form.
	 *
	 * @param GradGrade the grad grade of this candidate form
	 */
	public void setGradGrade(String GradGrade);

	/**
	 * Returns the pg university institute of this candidate form.
	 *
	 * @return the pg university institute of this candidate form
	 */
	@AutoEscape
	public String getPGUniversityInstitute();

	/**
	 * Sets the pg university institute of this candidate form.
	 *
	 * @param PGUniversityInstitute the pg university institute of this candidate form
	 */
	public void setPGUniversityInstitute(String PGUniversityInstitute);

	/**
	 * Returns the pg qualification of this candidate form.
	 *
	 * @return the pg qualification of this candidate form
	 */
	@AutoEscape
	public String getPGQualification();

	/**
	 * Sets the pg qualification of this candidate form.
	 *
	 * @param PGQualification the pg qualification of this candidate form
	 */
	public void setPGQualification(String PGQualification);

	/**
	 * Returns the pg year of passing of this candidate form.
	 *
	 * @return the pg year of passing of this candidate form
	 */
	@AutoEscape
	public String getPGYearOfPassing();

	/**
	 * Sets the pg year of passing of this candidate form.
	 *
	 * @param PGYearOfPassing the pg year of passing of this candidate form
	 */
	public void setPGYearOfPassing(String PGYearOfPassing);

	/**
	 * Returns the pg grade of this candidate form.
	 *
	 * @return the pg grade of this candidate form
	 */
	@AutoEscape
	public String getPGGrade();

	/**
	 * Sets the pg grade of this candidate form.
	 *
	 * @param PGGrade the pg grade of this candidate form
	 */
	public void setPGGrade(String PGGrade);

	/**
	 * Returns the ph d university institute of this candidate form.
	 *
	 * @return the ph d university institute of this candidate form
	 */
	@AutoEscape
	public String getPhDUniversityInstitute();

	/**
	 * Sets the ph d university institute of this candidate form.
	 *
	 * @param PhDUniversityInstitute the ph d university institute of this candidate form
	 */
	public void setPhDUniversityInstitute(String PhDUniversityInstitute);

	/**
	 * Returns the ph d qualification of this candidate form.
	 *
	 * @return the ph d qualification of this candidate form
	 */
	@AutoEscape
	public String getPhDQualification();

	/**
	 * Sets the ph d qualification of this candidate form.
	 *
	 * @param PhDQualification the ph d qualification of this candidate form
	 */
	public void setPhDQualification(String PhDQualification);

	/**
	 * Returns the ph d year of passing of this candidate form.
	 *
	 * @return the ph d year of passing of this candidate form
	 */
	@AutoEscape
	public String getPhDYearOfPassing();

	/**
	 * Sets the ph d year of passing of this candidate form.
	 *
	 * @param PhDYearOfPassing the ph d year of passing of this candidate form
	 */
	public void setPhDYearOfPassing(String PhDYearOfPassing);

	/**
	 * Returns the ph d grade of this candidate form.
	 *
	 * @return the ph d grade of this candidate form
	 */
	@AutoEscape
	public String getPhDGrade();

	/**
	 * Sets the ph d grade of this candidate form.
	 *
	 * @param PhDGrade the ph d grade of this candidate form
	 */
	public void setPhDGrade(String PhDGrade);

	/**
	 * Returns the other1 university institute of this candidate form.
	 *
	 * @return the other1 university institute of this candidate form
	 */
	@AutoEscape
	public String getOther1UniversityInstitute();

	/**
	 * Sets the other1 university institute of this candidate form.
	 *
	 * @param other1UniversityInstitute the other1 university institute of this candidate form
	 */
	public void setOther1UniversityInstitute(String other1UniversityInstitute);

	/**
	 * Returns the other1 qualification of this candidate form.
	 *
	 * @return the other1 qualification of this candidate form
	 */
	@AutoEscape
	public String getOther1Qualification();

	/**
	 * Sets the other1 qualification of this candidate form.
	 *
	 * @param other1Qualification the other1 qualification of this candidate form
	 */
	public void setOther1Qualification(String other1Qualification);

	/**
	 * Returns the other1 year of passing of this candidate form.
	 *
	 * @return the other1 year of passing of this candidate form
	 */
	@AutoEscape
	public String getOther1YearOfPassing();

	/**
	 * Sets the other1 year of passing of this candidate form.
	 *
	 * @param other1YearOfPassing the other1 year of passing of this candidate form
	 */
	public void setOther1YearOfPassing(String other1YearOfPassing);

	/**
	 * Returns the other1 grade of this candidate form.
	 *
	 * @return the other1 grade of this candidate form
	 */
	@AutoEscape
	public String getOther1Grade();

	/**
	 * Sets the other1 grade of this candidate form.
	 *
	 * @param other1Grade the other1 grade of this candidate form
	 */
	public void setOther1Grade(String other1Grade);

	/**
	 * Returns the other2 university institute of this candidate form.
	 *
	 * @return the other2 university institute of this candidate form
	 */
	@AutoEscape
	public String getOther2UniversityInstitute();

	/**
	 * Sets the other2 university institute of this candidate form.
	 *
	 * @param other2UniversityInstitute the other2 university institute of this candidate form
	 */
	public void setOther2UniversityInstitute(String other2UniversityInstitute);

	/**
	 * Returns the other2 qualification of this candidate form.
	 *
	 * @return the other2 qualification of this candidate form
	 */
	@AutoEscape
	public String getOther2Qualification();

	/**
	 * Sets the other2 qualification of this candidate form.
	 *
	 * @param other2Qualification the other2 qualification of this candidate form
	 */
	public void setOther2Qualification(String other2Qualification);

	/**
	 * Returns the other2 year of passing of this candidate form.
	 *
	 * @return the other2 year of passing of this candidate form
	 */
	@AutoEscape
	public String getOther2YearOfPassing();

	/**
	 * Sets the other2 year of passing of this candidate form.
	 *
	 * @param other2YearOfPassing the other2 year of passing of this candidate form
	 */
	public void setOther2YearOfPassing(String other2YearOfPassing);

	/**
	 * Returns the other2 grade of this candidate form.
	 *
	 * @return the other2 grade of this candidate form
	 */
	@AutoEscape
	public String getOther2Grade();

	/**
	 * Sets the other2 grade of this candidate form.
	 *
	 * @param other2Grade the other2 grade of this candidate form
	 */
	public void setOther2Grade(String other2Grade);

	/**
	 * Returns the other3 university institute of this candidate form.
	 *
	 * @return the other3 university institute of this candidate form
	 */
	@AutoEscape
	public String getOther3UniversityInstitute();

	/**
	 * Sets the other3 university institute of this candidate form.
	 *
	 * @param other3UniversityInstitute the other3 university institute of this candidate form
	 */
	public void setOther3UniversityInstitute(String other3UniversityInstitute);

	/**
	 * Returns the other3 qualification of this candidate form.
	 *
	 * @return the other3 qualification of this candidate form
	 */
	@AutoEscape
	public String getOther3Qualification();

	/**
	 * Sets the other3 qualification of this candidate form.
	 *
	 * @param other3Qualification the other3 qualification of this candidate form
	 */
	public void setOther3Qualification(String other3Qualification);

	/**
	 * Returns the other3 year of passing of this candidate form.
	 *
	 * @return the other3 year of passing of this candidate form
	 */
	@AutoEscape
	public String getOther3YearOfPassing();

	/**
	 * Sets the other3 year of passing of this candidate form.
	 *
	 * @param other3YearOfPassing the other3 year of passing of this candidate form
	 */
	public void setOther3YearOfPassing(String other3YearOfPassing);

	/**
	 * Returns the other3 grade of this candidate form.
	 *
	 * @return the other3 grade of this candidate form
	 */
	@AutoEscape
	public String getOther3Grade();

	/**
	 * Sets the other3 grade of this candidate form.
	 *
	 * @param other3Grade the other3 grade of this candidate form
	 */
	public void setOther3Grade(String other3Grade);

	/**
	 * Returns the uploadfile of this candidate form.
	 *
	 * @return the uploadfile of this candidate form
	 */
	@AutoEscape
	public String getUPLOADFILE();

	/**
	 * Sets the uploadfile of this candidate form.
	 *
	 * @param UPLOADFILE the uploadfile of this candidate form
	 */
	public void setUPLOADFILE(String UPLOADFILE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CandidateForm candidateForm);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CandidateForm> toCacheModel();

	@Override
	public CandidateForm toEscapedModel();

	@Override
	public CandidateForm toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}