create table UNPAID_DIVIDEND_FY_2018 (
	SRNO LONG not null primary key,
	FIRST_NAME VARCHAR(75) null,
	MIDDLE_NAME VARCHAR(75) null,
	LAST_NAME VARCHAR(75) null,
	FATHER_HUSBAND_FIRST_NAME VARCHAR(75) null,
	FATHER_HUSBAND_MIDDLE_NAME VARCHAR(75) null,
	FATHER_HUSBAND_LAST_NAME VARCHAR(75) null,
	ADDRESS VARCHAR(75) null,
	COUNTRY VARCHAR(75) null,
	STATE VARCHAR(75) null,
	DISTRICT VARCHAR(75) null,
	PIN_CODE VARCHAR(75) null,
	FOLIO_NO_OF_ITIES VARCHAR(75) null,
	INVESTMENT_TYPE VARCHAR(75) null,
	AMOUNT_DUE_IN_RS DOUBLE,
	PROPOSED_DATE_TRANSFER_IPEF DATE null,
	CREATEDATE DATE null
);