/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.relieanceada.rinfra.portal.pressRelease.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PressRelease service. Represents a row in the &quot;PRESS_RELEASE_PressRelease&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.relieanceada.rinfra.portal.pressRelease.model.impl.PressReleaseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.relieanceada.rinfra.portal.pressRelease.model.impl.PressReleaseImpl}.
 * </p>
 *
 * @author Vipin Singh
 * @see PressRelease
 * @see com.relieanceada.rinfra.portal.pressRelease.model.impl.PressReleaseImpl
 * @see com.relieanceada.rinfra.portal.pressRelease.model.impl.PressReleaseModelImpl
 * @generated
 */
@ProviderType
public interface PressReleaseModel extends BaseModel<PressRelease> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a press release model instance should use the {@link PressRelease} interface instead.
	 */

	/**
	 * Returns the primary key of this press release.
	 *
	 * @return the primary key of this press release
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this press release.
	 *
	 * @param primaryKey the primary key of this press release
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the press ID of this press release.
	 *
	 * @return the press ID of this press release
	 */
	public long getPressId();

	/**
	 * Sets the press ID of this press release.
	 *
	 * @param pressId the press ID of this press release
	 */
	public void setPressId(long pressId);

	/**
	 * Returns the news year of this press release.
	 *
	 * @return the news year of this press release
	 */
	@AutoEscape
	public String getNewsYear();

	/**
	 * Sets the news year of this press release.
	 *
	 * @param newsYear the news year of this press release
	 */
	public void setNewsYear(String newsYear);

	/**
	 * Returns the news date of this press release.
	 *
	 * @return the news date of this press release
	 */
	public Date getNewsDate();

	/**
	 * Sets the news date of this press release.
	 *
	 * @param newsDate the news date of this press release
	 */
	public void setNewsDate(Date newsDate);

	/**
	 * Returns the heading of this press release.
	 *
	 * @return the heading of this press release
	 */
	@AutoEscape
	public String getHeading();

	/**
	 * Sets the heading of this press release.
	 *
	 * @param heading the heading of this press release
	 */
	public void setHeading(String heading);

	/**
	 * Returns the data of this press release.
	 *
	 * @return the data of this press release
	 */
	@AutoEscape
	public String getData();

	/**
	 * Sets the data of this press release.
	 *
	 * @param data the data of this press release
	 */
	public void setData(String data);

	/**
	 * Returns the description of this press release.
	 *
	 * @return the description of this press release
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this press release.
	 *
	 * @param description the description of this press release
	 */
	public void setDescription(String description);

	/**
	 * Returns the show of this press release.
	 *
	 * @return the show of this press release
	 */
	@AutoEscape
	public String getShow();

	/**
	 * Sets the show of this press release.
	 *
	 * @param show the show of this press release
	 */
	public void setShow(String show);

	/**
	 * Returns the created date of this press release.
	 *
	 * @return the created date of this press release
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this press release.
	 *
	 * @param createdDate the created date of this press release
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the file name of this press release.
	 *
	 * @return the file name of this press release
	 */
	@AutoEscape
	public String getFileName();

	/**
	 * Sets the file name of this press release.
	 *
	 * @param fileName the file name of this press release
	 */
	public void setFileName(String fileName);

	/**
	 * Returns the file url of this press release.
	 *
	 * @return the file url of this press release
	 */
	@AutoEscape
	public String getFileURL();

	/**
	 * Sets the file url of this press release.
	 *
	 * @param fileURL the file url of this press release
	 */
	public void setFileURL(String fileURL);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PressRelease pressRelease);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PressRelease> toCacheModel();

	@Override
	public PressRelease toEscapedModel();

	@Override
	public PressRelease toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}