/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package attendence.rinfra.services.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the AttendenceTransaction service. Represents a row in the &quot;ATTENDENCE_TRANSACTION_TABLE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link attendence.rinfra.services.model.impl.AttendenceTransactionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link attendence.rinfra.services.model.impl.AttendenceTransactionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AttendenceTransaction
 * @see attendence.rinfra.services.model.impl.AttendenceTransactionImpl
 * @see attendence.rinfra.services.model.impl.AttendenceTransactionModelImpl
 * @generated
 */
@ProviderType
public interface AttendenceTransactionModel extends BaseModel<AttendenceTransaction> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a attendence transaction model instance should use the {@link AttendenceTransaction} interface instead.
	 */

	/**
	 * Returns the primary key of this attendence transaction.
	 *
	 * @return the primary key of this attendence transaction
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this attendence transaction.
	 *
	 * @param primaryKey the primary key of this attendence transaction
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the sr no of this attendence transaction.
	 *
	 * @return the sr no of this attendence transaction
	 */
	@AutoEscape
	public String getSrNo();

	/**
	 * Sets the sr no of this attendence transaction.
	 *
	 * @param srNo the sr no of this attendence transaction
	 */
	public void setSrNo(String srNo);

	/**
	 * Returns the employee code of this attendence transaction.
	 *
	 * @return the employee code of this attendence transaction
	 */
	@AutoEscape
	public String getEmployeeCode();

	/**
	 * Sets the employee code of this attendence transaction.
	 *
	 * @param employeeCode the employee code of this attendence transaction
	 */
	public void setEmployeeCode(String employeeCode);

	/**
	 * Returns the employee name of this attendence transaction.
	 *
	 * @return the employee name of this attendence transaction
	 */
	@AutoEscape
	public String getEmployeeName();

	/**
	 * Sets the employee name of this attendence transaction.
	 *
	 * @param employeeName the employee name of this attendence transaction
	 */
	public void setEmployeeName(String employeeName);

	/**
	 * Returns the mobile of this attendence transaction.
	 *
	 * @return the mobile of this attendence transaction
	 */
	@AutoEscape
	public String getMobile();

	/**
	 * Sets the mobile of this attendence transaction.
	 *
	 * @param mobile the mobile of this attendence transaction
	 */
	public void setMobile(String mobile);

	/**
	 * Returns the user defined1 of this attendence transaction.
	 *
	 * @return the user defined1 of this attendence transaction
	 */
	@AutoEscape
	public String getUserDefined1();

	/**
	 * Sets the user defined1 of this attendence transaction.
	 *
	 * @param userDefined1 the user defined1 of this attendence transaction
	 */
	public void setUserDefined1(String userDefined1);

	/**
	 * Returns the user defined2 of this attendence transaction.
	 *
	 * @return the user defined2 of this attendence transaction
	 */
	@AutoEscape
	public String getUserDefined2();

	/**
	 * Sets the user defined2 of this attendence transaction.
	 *
	 * @param userDefined2 the user defined2 of this attendence transaction
	 */
	public void setUserDefined2(String userDefined2);

	/**
	 * Returns the attendence mode of this attendence transaction.
	 *
	 * @return the attendence mode of this attendence transaction
	 */
	@AutoEscape
	public String getAttendenceMode();

	/**
	 * Sets the attendence mode of this attendence transaction.
	 *
	 * @param attendenceMode the attendence mode of this attendence transaction
	 */
	public void setAttendenceMode(String attendenceMode);

	/**
	 * Returns the attendence date time of this attendence transaction.
	 *
	 * @return the attendence date time of this attendence transaction
	 */
	@AutoEscape
	public String getAttendenceDateTime();

	/**
	 * Sets the attendence date time of this attendence transaction.
	 *
	 * @param attendenceDateTime the attendence date time of this attendence transaction
	 */
	public void setAttendenceDateTime(String attendenceDateTime);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		attendence.rinfra.services.model.AttendenceTransaction attendenceTransaction);

	@Override
	public int hashCode();

	@Override
	public CacheModel<attendence.rinfra.services.model.AttendenceTransaction> toCacheModel();

	@Override
	public attendence.rinfra.services.model.AttendenceTransaction toEscapedModel();

	@Override
	public attendence.rinfra.services.model.AttendenceTransaction toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}