/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package attendence.rinfra.services.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the EmpMaster service. Represents a row in the &quot;MASTER_TABLE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link attendence.rinfra.services.model.impl.EmpMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link attendence.rinfra.services.model.impl.EmpMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmpMaster
 * @see attendence.rinfra.services.model.impl.EmpMasterImpl
 * @see attendence.rinfra.services.model.impl.EmpMasterModelImpl
 * @generated
 */
@ProviderType
public interface EmpMasterModel extends BaseModel<EmpMaster> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a emp master model instance should use the {@link EmpMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this emp master.
	 *
	 * @return the primary key of this emp master
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this emp master.
	 *
	 * @param primaryKey the primary key of this emp master
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the employee code of this emp master.
	 *
	 * @return the employee code of this emp master
	 */
	@AutoEscape
	public String getEmployeeCode();

	/**
	 * Sets the employee code of this emp master.
	 *
	 * @param employeeCode the employee code of this emp master
	 */
	public void setEmployeeCode(String employeeCode);

	/**
	 * Returns the employee name of this emp master.
	 *
	 * @return the employee name of this emp master
	 */
	@AutoEscape
	public String getEmployeeName();

	/**
	 * Sets the employee name of this emp master.
	 *
	 * @param employeeName the employee name of this emp master
	 */
	public void setEmployeeName(String employeeName);

	/**
	 * Returns the mobile of this emp master.
	 *
	 * @return the mobile of this emp master
	 */
	@AutoEscape
	public String getMobile();

	/**
	 * Sets the mobile of this emp master.
	 *
	 * @param mobile the mobile of this emp master
	 */
	public void setMobile(String mobile);

	/**
	 * Returns the user defined1 of this emp master.
	 *
	 * @return the user defined1 of this emp master
	 */
	@AutoEscape
	public String getUserDefined1();

	/**
	 * Sets the user defined1 of this emp master.
	 *
	 * @param userDefined1 the user defined1 of this emp master
	 */
	public void setUserDefined1(String userDefined1);

	/**
	 * Returns the user defined2 of this emp master.
	 *
	 * @return the user defined2 of this emp master
	 */
	@AutoEscape
	public String getUserDefined2();

	/**
	 * Sets the user defined2 of this emp master.
	 *
	 * @param userDefined2 the user defined2 of this emp master
	 */
	public void setUserDefined2(String userDefined2);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(attendence.rinfra.services.model.EmpMaster empMaster);

	@Override
	public int hashCode();

	@Override
	public CacheModel<attendence.rinfra.services.model.EmpMaster> toCacheModel();

	@Override
	public attendence.rinfra.services.model.EmpMaster toEscapedModel();

	@Override
	public attendence.rinfra.services.model.EmpMaster toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}