/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package attendence.rinfra.services.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the EmpOtpMaster service. Represents a row in the &quot;EMP_OTP_MASTER&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link attendence.rinfra.services.model.impl.EmpOtpMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link attendence.rinfra.services.model.impl.EmpOtpMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmpOtpMaster
 * @see attendence.rinfra.services.model.impl.EmpOtpMasterImpl
 * @see attendence.rinfra.services.model.impl.EmpOtpMasterModelImpl
 * @generated
 */
@ProviderType
public interface EmpOtpMasterModel extends BaseModel<EmpOtpMaster> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a emp otp master model instance should use the {@link EmpOtpMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this emp otp master.
	 *
	 * @return the primary key of this emp otp master
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this emp otp master.
	 *
	 * @param primaryKey the primary key of this emp otp master
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the emp mobile of this emp otp master.
	 *
	 * @return the emp mobile of this emp otp master
	 */
	@AutoEscape
	public String getEmpMobile();

	/**
	 * Sets the emp mobile of this emp otp master.
	 *
	 * @param empMobile the emp mobile of this emp otp master
	 */
	public void setEmpMobile(String empMobile);

	/**
	 * Returns the otp of this emp otp master.
	 *
	 * @return the otp of this emp otp master
	 */
	@AutoEscape
	public String getOtp();

	/**
	 * Sets the otp of this emp otp master.
	 *
	 * @param otp the otp of this emp otp master
	 */
	public void setOtp(String otp);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		attendence.rinfra.services.model.EmpOtpMaster empOtpMaster);

	@Override
	public int hashCode();

	@Override
	public CacheModel<attendence.rinfra.services.model.EmpOtpMaster> toCacheModel();

	@Override
	public attendence.rinfra.services.model.EmpOtpMaster toEscapedModel();

	@Override
	public attendence.rinfra.services.model.EmpOtpMaster toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}