/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rinfra.unpaidunclaimedshares.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the unpaidUnclaimedDevidend service. Represents a row in the &quot;UNPAID_DIVIDEND_SHARE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rinfra.unpaidunclaimedshares.model.impl.unpaidUnclaimedDevidendModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rinfra.unpaidunclaimedshares.model.impl.unpaidUnclaimedDevidendImpl}.
 * </p>
 *
 * @author Mukesh Patidar
 * @see unpaidUnclaimedDevidend
 * @see com.rinfra.unpaidunclaimedshares.model.impl.unpaidUnclaimedDevidendImpl
 * @see com.rinfra.unpaidunclaimedshares.model.impl.unpaidUnclaimedDevidendModelImpl
 * @generated
 */
@ProviderType
public interface unpaidUnclaimedDevidendModel extends BaseModel<unpaidUnclaimedDevidend> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a unpaid unclaimed devidend model instance should use the {@link unpaidUnclaimedDevidend} interface instead.
	 */

	/**
	 * Returns the primary key of this unpaid unclaimed devidend.
	 *
	 * @return the primary key of this unpaid unclaimed devidend
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this unpaid unclaimed devidend.
	 *
	 * @param primaryKey the primary key of this unpaid unclaimed devidend
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the srno of this unpaid unclaimed devidend.
	 *
	 * @return the srno of this unpaid unclaimed devidend
	 */
	public long getSRNO();

	/**
	 * Sets the srno of this unpaid unclaimed devidend.
	 *
	 * @param SRNO the srno of this unpaid unclaimed devidend
	 */
	public void setSRNO(long SRNO);

	/**
	 * Returns the folio_no of this unpaid unclaimed devidend.
	 *
	 * @return the folio_no of this unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getFOLIO_NO();

	/**
	 * Sets the folio_no of this unpaid unclaimed devidend.
	 *
	 * @param FOLIO_NO the folio_no of this unpaid unclaimed devidend
	 */
	public void setFOLIO_NO(String FOLIO_NO);

	/**
	 * Returns the name of this unpaid unclaimed devidend.
	 *
	 * @return the name of this unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getNAME();

	/**
	 * Sets the name of this unpaid unclaimed devidend.
	 *
	 * @param NAME the name of this unpaid unclaimed devidend
	 */
	public void setNAME(String NAME);

	/**
	 * Returns the add1 of this unpaid unclaimed devidend.
	 *
	 * @return the add1 of this unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getADD1();

	/**
	 * Sets the add1 of this unpaid unclaimed devidend.
	 *
	 * @param ADD1 the add1 of this unpaid unclaimed devidend
	 */
	public void setADD1(String ADD1);

	/**
	 * Returns the add2 of this unpaid unclaimed devidend.
	 *
	 * @return the add2 of this unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getADD2();

	/**
	 * Sets the add2 of this unpaid unclaimed devidend.
	 *
	 * @param ADD2 the add2 of this unpaid unclaimed devidend
	 */
	public void setADD2(String ADD2);

	/**
	 * Returns the add3 of this unpaid unclaimed devidend.
	 *
	 * @return the add3 of this unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getADD3();

	/**
	 * Sets the add3 of this unpaid unclaimed devidend.
	 *
	 * @param ADD3 the add3 of this unpaid unclaimed devidend
	 */
	public void setADD3(String ADD3);

	/**
	 * Returns the add4 of this unpaid unclaimed devidend.
	 *
	 * @return the add4 of this unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getADD4();

	/**
	 * Sets the add4 of this unpaid unclaimed devidend.
	 *
	 * @param ADD4 the add4 of this unpaid unclaimed devidend
	 */
	public void setADD4(String ADD4);

	/**
	 * Returns the add5 of this unpaid unclaimed devidend.
	 *
	 * @return the add5 of this unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getADD5();

	/**
	 * Sets the add5 of this unpaid unclaimed devidend.
	 *
	 * @param ADD5 the add5 of this unpaid unclaimed devidend
	 */
	public void setADD5(String ADD5);

	/**
	 * Returns the add6 of this unpaid unclaimed devidend.
	 *
	 * @return the add6 of this unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getADD6();

	/**
	 * Sets the add6 of this unpaid unclaimed devidend.
	 *
	 * @param ADD6 the add6 of this unpaid unclaimed devidend
	 */
	public void setADD6(String ADD6);

	/**
	 * Returns the jt1 of this unpaid unclaimed devidend.
	 *
	 * @return the jt1 of this unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getJT1();

	/**
	 * Sets the jt1 of this unpaid unclaimed devidend.
	 *
	 * @param JT1 the jt1 of this unpaid unclaimed devidend
	 */
	public void setJT1(String JT1);

	/**
	 * Returns the jt2 of this unpaid unclaimed devidend.
	 *
	 * @return the jt2 of this unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getJT2();

	/**
	 * Sets the jt2 of this unpaid unclaimed devidend.
	 *
	 * @param JT2 the jt2 of this unpaid unclaimed devidend
	 */
	public void setJT2(String JT2);

	/**
	 * Returns the jt3 of this unpaid unclaimed devidend.
	 *
	 * @return the jt3 of this unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getJT3();

	/**
	 * Sets the jt3 of this unpaid unclaimed devidend.
	 *
	 * @param JT3 the jt3 of this unpaid unclaimed devidend
	 */
	public void setJT3(String JT3);

	/**
	 * Returns the shares of this unpaid unclaimed devidend.
	 *
	 * @return the shares of this unpaid unclaimed devidend
	 */
	@AutoEscape
	public String getSHARES();

	/**
	 * Sets the shares of this unpaid unclaimed devidend.
	 *
	 * @param SHARES the shares of this unpaid unclaimed devidend
	 */
	public void setSHARES(String SHARES);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rinfra.unpaidunclaimedshares.model.unpaidUnclaimedDevidend unpaidUnclaimedDevidend);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rinfra.unpaidunclaimedshares.model.unpaidUnclaimedDevidend> toCacheModel();

	@Override
	public com.rinfra.unpaidunclaimedshares.model.unpaidUnclaimedDevidend toEscapedModel();

	@Override
	public com.rinfra.unpaidunclaimedshares.model.unpaidUnclaimedDevidend toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}