/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.media.query.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the MediaQuery service. Represents a row in the &quot;MEDIA_QUERY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.media.query.model.impl.MediaQueryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.media.query.model.impl.MediaQueryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MediaQuery
 * @see com.media.query.model.impl.MediaQueryImpl
 * @see com.media.query.model.impl.MediaQueryModelImpl
 * @generated
 */
@ProviderType
public interface MediaQueryModel extends BaseModel<MediaQuery> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a media query model instance should use the {@link MediaQuery} interface instead.
	 */

	/**
	 * Returns the primary key of this media query.
	 *
	 * @return the primary key of this media query
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this media query.
	 *
	 * @param primaryKey the primary key of this media query
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sr no of this media query.
	 *
	 * @return the sr no of this media query
	 */
	public long getSrNo();

	/**
	 * Sets the sr no of this media query.
	 *
	 * @param srNo the sr no of this media query
	 */
	public void setSrNo(long srNo);

	/**
	 * Returns the journalist name of this media query.
	 *
	 * @return the journalist name of this media query
	 */
	@AutoEscape
	public String getJournalistName();

	/**
	 * Sets the journalist name of this media query.
	 *
	 * @param journalistName the journalist name of this media query
	 */
	public void setJournalistName(String journalistName);

	/**
	 * Returns the news organisation name of this media query.
	 *
	 * @return the news organisation name of this media query
	 */
	@AutoEscape
	public String getNewsOrganisationName();

	/**
	 * Sets the news organisation name of this media query.
	 *
	 * @param newsOrganisationName the news organisation name of this media query
	 */
	public void setNewsOrganisationName(String newsOrganisationName);

	/**
	 * Returns the organisation type of this media query.
	 *
	 * @return the organisation type of this media query
	 */
	@AutoEscape
	public String getOrganisationType();

	/**
	 * Sets the organisation type of this media query.
	 *
	 * @param organisationType the organisation type of this media query
	 */
	public void setOrganisationType(String organisationType);

	/**
	 * Returns the mobile of this media query.
	 *
	 * @return the mobile of this media query
	 */
	@AutoEscape
	public String getMobile();

	/**
	 * Sets the mobile of this media query.
	 *
	 * @param mobile the mobile of this media query
	 */
	public void setMobile(String mobile);

	/**
	 * Returns the email of this media query.
	 *
	 * @return the email of this media query
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this media query.
	 *
	 * @param email the email of this media query
	 */
	public void setEmail(String email);

	/**
	 * Returns the subject of this media query.
	 *
	 * @return the subject of this media query
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this media query.
	 *
	 * @param subject the subject of this media query
	 */
	public void setSubject(String subject);

	/**
	 * Returns the media query of this media query.
	 *
	 * @return the media query of this media query
	 */
	@AutoEscape
	public String getMediaQuery();

	/**
	 * Sets the media query of this media query.
	 *
	 * @param mediaQuery the media query of this media query
	 */
	public void setMediaQuery(String mediaQuery);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MediaQuery mediaQuery);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MediaQuery> toCacheModel();

	@Override
	public MediaQuery toEscapedModel();

	@Override
	public MediaQuery toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}