/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rinfra.satisfactionsurvey.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.rinfra.satisfactionsurvey.model.Shareholders;
import com.rinfra.satisfactionsurvey.model.ShareholdersModel;
import com.rinfra.satisfactionsurvey.model.ShareholdersSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Shareholders service. Represents a row in the &quot;SHAREHOLDERS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ShareholdersModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ShareholdersImpl}.
 * </p>
 *
 * @author Mukesh
 * @see ShareholdersImpl
 * @see Shareholders
 * @see ShareholdersModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ShareholdersModelImpl extends BaseModelImpl<Shareholders>
	implements ShareholdersModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a shareholders model instance should use the {@link Shareholders} interface instead.
	 */
	public static final String TABLE_NAME = "SHAREHOLDERS";
	public static final Object[][] TABLE_COLUMNS = {
			{ "SHAREHOLDERSID", Types.BIGINT },
			{ "SOLE_ID", Types.BIGINT },
			{ "SOLE_NAME", Types.VARCHAR },
			{ "ID_NUMBER", Types.BIGINT },
			{ "MOBILE", Types.BIGINT },
			{ "TELEPHONE", Types.BIGINT },
			{ "EMAIL", Types.VARCHAR },
			{ "QUERY_RESPONSE", Types.VARCHAR },
			{ "OVERALL_RATING", Types.VARCHAR },
			{ "COMP_INFORMATION", Types.VARCHAR },
			{ "QUALITY_REPORT", Types.VARCHAR },
			{ "DESCRIPTION", Types.VARCHAR },
			{ "COMMENTS", Types.VARCHAR },
			{ "GRIEVANCE", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("SHAREHOLDERSID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("SOLE_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("SOLE_NAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ID_NUMBER", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("MOBILE", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("TELEPHONE", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("EMAIL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("QUERY_RESPONSE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("OVERALL_RATING", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("COMP_INFORMATION", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("QUALITY_REPORT", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DESCRIPTION", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("COMMENTS", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("GRIEVANCE", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table SHAREHOLDERS (SHAREHOLDERSID LONG,SOLE_ID LONG not null primary key,SOLE_NAME VARCHAR(75) null,ID_NUMBER LONG,MOBILE LONG,TELEPHONE LONG,EMAIL VARCHAR(75) null,QUERY_RESPONSE VARCHAR(75) null,OVERALL_RATING VARCHAR(75) null,COMP_INFORMATION VARCHAR(75) null,QUALITY_REPORT VARCHAR(75) null,DESCRIPTION VARCHAR(75) null,COMMENTS VARCHAR(75) null,GRIEVANCE VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table SHAREHOLDERS";
	public static final String ORDER_BY_JPQL = " ORDER BY shareholders.SOLE_ID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SHAREHOLDERS.SOLE_ID ASC";
	public static final String DATA_SOURCE = "extDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.rinfra.satisfactionsurvey.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rinfra.satisfactionsurvey.model.Shareholders"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.rinfra.satisfactionsurvey.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rinfra.satisfactionsurvey.model.Shareholders"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Shareholders toModel(ShareholdersSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Shareholders model = new ShareholdersImpl();

		model.setSHAREHOLDERSID(soapModel.getSHAREHOLDERSID());
		model.setSOLE_ID(soapModel.getSOLE_ID());
		model.setSOLE_NAME(soapModel.getSOLE_NAME());
		model.setID_NUMBER(soapModel.getID_NUMBER());
		model.setMOBILE(soapModel.getMOBILE());
		model.setTELEPHONE(soapModel.getTELEPHONE());
		model.setEMAIL(soapModel.getEMAIL());
		model.setQUERY_RESPONSE(soapModel.getQUERY_RESPONSE());
		model.setOVERALL_RATING(soapModel.getOVERALL_RATING());
		model.setCOMP_INFORMATION(soapModel.getCOMP_INFORMATION());
		model.setQUALITY_REPORT(soapModel.getQUALITY_REPORT());
		model.setDESCRIPTION(soapModel.getDESCRIPTION());
		model.setCOMMENTS(soapModel.getCOMMENTS());
		model.setGRIEVANCE(soapModel.getGRIEVANCE());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Shareholders> toModels(ShareholdersSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Shareholders> models = new ArrayList<Shareholders>(soapModels.length);

		for (ShareholdersSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.rinfra.satisfactionsurvey.service.util.ServiceProps.get(
				"lock.expiration.time.com.rinfra.satisfactionsurvey.model.Shareholders"));

	public ShareholdersModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _SOLE_ID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSOLE_ID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _SOLE_ID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Shareholders.class;
	}

	@Override
	public String getModelClassName() {
		return Shareholders.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("SHAREHOLDERSID", getSHAREHOLDERSID());
		attributes.put("SOLE_ID", getSOLE_ID());
		attributes.put("SOLE_NAME", getSOLE_NAME());
		attributes.put("ID_NUMBER", getID_NUMBER());
		attributes.put("MOBILE", getMOBILE());
		attributes.put("TELEPHONE", getTELEPHONE());
		attributes.put("EMAIL", getEMAIL());
		attributes.put("QUERY_RESPONSE", getQUERY_RESPONSE());
		attributes.put("OVERALL_RATING", getOVERALL_RATING());
		attributes.put("COMP_INFORMATION", getCOMP_INFORMATION());
		attributes.put("QUALITY_REPORT", getQUALITY_REPORT());
		attributes.put("DESCRIPTION", getDESCRIPTION());
		attributes.put("COMMENTS", getCOMMENTS());
		attributes.put("GRIEVANCE", getGRIEVANCE());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long SHAREHOLDERSID = (Long)attributes.get("SHAREHOLDERSID");

		if (SHAREHOLDERSID != null) {
			setSHAREHOLDERSID(SHAREHOLDERSID);
		}

		Long SOLE_ID = (Long)attributes.get("SOLE_ID");

		if (SOLE_ID != null) {
			setSOLE_ID(SOLE_ID);
		}

		String SOLE_NAME = (String)attributes.get("SOLE_NAME");

		if (SOLE_NAME != null) {
			setSOLE_NAME(SOLE_NAME);
		}

		Long ID_NUMBER = (Long)attributes.get("ID_NUMBER");

		if (ID_NUMBER != null) {
			setID_NUMBER(ID_NUMBER);
		}

		Long MOBILE = (Long)attributes.get("MOBILE");

		if (MOBILE != null) {
			setMOBILE(MOBILE);
		}

		Long TELEPHONE = (Long)attributes.get("TELEPHONE");

		if (TELEPHONE != null) {
			setTELEPHONE(TELEPHONE);
		}

		String EMAIL = (String)attributes.get("EMAIL");

		if (EMAIL != null) {
			setEMAIL(EMAIL);
		}

		String QUERY_RESPONSE = (String)attributes.get("QUERY_RESPONSE");

		if (QUERY_RESPONSE != null) {
			setQUERY_RESPONSE(QUERY_RESPONSE);
		}

		String OVERALL_RATING = (String)attributes.get("OVERALL_RATING");

		if (OVERALL_RATING != null) {
			setOVERALL_RATING(OVERALL_RATING);
		}

		String COMP_INFORMATION = (String)attributes.get("COMP_INFORMATION");

		if (COMP_INFORMATION != null) {
			setCOMP_INFORMATION(COMP_INFORMATION);
		}

		String QUALITY_REPORT = (String)attributes.get("QUALITY_REPORT");

		if (QUALITY_REPORT != null) {
			setQUALITY_REPORT(QUALITY_REPORT);
		}

		String DESCRIPTION = (String)attributes.get("DESCRIPTION");

		if (DESCRIPTION != null) {
			setDESCRIPTION(DESCRIPTION);
		}

		String COMMENTS = (String)attributes.get("COMMENTS");

		if (COMMENTS != null) {
			setCOMMENTS(COMMENTS);
		}

		String GRIEVANCE = (String)attributes.get("GRIEVANCE");

		if (GRIEVANCE != null) {
			setGRIEVANCE(GRIEVANCE);
		}
	}

	@JSON
	@Override
	public long getSHAREHOLDERSID() {
		return _SHAREHOLDERSID;
	}

	@Override
	public void setSHAREHOLDERSID(long SHAREHOLDERSID) {
		_SHAREHOLDERSID = SHAREHOLDERSID;
	}

	@JSON
	@Override
	public long getSOLE_ID() {
		return _SOLE_ID;
	}

	@Override
	public void setSOLE_ID(long SOLE_ID) {
		_SOLE_ID = SOLE_ID;
	}

	@JSON
	@Override
	public String getSOLE_NAME() {
		if (_SOLE_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _SOLE_NAME;
		}
	}

	@Override
	public void setSOLE_NAME(String SOLE_NAME) {
		_SOLE_NAME = SOLE_NAME;
	}

	@JSON
	@Override
	public long getID_NUMBER() {
		return _ID_NUMBER;
	}

	@Override
	public void setID_NUMBER(long ID_NUMBER) {
		_ID_NUMBER = ID_NUMBER;
	}

	@JSON
	@Override
	public long getMOBILE() {
		return _MOBILE;
	}

	@Override
	public void setMOBILE(long MOBILE) {
		_MOBILE = MOBILE;
	}

	@JSON
	@Override
	public long getTELEPHONE() {
		return _TELEPHONE;
	}

	@Override
	public void setTELEPHONE(long TELEPHONE) {
		_TELEPHONE = TELEPHONE;
	}

	@JSON
	@Override
	public String getEMAIL() {
		if (_EMAIL == null) {
			return StringPool.BLANK;
		}
		else {
			return _EMAIL;
		}
	}

	@Override
	public void setEMAIL(String EMAIL) {
		_EMAIL = EMAIL;
	}

	@JSON
	@Override
	public String getQUERY_RESPONSE() {
		if (_QUERY_RESPONSE == null) {
			return StringPool.BLANK;
		}
		else {
			return _QUERY_RESPONSE;
		}
	}

	@Override
	public void setQUERY_RESPONSE(String QUERY_RESPONSE) {
		_QUERY_RESPONSE = QUERY_RESPONSE;
	}

	@JSON
	@Override
	public String getOVERALL_RATING() {
		if (_OVERALL_RATING == null) {
			return StringPool.BLANK;
		}
		else {
			return _OVERALL_RATING;
		}
	}

	@Override
	public void setOVERALL_RATING(String OVERALL_RATING) {
		_OVERALL_RATING = OVERALL_RATING;
	}

	@JSON
	@Override
	public String getCOMP_INFORMATION() {
		if (_COMP_INFORMATION == null) {
			return StringPool.BLANK;
		}
		else {
			return _COMP_INFORMATION;
		}
	}

	@Override
	public void setCOMP_INFORMATION(String COMP_INFORMATION) {
		_COMP_INFORMATION = COMP_INFORMATION;
	}

	@JSON
	@Override
	public String getQUALITY_REPORT() {
		if (_QUALITY_REPORT == null) {
			return StringPool.BLANK;
		}
		else {
			return _QUALITY_REPORT;
		}
	}

	@Override
	public void setQUALITY_REPORT(String QUALITY_REPORT) {
		_QUALITY_REPORT = QUALITY_REPORT;
	}

	@JSON
	@Override
	public String getDESCRIPTION() {
		if (_DESCRIPTION == null) {
			return StringPool.BLANK;
		}
		else {
			return _DESCRIPTION;
		}
	}

	@Override
	public void setDESCRIPTION(String DESCRIPTION) {
		_DESCRIPTION = DESCRIPTION;
	}

	@JSON
	@Override
	public String getCOMMENTS() {
		if (_COMMENTS == null) {
			return StringPool.BLANK;
		}
		else {
			return _COMMENTS;
		}
	}

	@Override
	public void setCOMMENTS(String COMMENTS) {
		_COMMENTS = COMMENTS;
	}

	@JSON
	@Override
	public String getGRIEVANCE() {
		if (_GRIEVANCE == null) {
			return StringPool.BLANK;
		}
		else {
			return _GRIEVANCE;
		}
	}

	@Override
	public void setGRIEVANCE(String GRIEVANCE) {
		_GRIEVANCE = GRIEVANCE;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Shareholders.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Shareholders toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Shareholders)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ShareholdersImpl shareholdersImpl = new ShareholdersImpl();

		shareholdersImpl.setSHAREHOLDERSID(getSHAREHOLDERSID());
		shareholdersImpl.setSOLE_ID(getSOLE_ID());
		shareholdersImpl.setSOLE_NAME(getSOLE_NAME());
		shareholdersImpl.setID_NUMBER(getID_NUMBER());
		shareholdersImpl.setMOBILE(getMOBILE());
		shareholdersImpl.setTELEPHONE(getTELEPHONE());
		shareholdersImpl.setEMAIL(getEMAIL());
		shareholdersImpl.setQUERY_RESPONSE(getQUERY_RESPONSE());
		shareholdersImpl.setOVERALL_RATING(getOVERALL_RATING());
		shareholdersImpl.setCOMP_INFORMATION(getCOMP_INFORMATION());
		shareholdersImpl.setQUALITY_REPORT(getQUALITY_REPORT());
		shareholdersImpl.setDESCRIPTION(getDESCRIPTION());
		shareholdersImpl.setCOMMENTS(getCOMMENTS());
		shareholdersImpl.setGRIEVANCE(getGRIEVANCE());

		shareholdersImpl.resetOriginalValues();

		return shareholdersImpl;
	}

	@Override
	public int compareTo(Shareholders shareholders) {
		long primaryKey = shareholders.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Shareholders)) {
			return false;
		}

		Shareholders shareholders = (Shareholders)obj;

		long primaryKey = shareholders.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Shareholders> toCacheModel() {
		ShareholdersCacheModel shareholdersCacheModel = new ShareholdersCacheModel();

		shareholdersCacheModel.SHAREHOLDERSID = getSHAREHOLDERSID();

		shareholdersCacheModel.SOLE_ID = getSOLE_ID();

		shareholdersCacheModel.SOLE_NAME = getSOLE_NAME();

		String SOLE_NAME = shareholdersCacheModel.SOLE_NAME;

		if ((SOLE_NAME != null) && (SOLE_NAME.length() == 0)) {
			shareholdersCacheModel.SOLE_NAME = null;
		}

		shareholdersCacheModel.ID_NUMBER = getID_NUMBER();

		shareholdersCacheModel.MOBILE = getMOBILE();

		shareholdersCacheModel.TELEPHONE = getTELEPHONE();

		shareholdersCacheModel.EMAIL = getEMAIL();

		String EMAIL = shareholdersCacheModel.EMAIL;

		if ((EMAIL != null) && (EMAIL.length() == 0)) {
			shareholdersCacheModel.EMAIL = null;
		}

		shareholdersCacheModel.QUERY_RESPONSE = getQUERY_RESPONSE();

		String QUERY_RESPONSE = shareholdersCacheModel.QUERY_RESPONSE;

		if ((QUERY_RESPONSE != null) && (QUERY_RESPONSE.length() == 0)) {
			shareholdersCacheModel.QUERY_RESPONSE = null;
		}

		shareholdersCacheModel.OVERALL_RATING = getOVERALL_RATING();

		String OVERALL_RATING = shareholdersCacheModel.OVERALL_RATING;

		if ((OVERALL_RATING != null) && (OVERALL_RATING.length() == 0)) {
			shareholdersCacheModel.OVERALL_RATING = null;
		}

		shareholdersCacheModel.COMP_INFORMATION = getCOMP_INFORMATION();

		String COMP_INFORMATION = shareholdersCacheModel.COMP_INFORMATION;

		if ((COMP_INFORMATION != null) && (COMP_INFORMATION.length() == 0)) {
			shareholdersCacheModel.COMP_INFORMATION = null;
		}

		shareholdersCacheModel.QUALITY_REPORT = getQUALITY_REPORT();

		String QUALITY_REPORT = shareholdersCacheModel.QUALITY_REPORT;

		if ((QUALITY_REPORT != null) && (QUALITY_REPORT.length() == 0)) {
			shareholdersCacheModel.QUALITY_REPORT = null;
		}

		shareholdersCacheModel.DESCRIPTION = getDESCRIPTION();

		String DESCRIPTION = shareholdersCacheModel.DESCRIPTION;

		if ((DESCRIPTION != null) && (DESCRIPTION.length() == 0)) {
			shareholdersCacheModel.DESCRIPTION = null;
		}

		shareholdersCacheModel.COMMENTS = getCOMMENTS();

		String COMMENTS = shareholdersCacheModel.COMMENTS;

		if ((COMMENTS != null) && (COMMENTS.length() == 0)) {
			shareholdersCacheModel.COMMENTS = null;
		}

		shareholdersCacheModel.GRIEVANCE = getGRIEVANCE();

		String GRIEVANCE = shareholdersCacheModel.GRIEVANCE;

		if ((GRIEVANCE != null) && (GRIEVANCE.length() == 0)) {
			shareholdersCacheModel.GRIEVANCE = null;
		}

		return shareholdersCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{SHAREHOLDERSID=");
		sb.append(getSHAREHOLDERSID());
		sb.append(", SOLE_ID=");
		sb.append(getSOLE_ID());
		sb.append(", SOLE_NAME=");
		sb.append(getSOLE_NAME());
		sb.append(", ID_NUMBER=");
		sb.append(getID_NUMBER());
		sb.append(", MOBILE=");
		sb.append(getMOBILE());
		sb.append(", TELEPHONE=");
		sb.append(getTELEPHONE());
		sb.append(", EMAIL=");
		sb.append(getEMAIL());
		sb.append(", QUERY_RESPONSE=");
		sb.append(getQUERY_RESPONSE());
		sb.append(", OVERALL_RATING=");
		sb.append(getOVERALL_RATING());
		sb.append(", COMP_INFORMATION=");
		sb.append(getCOMP_INFORMATION());
		sb.append(", QUALITY_REPORT=");
		sb.append(getQUALITY_REPORT());
		sb.append(", DESCRIPTION=");
		sb.append(getDESCRIPTION());
		sb.append(", COMMENTS=");
		sb.append(getCOMMENTS());
		sb.append(", GRIEVANCE=");
		sb.append(getGRIEVANCE());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("com.rinfra.satisfactionsurvey.model.Shareholders");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>SHAREHOLDERSID</column-name><column-value><![CDATA[");
		sb.append(getSHAREHOLDERSID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SOLE_ID</column-name><column-value><![CDATA[");
		sb.append(getSOLE_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SOLE_NAME</column-name><column-value><![CDATA[");
		sb.append(getSOLE_NAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ID_NUMBER</column-name><column-value><![CDATA[");
		sb.append(getID_NUMBER());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MOBILE</column-name><column-value><![CDATA[");
		sb.append(getMOBILE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TELEPHONE</column-name><column-value><![CDATA[");
		sb.append(getTELEPHONE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>EMAIL</column-name><column-value><![CDATA[");
		sb.append(getEMAIL());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>QUERY_RESPONSE</column-name><column-value><![CDATA[");
		sb.append(getQUERY_RESPONSE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>OVERALL_RATING</column-name><column-value><![CDATA[");
		sb.append(getOVERALL_RATING());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>COMP_INFORMATION</column-name><column-value><![CDATA[");
		sb.append(getCOMP_INFORMATION());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>QUALITY_REPORT</column-name><column-value><![CDATA[");
		sb.append(getQUALITY_REPORT());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DESCRIPTION</column-name><column-value><![CDATA[");
		sb.append(getDESCRIPTION());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>COMMENTS</column-name><column-value><![CDATA[");
		sb.append(getCOMMENTS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>GRIEVANCE</column-name><column-value><![CDATA[");
		sb.append(getGRIEVANCE());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Shareholders.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Shareholders.class
		};
	private long _SHAREHOLDERSID;
	private long _SOLE_ID;
	private String _SOLE_NAME;
	private long _ID_NUMBER;
	private long _MOBILE;
	private long _TELEPHONE;
	private String _EMAIL;
	private String _QUERY_RESPONSE;
	private String _OVERALL_RATING;
	private String _COMP_INFORMATION;
	private String _QUALITY_REPORT;
	private String _DESCRIPTION;
	private String _COMMENTS;
	private String _GRIEVANCE;
	private Shareholders _escapedModel;
}